#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <errno.h>
#include <unistd.h>
#include <sys/stat.h>
#include <dirent.h>

#include "esp_log.h"
#include "esp_spiffs.h"
#include "screen_flash_store.h"

#define TAG "ScreenStore"

#define MOUNT_PATH "/spiffs"
#define PARTITION_LABEL "screen_data"
#define SCREENS_DIR MOUNT_PATH "/screens"
#define IMAGES_DIR MOUNT_PATH "/images"
#define WRITE_CHUNK_SIZE 4096
#define SPIFFS_WRITE_OVERHEAD 1024

static bool s_is_mounted = false;

static const esp_vfs_spiffs_conf_t s_spiffs_conf = {
    .base_path = MOUNT_PATH,
    .partition_label = PARTITION_LABEL,
    .max_files = 64,
    .format_if_mount_failed = true
};

// Embedded default JSON symbols generated by CMake EMBED_TXTFILES
extern const char _binary_start_up_screen_json_start[];
extern const char _binary_start_up_screen_json_end[];

extern const char _binary_home_screen_json_start[];
extern const char _binary_home_screen_json_end[];

extern const char _binary_main_menu_json_start[];
extern const char _binary_main_menu_json_end[];

extern const char _binary_network_config_json_start[];
extern const char _binary_network_config_json_end[];

extern const char _binary_parameters_json_start[];
extern const char _binary_parameters_json_end[];

extern const char _binary_protocols_json_start[];
extern const char _binary_protocols_json_end[];

extern const char _binary_schedule_edit_screen_json_start[];
extern const char _binary_schedule_edit_screen_json_end[];

extern const char _binary_schedule_screen_json_start[];
extern const char _binary_schedule_screen_json_end[];

extern const char _binary_time_json_start[];
extern const char _binary_time_json_end[];

extern const char _binary_wifi_config_json_start[];
extern const char _binary_wifi_config_json_end[];

extern const char _binary_holiday_calender_screen_json_start[];
extern const char _binary_holiday_calender_screen_json_end[];

extern const char _binary_wireguard_screen_json_start[];
extern const char _binary_wireguard_screen_json_end[];

extern const char _binary_ddns_screen_json_start[];
extern const char _binary_ddns_screen_json_end[];

// Embedded default Image symbols generated by CMake EMBED_TXTFILES
extern const char _binary_power_symbol_30_json_start[];
extern const char _binary_power_symbol_30_json_end[];
extern const char _binary_calendar_40_json_start[];
extern const char _binary_calendar_40_json_end[];
extern const char _binary_control_panel_40_json_start[];
extern const char _binary_control_panel_40_json_end[];
extern const char _binary_day_30_json_start[];
extern const char _binary_day_30_json_end[];
extern const char _binary_snowflake_30_json_start[];
extern const char _binary_snowflake_30_json_end[];
extern const char _binary_input_40_json_start[];
extern const char _binary_input_40_json_end[];
extern const char _binary_output_40_json_start[];
extern const char _binary_output_40_json_end[];
extern const char _binary_backsmallarrow_json_start[];
extern const char _binary_backsmallarrow_json_end[];
extern const char _binary_displayhomescreendot_json_start[];
extern const char _binary_displayhomescreendot_json_end[];
extern const char _binary_displayscreendotformenuscreen_gray_json_start[];
extern const char _binary_displayscreendotformenuscreen_gray_json_end[];
extern const char _binary_fan_auto_new_json_start[];
extern const char _binary_fan_auto_new_json_end[];
extern const char _binary_fan_small_json_start[];
extern const char _binary_fan_small_json_end[];
extern const char _binary_fan_withtime_json_start[];
extern const char _binary_fan_withtime_json_end[];
extern const char _binary_leftarrow_json_start[];
extern const char _binary_leftarrow_json_end[];
extern const char _binary_rightarrow_json_start[];
extern const char _binary_rightarrow_json_end[];
extern const char _binary_wifisym_json_start[];
extern const char _binary_wifisym_json_end[];
extern const char _binary_wifisym_0_json_start[];
extern const char _binary_wifisym_0_json_end[];
extern const char _binary_wifisym_1_json_start[];
extern const char _binary_wifisym_1_json_end[];
extern const char _binary_wifisym_2_json_start[];
extern const char _binary_wifisym_2_json_end[];
extern const char _binary_wifisym_3_json_start[];
extern const char _binary_wifisym_3_json_end[];
extern const char _binary_wifisym_4_json_start[];
extern const char _binary_wifisym_4_json_end[];
extern const char _binary_wifisym_Disable_json_start[];
extern const char _binary_wifisym_Disable_json_end[];

typedef struct {
    const char *name;
    const char *start;
    const char *end;
} default_resource_entry_t;

static const default_resource_entry_t DEFAULT_SCREENS[] = {
    {"start_up_screen", _binary_start_up_screen_json_start, _binary_start_up_screen_json_end},
    {"home_screen", _binary_home_screen_json_start, _binary_home_screen_json_end},
    {"main_menu", _binary_main_menu_json_start, _binary_main_menu_json_end},
    {"network_config", _binary_network_config_json_start, _binary_network_config_json_end},
    {"parameters", _binary_parameters_json_start, _binary_parameters_json_end},
    {"protocols", _binary_protocols_json_start, _binary_protocols_json_end},
    {"schedule_edit_screen", _binary_schedule_edit_screen_json_start, _binary_schedule_edit_screen_json_end},
    {"schedule_screen", _binary_schedule_screen_json_start, _binary_schedule_screen_json_end},
    {"time", _binary_time_json_start, _binary_time_json_end},
    {"wifi_config", _binary_wifi_config_json_start, _binary_wifi_config_json_end},
    {"holiday_calender_screen", _binary_holiday_calender_screen_json_start, _binary_holiday_calender_screen_json_end},
    {"wireguard_screen", _binary_wireguard_screen_json_start, _binary_wireguard_screen_json_end},
    {"ddns_screen", _binary_ddns_screen_json_start, _binary_ddns_screen_json_end},
};

static const size_t DEFAULT_SCREENS_COUNT = sizeof(DEFAULT_SCREENS) / sizeof(DEFAULT_SCREENS[0]);

static const default_resource_entry_t DEFAULT_IMAGES[] = {
    {"power_symbol_30", _binary_power_symbol_30_json_start, _binary_power_symbol_30_json_end},
    {"calendar_40", _binary_calendar_40_json_start, _binary_calendar_40_json_end},
    {"control_panel_40", _binary_control_panel_40_json_start, _binary_control_panel_40_json_end},
    {"day_30", _binary_day_30_json_start, _binary_day_30_json_end},
    {"snowflake_30", _binary_snowflake_30_json_start, _binary_snowflake_30_json_end},
    {"input_40", _binary_input_40_json_start, _binary_input_40_json_end},
    {"output_40", _binary_output_40_json_start, _binary_output_40_json_end},
    {"backsmallarrow", _binary_backsmallarrow_json_start, _binary_backsmallarrow_json_end},
    {"displayhomescreendot", _binary_displayhomescreendot_json_start, _binary_displayhomescreendot_json_end},
    {"displayscreendotformenuscreen_gray", _binary_displayscreendotformenuscreen_gray_json_start, _binary_displayscreendotformenuscreen_gray_json_end},
    {"fan_auto_new", _binary_fan_auto_new_json_start, _binary_fan_auto_new_json_end},
    {"fan_small", _binary_fan_small_json_start, _binary_fan_small_json_end},
    {"fan_withtime", _binary_fan_withtime_json_start, _binary_fan_withtime_json_end},
    {"leftarrow", _binary_leftarrow_json_start, _binary_leftarrow_json_end},
    {"rightarrow", _binary_rightarrow_json_start, _binary_rightarrow_json_end},
    {"wifisym", _binary_wifisym_json_start, _binary_wifisym_json_end},
    {"wifisym_0", _binary_wifisym_0_json_start, _binary_wifisym_0_json_end},
    {"wifisym_1", _binary_wifisym_1_json_start, _binary_wifisym_1_json_end},
    {"wifisym_2", _binary_wifisym_2_json_start, _binary_wifisym_2_json_end},
    {"wifisym_3", _binary_wifisym_3_json_start, _binary_wifisym_3_json_end},
    {"wifisym_4", _binary_wifisym_4_json_start, _binary_wifisym_4_json_end},
    {"wifisym_Disable", _binary_wifisym_Disable_json_start, _binary_wifisym_Disable_json_end},
};

static const size_t DEFAULT_IMAGES_COUNT = sizeof(DEFAULT_IMAGES) / sizeof(DEFAULT_IMAGES[0]);

static void log_spiffs_usage(const char *when)
{
    size_t total = 0, used = 0;
    if (esp_spiffs_info(PARTITION_LABEL, &total, &used) == ESP_OK) {
        ESP_LOGI(TAG, "SPIFFS %s: used=%u KB, free=%u KB, total=%u KB",
                 when,
                 (unsigned)(used / 1024),
                 (unsigned)((total > used) ? ((total - used) / 1024) : 0),
                 (unsigned)(total / 1024));
    }
}

/*
 * SPIFFS cannot truncate or overwrite in place. fopen(..., "wb") on an
 * existing file keeps the old pages allocated, so fwrite() returns a short
 * count (ENOSPC) even when the payload is valid. That leaves a 0-byte or
 * truncated file; GET then reports "screen not found".
 * Unlink first so the old pages can be reused, then write + fsync.
 */
static esp_err_t write_file_replace(const char *path, const char *data, size_t len)
{
    if (!path || !data) return ESP_ERR_INVALID_ARG;

    struct stat st;
    size_t old_size = 0;
    bool exists = (stat(path, &st) == 0);
    if (exists && st.st_size > 0) {
        old_size = (size_t)st.st_size;
    }

    size_t total = 0, used = 0;
    if (esp_spiffs_info(PARTITION_LABEL, &total, &used) == ESP_OK) {
        size_t used_after_unlink = (used > old_size) ? (used - old_size) : 0;
        size_t free_after_unlink = (total > used_after_unlink) ? (total - used_after_unlink) : 0;
        if (free_after_unlink < len + SPIFFS_WRITE_OVERHEAD) {
            ESP_LOGE(TAG,
                     "Not enough SPIFFS space for %s: need %u bytes, free after replace ~%u (used=%u total=%u old=%u)",
                     path, (unsigned)len, (unsigned)free_after_unlink,
                     (unsigned)used, (unsigned)total, (unsigned)old_size);
            log_spiffs_usage("before rejected write");
            return ESP_ERR_NO_MEM;
        }
    }

    if (exists && remove(path) != 0) {
        ESP_LOGW(TAG, "Failed to unlink existing file before rewrite: %s (errno=%d)", path, errno);
    }

    FILE *f = fopen(path, "wb");
    if (!f) {
        ESP_LOGE(TAG, "Failed to open for writing: %s (errno=%d)", path, errno);
        return ESP_FAIL;
    }

    size_t written = 0;
    while (written < len) {
        size_t chunk = len - written;
        if (chunk > WRITE_CHUNK_SIZE) chunk = WRITE_CHUNK_SIZE;
        size_t n = fwrite(data + written, 1, chunk, f);
        if (n == 0) {
            ESP_LOGE(TAG, "fwrite stopped at %u/%u for %s (ferror=%d errno=%d)",
                     (unsigned)written, (unsigned)len, path, ferror(f), errno);
            break;
        }
        written += n;
    }

    int flush_err = fflush(f);
    int sync_err = 0;
    int fd = fileno(f);
    if (fd >= 0) {
        sync_err = fsync(fd);
    }
    int stream_err = ferror(f);
    fclose(f);

    if (written != len || flush_err != 0 || sync_err != 0 || stream_err) {
        ESP_LOGE(TAG, "Incomplete write %s (%u/%u) flush=%d sync=%d ferror=%d errno=%d",
                 path, (unsigned)written, (unsigned)len, flush_err, sync_err, stream_err, errno);
        remove(path);
        log_spiffs_usage("after failed write");
        return ESP_FAIL;
    }

    return ESP_OK;
}

static void ensure_directories_exist(void)
{
    struct stat st;
    if (stat(SCREENS_DIR, &st) != 0) {
        mkdir(SCREENS_DIR, 0755);
    }
    if (stat(IMAGES_DIR, &st) != 0) {
        mkdir(IMAGES_DIR, 0755);
    }
}

static esp_err_t seed_default_screens_if_empty(void)
{
    ensure_directories_exist();

    for (size_t i = 0; i < DEFAULT_SCREENS_COUNT; i++) {
        char path[128];
        snprintf(path, sizeof(path), "%s/%s.json", SCREENS_DIR, DEFAULT_SCREENS[i].name);

        struct stat st;
        if (stat(path, &st) != 0 || st.st_size == 0) {
            ESP_LOGI(TAG, "Seeding default screen: %s", DEFAULT_SCREENS[i].name);
            size_t len = (size_t)(DEFAULT_SCREENS[i].end - DEFAULT_SCREENS[i].start);
            if (write_file_replace(path, DEFAULT_SCREENS[i].start, len) != ESP_OK) {
                ESP_LOGE(TAG, "Failed to create default screen file: %s", path);
            }
        }
    }

    for (size_t i = 0; i < DEFAULT_IMAGES_COUNT; i++) {
        char path[128];
        snprintf(path, sizeof(path), "%s/%s.json", IMAGES_DIR, DEFAULT_IMAGES[i].name);

        struct stat st;
        if (stat(path, &st) != 0 || st.st_size == 0) {
            ESP_LOGI(TAG, "Seeding default image: %s", DEFAULT_IMAGES[i].name);
            size_t len = (size_t)(DEFAULT_IMAGES[i].end - DEFAULT_IMAGES[i].start);
            if (write_file_replace(path, DEFAULT_IMAGES[i].start, len) != ESP_OK) {
                ESP_LOGE(TAG, "Failed to create default image file: %s", path);
            }
        }
    }
    return ESP_OK;
}

static esp_err_t mount_spiffs(void)
{
    esp_err_t ret = esp_vfs_spiffs_register(&s_spiffs_conf);
    if (ret != ESP_OK) {
        if (ret == ESP_FAIL) {
            ESP_LOGE(TAG, "Failed to mount or format filesystem");
        } else if (ret == ESP_ERR_NOT_FOUND) {
            ESP_LOGE(TAG, "Failed to find SPIFFS partition 'screen_data'");
        } else {
            ESP_LOGE(TAG, "Failed to initialize SPIFFS (%s)", esp_err_to_name(ret));
        }
        return ret;
    }
    s_is_mounted = true;
    return ESP_OK;
}

static size_t count_default_files_present(const default_resource_entry_t *entries, size_t count, const char *dir)
{
    size_t present = 0;
    for (size_t i = 0; i < count; i++) {
        char path[128];
        struct stat st;
        snprintf(path, sizeof(path), "%s/%s.json", dir, entries[i].name);
        if (stat(path, &st) == 0 && st.st_size > 0) {
            present++;
        }
    }
    return present;
}

esp_err_t screen_store_init(void)
{
    if (s_is_mounted) return ESP_OK;

    ESP_LOGI(TAG, "Initializing SPIFFS partition screen_data");

    esp_err_t ret = mount_spiffs();
    if (ret != ESP_OK) {
        return ret;
    }

    log_spiffs_usage("after mount");
    seed_default_screens_if_empty();
    log_spiffs_usage("after seed");
    return ESP_OK;
}

bool screen_store_is_ready(void)
{
    return s_is_mounted;
}

esp_err_t screen_store_get_screen(const char *name, char **out_buf, size_t *out_size)
{
    if (!s_is_mounted || !name || !out_buf) return ESP_ERR_INVALID_ARG;

    char path[128];
    snprintf(path, sizeof(path), "%s/%s.json", SCREENS_DIR, name);

    FILE *f = fopen(path, "rb");
    if (!f) {
        ESP_LOGW(TAG, "Screen not found: %s", path);
        return ESP_ERR_NOT_FOUND;
    }

    fseek(f, 0, SEEK_END);
    long sz = ftell(f);
    fseek(f, 0, SEEK_SET);

    if (sz <= 0) {
        fclose(f);
        ESP_LOGW(TAG, "Screen file empty or truncated: %s", path);
        return ESP_ERR_INVALID_SIZE;
    }

    char *buf = (char *)malloc(sz + 1);
    if (!buf) {
        fclose(f);
        return ESP_ERR_NO_MEM;
    }

    size_t read_bytes = fread(buf, 1, sz, f);
    fclose(f);

    buf[read_bytes] = '\0';
    *out_buf = buf;
    if (out_size) *out_size = read_bytes;

    return ESP_OK;
}

esp_err_t screen_store_save_screen(const char *name, const char *json_data, size_t len)
{
    if (!s_is_mounted || !name || !json_data) return ESP_ERR_INVALID_ARG;

    ensure_directories_exist();

    if (len == 0) len = strlen(json_data);

    char path[128];
    snprintf(path, sizeof(path), "%s/%s.json", SCREENS_DIR, name);

    esp_err_t err = write_file_replace(path, json_data, len);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "Failed to write complete screen data: %s (%u bytes) err=%s",
                 name, (unsigned)len, esp_err_to_name(err));
        return err;
    }

    ESP_LOGI(TAG, "Saved screen to flash: %s (%u bytes)", name, (unsigned)len);
    return ESP_OK;
}

esp_err_t screen_store_delete_screen(const char *name)
{
    if (!s_is_mounted || !name) return ESP_ERR_INVALID_ARG;

    char path[128];
    snprintf(path, sizeof(path), "%s/%s.json", SCREENS_DIR, name);

    if (remove(path) == 0) {
        ESP_LOGI(TAG, "Deleted screen: %s", name);
        return ESP_OK;
    }

    return ESP_ERR_NOT_FOUND;
}

esp_err_t screen_store_list_screens(char names[][64], size_t max_count, size_t *out_count)
{
    if (!s_is_mounted || !names || !out_count) return ESP_ERR_INVALID_ARG;

    size_t count = 0;
    DIR *dir = opendir(SCREENS_DIR);
    if (!dir) {
        *out_count = 0;
        return ESP_OK;
    }

    struct dirent *entry;
    while ((entry = readdir(dir)) != NULL && count < max_count) {
        if (entry->d_type == DT_REG || entry->d_type == DT_UNKNOWN) {
            char *dot = strrchr(entry->d_name, '.');
            if (dot && strcmp(dot, ".json") == 0) {
                size_t name_len = dot - entry->d_name;
                if (name_len < 64) {
                    strncpy(names[count], entry->d_name, name_len);
                    names[count][name_len] = '\0';
                    count++;
                }
            }
        }
    }
    closedir(dir);

    *out_count = count;
    return ESP_OK;
}

esp_err_t screen_store_save_image(const char *name, const char *json_payload)
{
    if (!s_is_mounted || !name || !json_payload) return ESP_ERR_INVALID_ARG;

    ensure_directories_exist();

    char path[128];
    snprintf(path, sizeof(path), "%s/%s.json", IMAGES_DIR, name);

    size_t len = strlen(json_payload);
    esp_err_t err = write_file_replace(path, json_payload, len);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "Failed to write complete image data: %s (%u bytes) err=%s",
                 name, (unsigned)len, esp_err_to_name(err));
        return err;
    }

    ESP_LOGI(TAG, "Saved image to flash: %s (%u bytes)", name, (unsigned)len);
    return ESP_OK;
}

esp_err_t screen_store_get_image(const char *name, char **out_buf, size_t *out_size)
{
    if (!s_is_mounted || !name || !out_buf) return ESP_ERR_INVALID_ARG;

    char path[128];
    snprintf(path, sizeof(path), "%s/%s.json", IMAGES_DIR, name);

    FILE *f = fopen(path, "rb");
    if (!f) {
        return ESP_ERR_NOT_FOUND;
    }

    fseek(f, 0, SEEK_END);
    long sz = ftell(f);
    fseek(f, 0, SEEK_SET);

    if (sz <= 0) {
        fclose(f);
        return ESP_ERR_INVALID_SIZE;
    }

    char *buf = (char *)malloc(sz + 1);
    if (!buf) {
        fclose(f);
        return ESP_ERR_NO_MEM;
    }

    size_t read_bytes = fread(buf, 1, sz, f);
    fclose(f);

    buf[read_bytes] = '\0';
    *out_buf = buf;
    if (out_size) *out_size = read_bytes;

    return ESP_OK;
}

esp_err_t screen_store_delete_image(const char *name)
{
    if (!s_is_mounted || !name) return ESP_ERR_INVALID_ARG;

    char path[128];
    snprintf(path, sizeof(path), "%s/%s.json", IMAGES_DIR, name);

    if (remove(path) == 0) {
        ESP_LOGI(TAG, "Deleted image: %s", name);
        return ESP_OK;
    }

    return ESP_ERR_NOT_FOUND;
}

esp_err_t screen_store_list_images(char names[][64], size_t max_count, size_t *out_count)
{
    if (!s_is_mounted || !names || !out_count) return ESP_ERR_INVALID_ARG;

    size_t count = 0;
    DIR *dir = opendir(IMAGES_DIR);
    if (!dir) {
        *out_count = 0;
        return ESP_OK;
    }

    struct dirent *entry;
    while ((entry = readdir(dir)) != NULL && count < max_count) {
        if (entry->d_type == DT_REG || entry->d_type == DT_UNKNOWN) {
            char *dot = strrchr(entry->d_name, '.');
            if (dot && strcmp(dot, ".json") == 0) {
                size_t name_len = dot - entry->d_name;
                if (name_len < 64) {
                    strncpy(names[count], entry->d_name, name_len);
                    names[count][name_len] = '\0';
                    count++;
                }
            }
        }
    }
    closedir(dir);

    *out_count = count;
    return ESP_OK;
}

esp_err_t screen_store_reset_to_defaults(void)
{
    if (!s_is_mounted && !esp_spiffs_mounted(PARTITION_LABEL)) {
        return ESP_ERR_INVALID_STATE;
    }

    ESP_LOGW(TAG, "Formatting SPIFFS and restoring factory defaults");
    log_spiffs_usage("before reset");

    /* remove() does not reclaim SPIFFS pages. After a failed overwrite the
     * partition is fragmented/full, so delete+rewrite still short-writes and
     * GET returns "screen not found". Format gives a clean filesystem. */
    s_is_mounted = false;
    esp_err_t err = esp_vfs_spiffs_unregister(PARTITION_LABEL);
    if (err != ESP_OK) {
        ESP_LOGW(TAG, "SPIFFS unregister: %s", esp_err_to_name(err));
    }

    err = esp_spiffs_format(PARTITION_LABEL);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "SPIFFS format failed: %s", esp_err_to_name(err));
        mount_spiffs();
        return err;
    }

    err = mount_spiffs();
    if (err != ESP_OK) {
        return err;
    }

    seed_default_screens_if_empty();

    size_t screens_ok = count_default_files_present(DEFAULT_SCREENS, DEFAULT_SCREENS_COUNT, SCREENS_DIR);
    size_t images_ok = count_default_files_present(DEFAULT_IMAGES, DEFAULT_IMAGES_COUNT, IMAGES_DIR);

    log_spiffs_usage("after reset");
    ESP_LOGI(TAG, "Restored %u/%u default screens and %u/%u default images",
             (unsigned)screens_ok, (unsigned)DEFAULT_SCREENS_COUNT,
             (unsigned)images_ok, (unsigned)DEFAULT_IMAGES_COUNT);

    return (screens_ok == DEFAULT_SCREENS_COUNT && images_ok == DEFAULT_IMAGES_COUNT) ? ESP_OK : ESP_FAIL;
}
