// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: TemcoProject

#ifndef _TEMCOPROJECT_UI_H
#define _TEMCOPROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_StartUpScreen.h"
#include "ui_HomeScreen.h"
#include "ui_MainMenu.h"
#include "ui_ChangeConfig.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * StartName_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * InitAnimation_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * ShowItem_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * LeftInItem_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * RightIn_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_wifisym_png);    // assets/wifiSym.png
LV_IMG_DECLARE(ui_img_round_manage_accounts_black_36pt_1x_png);    // assets/round_manage_accounts_black_36pt_1x.png
LV_IMG_DECLARE(ui_img_round_arrow_back_black_36_png);    // assets/round_arrow_back_black_36.png

// FONTS
LV_FONT_DECLARE(ui_font_Arial80);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
