// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: TemcoProject

#ifndef _TEMCOPROJECT_UI_H
#define _TEMCOPROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_StartUpScreen.h"
#include "ui_HomeScreen.h"
#include "ui_MainMenu.h"
#include "ui_WifiConfig.h"
#include "ui_NetworkConfig.h"
#include "ui_Protocols.h"
#include "ui_Parameters.h"
#include "ui_Time.h"
#include "ui_ScheduleScreen.h"
#include "ui_ScheduleEditScreen.h"
#include "ui_HolidayCalenderScreen.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * StartName_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * InitAnimation_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * ShowItem_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * LeftInItem_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * RightIn_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_wifisym_png);    // assets/wifiSym.png
LV_IMG_DECLARE(ui_img_rightarrow_png);    // assets/RightArrow.png
LV_IMG_DECLARE(ui_img_displayhomescreendot_png);    // assets/DisplayHomeScreenDot.png
LV_IMG_DECLARE(ui_img_fan_auto_new_png);    // assets/fan_Auto_New.png
LV_IMG_DECLARE(ui_img_fan_small_png);    // assets/fan_small.png
LV_IMG_DECLARE(ui_img_fan_withtime_png);    // assets/fan_withTime.png
LV_IMG_DECLARE(ui_img_1679221590);    // assets/icons8-day-30.png
LV_IMG_DECLARE(ui_img_1020677502);    // assets/icons8-power-symbol-30.png
LV_IMG_DECLARE(ui_img_1869774352);    // assets/icons8-snowflake-30.png
LV_IMG_DECLARE(ui_img_leftarrow_png);    // assets/LeftArrow.png
LV_IMG_DECLARE(ui_img_displayscreendotformenuscreen_gray_png);    // assets/DisplayScreenDotForMenuScreen_Gray.png
LV_IMG_DECLARE(ui_img_1984394067);    // assets/icons8-input-40.png
LV_IMG_DECLARE(ui_img_444508050);    // assets/icons8-output-40.png
LV_IMG_DECLARE(ui_img_1589547977);    // assets/icons8-control-panel-40.png
LV_IMG_DECLARE(ui_img_1207302323);    // assets/icons8-event-accepted-tentatively-40 (1).png
LV_IMG_DECLARE(ui_img_backsmallarrow_png);    // assets/BackSmallArrow.png

// FONTS
LV_FONT_DECLARE(ui_font_Arial80);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
