// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: TemcoProject

#ifndef UI_CHANGECONFIG_H
#define UI_CHANGECONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ChangeConfig
extern void ui_ChangeConfig_screen_init(void);
extern void ui_ChangeConfig_screen_destroy(void);
extern void ui_event_ChangeConfig(lv_event_t * e);
extern lv_obj_t * ui_ChangeConfig;
extern lv_obj_t * ui_ChangeConfigTitle;
extern lv_obj_t * ui_MainMenuLbl2;
extern lv_obj_t * ui_WifiContainer;
extern lv_obj_t * ui_WifiEnPanel;
extern lv_obj_t * ui_WifiEnableStr;
extern void ui_event_WifiEnSw(lv_event_t * e);
extern lv_obj_t * ui_WifiEnSw;
extern lv_obj_t * ui_WifiPanelAutoIP;
extern lv_obj_t * ui_WifiEnableStr1;
extern void ui_event_WifiAutoIPSw(lv_event_t * e);
extern lv_obj_t * ui_WifiAutoIPSw;
extern lv_obj_t * ui_WifiSsidPanel;
extern lv_obj_t * ui_SSIDStr;
extern void ui_event_SSIDText(lv_event_t * e);
extern lv_obj_t * ui_SSIDText;
extern lv_obj_t * ui_WifiPassPanel;
extern lv_obj_t * ui_PasswordStr1;
extern void ui_event_PasswordText(lv_event_t * e);
extern lv_obj_t * ui_PasswordText;
extern lv_obj_t * ui_IpPanel;
extern lv_obj_t * ui_DropdownNetdata;
extern void ui_event_DommyDot(lv_event_t * e);
extern lv_obj_t * ui_DommyDot;
extern void ui_event_Octant1(lv_event_t * e);
extern lv_obj_t * ui_Octant1;
extern void ui_event_Octant2(lv_event_t * e);
extern lv_obj_t * ui_Octant2;
extern void ui_event_Octant3(lv_event_t * e);
extern lv_obj_t * ui_Octant3;
extern void ui_event_Octant4(lv_event_t * e);
extern lv_obj_t * ui_Octant4;
extern lv_obj_t * ui_BacNetPortPanel;
extern lv_obj_t * ui_BacNetPortStr;
extern void ui_event_BacNetText(lv_event_t * e);
extern lv_obj_t * ui_BacNetText;
extern lv_obj_t * ui_ModbusPortPanel;
extern lv_obj_t * ui_ModbusPortStr;
extern void ui_event_ModbusPortText(lv_event_t * e);
extern lv_obj_t * ui_ModbusPortText;
extern void ui_event_Keyboard(lv_event_t * e);
extern lv_obj_t * ui_Keyboard;
extern lv_obj_t * ui_NumKeyboard;
// CUSTOM VARIABLES
extern lv_obj_t * uic_WifiEnSw;
extern lv_obj_t * uic_SSIDText;
extern lv_obj_t * uic_PasswordText;
extern lv_obj_t * uic_Octant1;
extern lv_obj_t * uic_BacNetText;
extern lv_obj_t * uic_ModbusPortText;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

