// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: TemcoProject

#include "ui.h"

lv_obj_t * uic_ModbusPortText;
lv_obj_t * uic_BacNetText;
lv_obj_t * uic_Octant1;
lv_obj_t * uic_PasswordText;
lv_obj_t * uic_SSIDText;
lv_obj_t * uic_WifiEnSw;
lv_obj_t * ui_ChangeConfig = NULL;
lv_obj_t * ui_ChangeConfigTitle = NULL;
lv_obj_t * ui_MainMenuLbl2 = NULL;
lv_obj_t * ui_WifiContainer = NULL;
lv_obj_t * ui_WifiEnPanel = NULL;
lv_obj_t * ui_WifiEnableStr = NULL;
lv_obj_t * ui_WifiEnSw = NULL;
lv_obj_t * ui_WifiPanelAutoIP = NULL;
lv_obj_t * ui_WifiEnableStr1 = NULL;
lv_obj_t * ui_WifiAutoIPSw = NULL;
lv_obj_t * ui_WifiSsidPanel = NULL;
lv_obj_t * ui_SSIDStr = NULL;
lv_obj_t * ui_SSIDText = NULL;
lv_obj_t * ui_WifiPassPanel = NULL;
lv_obj_t * ui_PasswordStr1 = NULL;
lv_obj_t * ui_PasswordText = NULL;
lv_obj_t * ui_IpPanel = NULL;
lv_obj_t * ui_DropdownNetdata = NULL;
lv_obj_t * ui_DommyDot = NULL;
lv_obj_t * ui_Octant1 = NULL;
lv_obj_t * ui_Octant2 = NULL;
lv_obj_t * ui_Octant3 = NULL;
lv_obj_t * ui_Octant4 = NULL;
lv_obj_t * ui_BacNetPortPanel = NULL;
lv_obj_t * ui_BacNetPortStr = NULL;
lv_obj_t * ui_BacNetText = NULL;
lv_obj_t * ui_ModbusPortPanel = NULL;
lv_obj_t * ui_ModbusPortStr = NULL;
lv_obj_t * ui_ModbusPortText = NULL;
lv_obj_t * ui_Keyboard = NULL;
lv_obj_t * ui_NumKeyboard = NULL;
// event funtions
void ui_event_ChangeConfig(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_NumKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_WifiEnSw(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        WifiEnEvent(e);
    }
}

void ui_event_WifiAutoIPSw(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        IpAutoSelectFun(e);
    }
}

void ui_event_SSIDText(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard,  ui_SSIDText);
        _ui_flag_modify(ui_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_PasswordText(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard,  ui_PasswordText);
        _ui_flag_modify(ui_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_DommyDot(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard,  ui_DommyDot);
        _ui_flag_modify(ui_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Octant1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_NumKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_keyboard_set_target(ui_NumKeyboard,  ui_Octant1);
    }
}

void ui_event_Octant2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_NumKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_keyboard_set_target(ui_NumKeyboard,  ui_Octant2);
    }
}

void ui_event_Octant3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_NumKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_keyboard_set_target(ui_NumKeyboard,  ui_Octant3);
    }
}

void ui_event_Octant4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_NumKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_keyboard_set_target(ui_NumKeyboard,  ui_Octant4);
    }
}

void ui_event_BacNetText(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard,  ui_BacNetText);
        _ui_flag_modify(ui_NumKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_ModbusPortText(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard,  ui_ModbusPortText);
        _ui_flag_modify(ui_NumKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_Keyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        KeyPressFunc(e);
    }
}

// build funtions

void ui_ChangeConfig_screen_init(void)
{
    ui_ChangeConfig = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ChangeConfig, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ChangeConfigTitle = lv_obj_create(ui_ChangeConfig);
    lv_obj_set_width(ui_ChangeConfigTitle, 480);
    lv_obj_set_height(ui_ChangeConfigTitle, 30);
    lv_obj_set_align(ui_ChangeConfigTitle, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_ChangeConfigTitle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ChangeConfigTitle, lv_color_hex(0x2D70A0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChangeConfigTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainMenuLbl2 = lv_label_create(ui_ChangeConfigTitle);
    lv_obj_set_width(ui_MainMenuLbl2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainMenuLbl2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MainMenuLbl2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MainMenuLbl2, "Configurations");
    lv_obj_set_style_text_color(ui_MainMenuLbl2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MainMenuLbl2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiContainer = lv_obj_create(ui_ChangeConfig);
    lv_obj_remove_style_all(ui_WifiContainer);
    lv_obj_set_width(ui_WifiContainer, 480);
    lv_obj_set_height(ui_WifiContainer, 290);
    lv_obj_set_align(ui_WifiContainer, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_WifiContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiEnPanel = lv_obj_create(ui_WifiContainer);
    lv_obj_set_width(ui_WifiEnPanel, 226);
    lv_obj_set_height(ui_WifiEnPanel, 30);
    lv_obj_set_x(ui_WifiEnPanel, -120);
    lv_obj_set_y(ui_WifiEnPanel, 100);
    lv_obj_set_align(ui_WifiEnPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WifiEnPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiEnPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiEnPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_WifiEnPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiEnableStr = lv_label_create(ui_WifiEnPanel);
    lv_obj_set_width(ui_WifiEnableStr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiEnableStr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiEnableStr, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_WifiEnableStr, "Wifi Enable");
    lv_obj_remove_flag(ui_WifiEnableStr,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_WifiEnableStr, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiEnSw = lv_switch_create(ui_WifiEnPanel);
    lv_obj_set_width(ui_WifiEnSw, 50);
    lv_obj_set_height(ui_WifiEnSw, 25);
    lv_obj_set_align(ui_WifiEnSw, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_WifiEnSw, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_WifiEnSw, lv_color_hex(0x868383), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiEnSw, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiPanelAutoIP = lv_obj_create(ui_WifiContainer);
    lv_obj_set_width(ui_WifiPanelAutoIP, 226);
    lv_obj_set_height(ui_WifiPanelAutoIP, 30);
    lv_obj_set_x(ui_WifiPanelAutoIP, 120);
    lv_obj_set_y(ui_WifiPanelAutoIP, 100);
    lv_obj_set_align(ui_WifiPanelAutoIP, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WifiPanelAutoIP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiPanelAutoIP, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiPanelAutoIP, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_WifiPanelAutoIP, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiEnableStr1 = lv_label_create(ui_WifiPanelAutoIP);
    lv_obj_set_width(ui_WifiEnableStr1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiEnableStr1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiEnableStr1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_WifiEnableStr1, "IP Auto Select");
    lv_obj_remove_flag(ui_WifiEnableStr1,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_WifiEnableStr1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiAutoIPSw = lv_switch_create(ui_WifiPanelAutoIP);
    lv_obj_set_width(ui_WifiAutoIPSw, 50);
    lv_obj_set_height(ui_WifiAutoIPSw, 25);
    lv_obj_set_align(ui_WifiAutoIPSw, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_WifiAutoIPSw, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_WifiAutoIPSw, lv_color_hex(0x868383), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiAutoIPSw, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiSsidPanel = lv_obj_create(ui_WifiContainer);
    lv_obj_set_width(ui_WifiSsidPanel, 445);
    lv_obj_set_height(ui_WifiSsidPanel, 30);
    lv_obj_set_x(ui_WifiSsidPanel, 0);
    lv_obj_set_y(ui_WifiSsidPanel, -125);
    lv_obj_set_align(ui_WifiSsidPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WifiSsidPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiSsidPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiSsidPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_WifiSsidPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SSIDStr = lv_label_create(ui_WifiSsidPanel);
    lv_obj_set_width(ui_SSIDStr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SSIDStr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SSIDStr, -10);
    lv_obj_set_y(ui_SSIDStr, 0);
    lv_obj_set_align(ui_SSIDStr, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_SSIDStr, "SSID           :");
    lv_obj_remove_flag(ui_SSIDStr, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_style_text_font(ui_SSIDStr, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SSIDText = lv_textarea_create(ui_WifiSsidPanel);
    lv_obj_set_width(ui_SSIDText, 315);
    lv_obj_set_height(ui_SSIDText, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_align(ui_SSIDText, LV_ALIGN_RIGHT_MID);
    lv_textarea_set_max_length(ui_SSIDText, 64);
    lv_textarea_set_placeholder_text(ui_SSIDText, "Wifi SSID");
    lv_textarea_set_one_line(ui_SSIDText, true);
    lv_obj_set_style_radius(ui_SSIDText, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SSIDText, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiPassPanel = lv_obj_create(ui_WifiContainer);
    lv_obj_set_width(ui_WifiPassPanel, 445);
    lv_obj_set_height(ui_WifiPassPanel, 30);
    lv_obj_set_x(ui_WifiPassPanel, 0);
    lv_obj_set_y(ui_WifiPassPanel, -85);
    lv_obj_set_align(ui_WifiPassPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WifiPassPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiPassPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiPassPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_WifiPassPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PasswordStr1 = lv_label_create(ui_WifiPassPanel);
    lv_obj_set_width(ui_PasswordStr1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PasswordStr1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PasswordStr1, -10);
    lv_obj_set_y(ui_PasswordStr1, 0);
    lv_obj_set_align(ui_PasswordStr1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_PasswordStr1, "Password  :");
    lv_obj_remove_flag(ui_PasswordStr1, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM);    /// Flags
    lv_obj_set_style_text_font(ui_PasswordStr1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PasswordText = lv_textarea_create(ui_WifiPassPanel);
    lv_obj_set_width(ui_PasswordText, 315);
    lv_obj_set_height(ui_PasswordText, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_align(ui_PasswordText, LV_ALIGN_RIGHT_MID);
    lv_textarea_set_max_length(ui_PasswordText, 36);
    lv_textarea_set_placeholder_text(ui_PasswordText, "Wifi Password");
    lv_textarea_set_one_line(ui_PasswordText, true);
    lv_obj_set_style_radius(ui_PasswordText, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PasswordText, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IpPanel = lv_obj_create(ui_WifiContainer);
    lv_obj_set_width(ui_IpPanel, 445);
    lv_obj_set_height(ui_IpPanel, 30);
    lv_obj_set_x(ui_IpPanel, 0);
    lv_obj_set_y(ui_IpPanel, -45);
    lv_obj_set_align(ui_IpPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_IpPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_IpPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IpPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_IpPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropdownNetdata = lv_dropdown_create(ui_IpPanel);
    lv_dropdown_set_options(ui_DropdownNetdata, "IP Address\nNetMask\nGetway");
    lv_obj_set_width(ui_DropdownNetdata, 130);
    lv_obj_set_height(ui_DropdownNetdata, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownNetdata, -22);
    lv_obj_set_y(ui_DropdownNetdata, 0);
    lv_obj_set_align(ui_DropdownNetdata, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_DropdownNetdata, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_DropdownNetdata, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DropdownNetdata, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DropdownNetdata, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_DropdownNetdata, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DommyDot = lv_textarea_create(ui_IpPanel);
    lv_obj_set_width(ui_DommyDot, 200);
    lv_obj_set_height(ui_DommyDot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DommyDot, 45);
    lv_obj_set_y(ui_DommyDot, 0);
    lv_obj_set_align(ui_DommyDot, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_DommyDot, 36);
    lv_textarea_set_placeholder_text(ui_DommyDot, "         .            .            . ");
    lv_textarea_set_one_line(ui_DommyDot, true);
    lv_obj_remove_flag(ui_DommyDot, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_DommyDot, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_DommyDot, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_DommyDot, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_DommyDot, lv_color_hex(0xFFFFFF), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DommyDot, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_Octant1 = lv_textarea_create(ui_IpPanel);
    lv_obj_set_width(ui_Octant1, 35);
    lv_obj_set_height(ui_Octant1, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_Octant1, -30);
    lv_obj_set_y(ui_Octant1, 0);
    lv_obj_set_align(ui_Octant1, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_Octant1, "123456789");
    lv_textarea_set_max_length(ui_Octant1, 3);
    lv_textarea_set_placeholder_text(ui_Octant1, "192");
    lv_textarea_set_one_line(ui_Octant1, true);
    lv_obj_remove_flag(ui_Octant1, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_Octant1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Octant1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Octant1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Octant1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Octant1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Octant1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Octant1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Octant1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Octant1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Octant2 = lv_textarea_create(ui_IpPanel);
    lv_obj_set_width(ui_Octant2, 35);
    lv_obj_set_height(ui_Octant2, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_Octant2, 20);
    lv_obj_set_y(ui_Octant2, 0);
    lv_obj_set_align(ui_Octant2, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_Octant2, "123456789");
    lv_textarea_set_max_length(ui_Octant2, 3);
    lv_textarea_set_placeholder_text(ui_Octant2, "168");
    lv_textarea_set_one_line(ui_Octant2, true);
    lv_obj_remove_flag(ui_Octant2, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_Octant2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Octant2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Octant2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Octant2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Octant2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Octant2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Octant2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Octant2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Octant2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Octant3 = lv_textarea_create(ui_IpPanel);
    lv_obj_set_width(ui_Octant3, 35);
    lv_obj_set_height(ui_Octant3, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_Octant3, 70);
    lv_obj_set_y(ui_Octant3, 0);
    lv_obj_set_align(ui_Octant3, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_Octant3, "123456789");
    lv_textarea_set_max_length(ui_Octant3, 3);
    lv_textarea_set_placeholder_text(ui_Octant3, "000");
    lv_textarea_set_one_line(ui_Octant3, true);
    lv_obj_remove_flag(ui_Octant3, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_Octant3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Octant3, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Octant3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Octant3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Octant3, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Octant3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Octant3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Octant3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Octant3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Octant4 = lv_textarea_create(ui_IpPanel);
    lv_obj_set_width(ui_Octant4, 35);
    lv_obj_set_height(ui_Octant4, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_Octant4, 120);
    lv_obj_set_y(ui_Octant4, 0);
    lv_obj_set_align(ui_Octant4, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_Octant4, "123456789");
    lv_textarea_set_max_length(ui_Octant4, 3);
    lv_textarea_set_placeholder_text(ui_Octant4, "001");
    lv_textarea_set_one_line(ui_Octant4, true);
    lv_obj_remove_flag(ui_Octant4, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_Octant4, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Octant4, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Octant4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Octant4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Octant4, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Octant4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Octant4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Octant4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Octant4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BacNetPortPanel = lv_obj_create(ui_WifiContainer);
    lv_obj_set_width(ui_BacNetPortPanel, 445);
    lv_obj_set_height(ui_BacNetPortPanel, 30);
    lv_obj_set_align(ui_BacNetPortPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_BacNetPortPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BacNetPortPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BacNetPortPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BacNetPortPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BacNetPortStr = lv_label_create(ui_BacNetPortPanel);
    lv_obj_set_width(ui_BacNetPortStr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BacNetPortStr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BacNetPortStr, -10);
    lv_obj_set_y(ui_BacNetPortStr, 0);
    lv_obj_set_align(ui_BacNetPortStr, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BacNetPortStr, "Bacnet Port       :");
    lv_obj_remove_flag(ui_BacNetPortStr,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);    /// Flags
    lv_obj_set_style_text_font(ui_BacNetPortStr, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BacNetText = lv_textarea_create(ui_BacNetPortPanel);
    lv_obj_set_width(ui_BacNetText, 150);
    lv_obj_set_height(ui_BacNetText, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_x(ui_BacNetText, 20);
    lv_obj_set_y(ui_BacNetText, 0);
    lv_obj_set_align(ui_BacNetText, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_BacNetText, "0123456789");
    lv_textarea_set_max_length(ui_BacNetText, 5);
    lv_textarea_set_placeholder_text(ui_BacNetText, "Port");
    lv_textarea_set_one_line(ui_BacNetText, true);
    lv_obj_set_style_radius(ui_BacNetText, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BacNetText, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ModbusPortPanel = lv_obj_create(ui_WifiContainer);
    lv_obj_set_width(ui_ModbusPortPanel, 445);
    lv_obj_set_height(ui_ModbusPortPanel, 30);
    lv_obj_set_x(ui_ModbusPortPanel, 0);
    lv_obj_set_y(ui_ModbusPortPanel, 40);
    lv_obj_set_align(ui_ModbusPortPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ModbusPortPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ModbusPortPanel, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ModbusPortPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ModbusPortPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ModbusPortStr = lv_label_create(ui_ModbusPortPanel);
    lv_obj_set_width(ui_ModbusPortStr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ModbusPortStr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ModbusPortStr, -10);
    lv_obj_set_y(ui_ModbusPortStr, 0);
    lv_obj_set_align(ui_ModbusPortStr, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ModbusPortStr, "Modbus Port      :");
    lv_obj_remove_flag(ui_ModbusPortStr,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);    /// Flags
    lv_obj_set_style_text_font(ui_ModbusPortStr, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ModbusPortText = lv_textarea_create(ui_ModbusPortPanel);
    lv_obj_set_width(ui_ModbusPortText, 150);
    lv_obj_set_height(ui_ModbusPortText, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_x(ui_ModbusPortText, 20);
    lv_obj_set_y(ui_ModbusPortText, 0);
    lv_obj_set_align(ui_ModbusPortText, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_ModbusPortText, "0123456789");
    lv_textarea_set_max_length(ui_ModbusPortText, 5);
    lv_textarea_set_placeholder_text(ui_ModbusPortText, "Port");
    lv_textarea_set_one_line(ui_ModbusPortText, true);
    lv_obj_set_style_radius(ui_ModbusPortText, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ModbusPortText, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard = lv_keyboard_create(ui_ChangeConfig);
    lv_obj_set_width(ui_Keyboard, 480);
    lv_obj_set_height(ui_Keyboard, 120);
    lv_obj_set_x(ui_Keyboard, 0);
    lv_obj_set_y(ui_Keyboard, 1);
    lv_obj_set_align(ui_Keyboard, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Keyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_Keyboard, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Keyboard, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Keyboard, 0, LV_PART_MAIN | LV_STATE_DISABLED);

    lv_obj_set_style_radius(ui_Keyboard, 30, LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_NumKeyboard = lv_keyboard_create(ui_ChangeConfig);
    lv_keyboard_set_mode(ui_NumKeyboard, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_NumKeyboard, 250);
    lv_obj_set_height(ui_NumKeyboard, 120);
    lv_obj_set_x(ui_NumKeyboard, 120);
    lv_obj_set_y(ui_NumKeyboard, 0);
    lv_obj_set_align(ui_NumKeyboard, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_NumKeyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_WifiEnSw, ui_event_WifiEnSw, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WifiAutoIPSw, ui_event_WifiAutoIPSw, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SSIDText, ui_event_SSIDText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PasswordText, ui_event_PasswordText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DommyDot, ui_event_DommyDot, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Octant1, ui_event_Octant1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Octant2, ui_event_Octant2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Octant3, ui_event_Octant3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Octant4, ui_event_Octant4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BacNetText, ui_event_BacNetText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ModbusPortText, ui_event_ModbusPortText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Keyboard, ui_event_Keyboard, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ChangeConfig, ui_event_ChangeConfig, LV_EVENT_ALL, NULL);
    uic_WifiEnSw = ui_WifiEnSw;
    uic_SSIDText = ui_SSIDText;
    uic_PasswordText = ui_PasswordText;
    uic_Octant1 = ui_Octant1;
    uic_BacNetText = ui_BacNetText;
    uic_ModbusPortText = ui_ModbusPortText;

}

void ui_ChangeConfig_screen_destroy(void)
{
    if(ui_ChangeConfig) lv_obj_del(ui_ChangeConfig);

    // NULL screen variables
    ui_ChangeConfig = NULL;
    ui_ChangeConfigTitle = NULL;
    ui_MainMenuLbl2 = NULL;
    ui_WifiContainer = NULL;
    ui_WifiEnPanel = NULL;
    ui_WifiEnableStr = NULL;
    uic_WifiEnSw = NULL;
    ui_WifiEnSw = NULL;
    ui_WifiPanelAutoIP = NULL;
    ui_WifiEnableStr1 = NULL;
    ui_WifiAutoIPSw = NULL;
    ui_WifiSsidPanel = NULL;
    ui_SSIDStr = NULL;
    uic_SSIDText = NULL;
    ui_SSIDText = NULL;
    ui_WifiPassPanel = NULL;
    ui_PasswordStr1 = NULL;
    uic_PasswordText = NULL;
    ui_PasswordText = NULL;
    ui_IpPanel = NULL;
    ui_DropdownNetdata = NULL;
    ui_DommyDot = NULL;
    uic_Octant1 = NULL;
    ui_Octant1 = NULL;
    ui_Octant2 = NULL;
    ui_Octant3 = NULL;
    ui_Octant4 = NULL;
    ui_BacNetPortPanel = NULL;
    ui_BacNetPortStr = NULL;
    uic_BacNetText = NULL;
    ui_BacNetText = NULL;
    ui_ModbusPortPanel = NULL;
    ui_ModbusPortStr = NULL;
    uic_ModbusPortText = NULL;
    ui_ModbusPortText = NULL;
    ui_Keyboard = NULL;
    ui_NumKeyboard = NULL;

}
