// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: TemcoProject

#include "ui.h"
#include "lv_UserPeram.h"

void ui_event_TempSetPoint(lv_event_t * e)
{
	Event_Cb_SetSetpointValue(e);
}

void WifiEnEvent(lv_event_t * e)
{
	Event_Cb_WifiEn(e);
}

void IpAutoSelectFun(lv_event_t * e)
{
	Event_Cb_WifiIpAutoSelect(e);
}

void KeyPressFunc(lv_event_t * e)
{
	Event_Cb_KeyPress(e);
}

void FanSetAutoMode(lv_event_t * e)
{
	Event_Cb_FanSetAutoMode(e);
}

void CirculateBtnClicked(lv_event_t * e)
{
	Event_Cb_CirculateBtnClicked(e);
}

void StartFanBtn(lv_event_t * e)
{
	Event_Cb_StartFanBtn(e);
}

void SysModeHeatFunc(lv_event_t * e)
{
	Event_Cb_SysModeHeatFunc(e);
}

void AutoModeBtnFunc(lv_event_t * e)
{
	Event_Cb_AutoModeBtnFunc(e);
}

void ModeOffBtnEventFunc(lv_event_t * e)
{
	Event_Cb_ModeOffBtnEventFunc(e);
}

void SysModeCoolFunc(lv_event_t * e)
{
	Event_Cb_SysModeCoolFunc(e);
}

void UpdateWifiConfig(lv_event_t * e)
{
	Event_Cb_UpdateWifiConfig(e);
}

void WifiKeyboardPressFunc(lv_event_t * e)
{
	Event_Cb_WifiKeyboardPressFunc(e);
}

void NetworkConfigKeyPressFunc(lv_event_t * e)
{
	Event_Cb_NetworkConfigKeyPressFunc(e);
}

void ScheduleTimeSelectedFunc(lv_event_t * e)
{
	Event_Cb_ScheduleTimeSelectedFunc(e);
}

void ScheduleTimeUpdateCallback(lv_event_t * e)
{
	Event_Cb_ScheduleTimeUpdateCallback(e);
}

void ChangeTemperatureTypeCallBack(lv_event_t * e)
{
	Event_Cb_ChangeTemperatureTypeCallBack(e);
}

void ParamInputShowCallBackFunc(lv_event_t * e)
{
	Event_Cb_ParamInputShowCallBackFunc(e);
}

void ParamOutputShowCallBackFunc(lv_event_t * e)
{
	Event_Cb_ParamOutputShowCallBackFunc(e);
}

void ParamVariableShowCallBackFunc(lv_event_t * e)
{
	Event_Cb_ParamVariableShowCallBackFunc(e);
}

void SSIDShowEventFunc(lv_event_t * e)
{
	Event_Cb_SSIDShowEventFunc(e);
}

void ip_auto_next(lv_event_t * e)
{
	Event_Cb_IpAutoNext(e);
}

void UpdateParameterTableFunc(lv_event_t * e)
{
	Event_Cb_UpdateParameterTableFunc(e);
}

void SysTimeUpdateCallback(lv_event_t * e)
{
	Event_Cb_SysTimeUpdateCallback(e);
}

void CalenderValueChangeCallback(lv_event_t * e)
{
	Event_Cb_CalenderValueChangeCallback(e);
}

void NetworkConfigUpdateFunc(lv_event_t * e)
{
	Event_Cb_NetworkConfigUpdateFunc(e);
}

void UpdateProtocolFunc(lv_event_t * e)
{
	Event_Cb_UpdateProtocolFunc(e);
}

void RefreshTimeFunc(lv_event_t * e)
{
	Event_Cb_RefreshTimeFunc(e);
}

void TimeSyncLocalPcFunc(lv_event_t * e)
{
	Event_Cb_TimeSyncLocalPcFunc(e);
}

void TimeSyncUpdateFunc(lv_event_t * e)
{
	Event_Cb_TimeSyncUpdateFunc(e);
}

void TimeSyncServerUpdateFunc(lv_event_t * e)
{
	Event_Cb_TimeSyncServerUpdateFunc(e);
}

void ParameterUpdateFunc(lv_event_t * e)
{
	Event_Cb_ParameterUpdateFunc(e);
}

void ScheduleAutoManualValChangeFun(lv_event_t * e)
{
	Event_Cb_ScheduleAutoManualValChangeFun(e);
}

void ScheduleSwithValueChangeFunc(lv_event_t * e)
{
	Event_Cb_ScheduleSwithValueChangeFunc(e);
}

void ScheduleSetupUpdateBtnFunc(lv_event_t * e)
{
	Event_Cb_ScheduleSetupUpdateBtnFunc(e);
}

void ScheduleKeyboardPressFunc(lv_event_t * e)
{
	Event_Cb_ScheduleKeyboardPressFunc(e);
}

void SchSaveBtnFunc(lv_event_t * e)
{
	Event_Cb_SchSaveBtnFunc(e);
}

void SchClearAllFunc(lv_event_t * e)
{
	Event_Cb_SchClearAllFunc(e);
}

void SchCopyAllFunc(lv_event_t * e)
{
	Event_Cb_SchCopyAllFunc(e);
}

// End of file..
