// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: TemcoProject

#include "ui.h"

void ui_event_TempSetPoint(lv_event_t * e)
{
	// Your code here
}

void WifiEnEvent(lv_event_t * e)
{
	// Your code here
}

void IpAutoSelectFun(lv_event_t * e)
{
	// Your code here
}

void KeyPressFunc(lv_event_t * e)
{
	// Your code here
}
