// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: TemcoProject

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_event_TempSetPoint(lv_event_t * e);
void WifiEnEvent(lv_event_t * e);
void IpAutoSelectFun(lv_event_t * e);
void KeyPressFunc(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
