// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: TemcoProject

#ifndef UI_HOMESCREEN_H
#define UI_HOMESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HomeScreen
extern void ui_HomeScreen_screen_init(void);
extern void ui_HomeScreen_screen_destroy(void);
extern void ui_event_HomeScreen(lv_event_t * e);
extern lv_obj_t * ui_HomeScreen;
extern lv_obj_t * ui_RunTime;
extern lv_obj_t * ui_TemperatureContainer;
extern void ui_event_TempSetPoint1(lv_event_t * e);
extern lv_obj_t * ui_TempSetPoint1;
extern lv_obj_t * ui_TempSetPoint2;
extern lv_obj_t * ui_TemperatureVal;
extern lv_obj_t * ui_TempratureSymbol;
extern lv_obj_t * ui_SPLable;
extern lv_obj_t * ui_TemperatureSetPoint;
extern lv_obj_t * ui_WifiSymb;
extern lv_obj_t * ui_HumidityContainer;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_TextArea4;
extern void ui_event_RightBtn(lv_event_t * e);
extern lv_obj_t * ui_RightBtn;
extern lv_obj_t * ui_HomeDot;
extern lv_obj_t * ui_FanModePanel;
extern void ui_event_AutoBtn(lv_event_t * e);
extern lv_obj_t * ui_AutoBtn;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label16;
extern void ui_event_FanONBtn(lv_event_t * e);
extern lv_obj_t * ui_FanONBtn;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Image3;
extern void ui_event_CurculateBtn(lv_event_t * e);
extern lv_obj_t * ui_CurculateBtn;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label25;
extern void ui_event_FanButton(lv_event_t * e);
extern lv_obj_t * ui_FanButton;
extern lv_obj_t * ui_FanOnTimePanel;
extern lv_obj_t * ui_Roller1;
extern void ui_event_StartFanBtn(lv_event_t * e);
extern lv_obj_t * ui_StartFanBtn;
extern lv_obj_t * ui_Label29;
extern void ui_event_ModeBtn(lv_event_t * e);
extern lv_obj_t * ui_ModeBtn;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_SysModePanel;
extern void ui_event_HeatModeBtn(lv_event_t * e);
extern lv_obj_t * ui_HeatModeBtn;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Label28;
extern void ui_event_AutoModeBtn(lv_event_t * e);
extern lv_obj_t * ui_AutoModeBtn;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Label33;
extern void ui_event_OffModeBtn(lv_event_t * e);
extern lv_obj_t * ui_OffModeBtn;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Image5;
extern void ui_event_CoolModeBtn(lv_event_t * e);
extern lv_obj_t * ui_CoolModeBtn;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_Image8;
// CUSTOM VARIABLES
extern lv_obj_t * uic_RunTime;
extern lv_obj_t * uic_TemperatureVal;
extern lv_obj_t * uic_TempratureSymbol;
extern lv_obj_t * uic_TemperatureSetPoint;
extern lv_obj_t * uic_WifiSymb;
extern lv_obj_t * uic_RightBtn;
extern lv_obj_t * uic_AutoBtn;
extern lv_obj_t * uic_FanONBtn;
extern lv_obj_t * uic_CurculateBtn;
extern lv_obj_t * uic_FanOnTimePanel;
extern lv_obj_t * uic_StartFanBtn;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

