// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: TemcoProject

#include "ui.h"

lv_obj_t * uic_MenuBtn;
lv_obj_t * uic_WifiSymb;
lv_obj_t * uic_TemperatureSetPoint;
lv_obj_t * uic_TempratureSymbol;
lv_obj_t * uic_TemperatureVal;
lv_obj_t * uic_RunTime;
lv_obj_t * ui_HomeScreen = NULL;
lv_obj_t * ui_RunTime = NULL;
lv_obj_t * ui_TemperatureContainer = NULL;
lv_obj_t * ui_TempSetPoint1 = NULL;
lv_obj_t * ui_TempSetPoint2 = NULL;
lv_obj_t * ui_TemperatureVal = NULL;
lv_obj_t * ui_TempratureSymbol = NULL;
lv_obj_t * ui_SPLable = NULL;
lv_obj_t * ui_TemperatureSetPoint = NULL;
lv_obj_t * ui_WifiSymb = NULL;
lv_obj_t * ui_HumidityContainer = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_TextArea4 = NULL;
lv_obj_t * ui_ImgButton1 = NULL;
// event funtions
void ui_event_HomeScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        ShowItem_Animation(ui_WifiSymb, 2000);
        ShowItem_Animation(ui_TemperatureContainer, 200);
        ShowItem_Animation(ui_HumidityContainer, 1000);
        ShowItem_Animation(ui_RunTime, 3000);
        _ui_state_modify(ui_TemperatureContainer, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
}

void ui_event_TempSetPoint1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_event_TempSetPoint(e);
    }
}

void ui_event_ImgButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainMenu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 100, &ui_MainMenu_screen_init);
        _ui_opacity_set(ui_RunTime, 0);
        _ui_opacity_set(ui_TemperatureContainer, 0);
        _ui_opacity_set(ui_HumidityContainer, 0);
        _ui_opacity_set(ui_WifiSymb, 0);
    }
}

// build funtions

void ui_HomeScreen_screen_init(void)
{
    ui_HomeScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_HomeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomeScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunTime = lv_textarea_create(ui_HomeScreen);
    lv_obj_set_width(ui_RunTime, 100);
    lv_obj_set_height(ui_RunTime, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_RunTime, -190);
    lv_obj_set_y(ui_RunTime, -135);
    lv_obj_set_align(ui_RunTime, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_RunTime, "01234567890: AMP Time");
    lv_textarea_set_max_length(ui_RunTime, 10);
    lv_textarea_set_text(ui_RunTime, "10:20:35");
    lv_textarea_set_placeholder_text(ui_RunTime, "Time");
    lv_textarea_set_one_line(ui_RunTime, true);
    lv_obj_remove_flag(ui_RunTime, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_RunTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunTime, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RunTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RunTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_RunTime, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_RunTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_RunTime, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RunTime, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_TemperatureContainer = lv_obj_create(ui_HomeScreen);
    lv_obj_remove_style_all(ui_TemperatureContainer);
    lv_obj_set_width(ui_TemperatureContainer, 220);
    lv_obj_set_height(ui_TemperatureContainer, 220);
    lv_obj_set_align(ui_TemperatureContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TemperatureContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_TemperatureContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempSetPoint1 = lv_arc_create(ui_TemperatureContainer);
    lv_obj_set_width(ui_TempSetPoint1, 220);
    lv_obj_set_height(ui_TempSetPoint1, 220);
    lv_obj_set_align(ui_TempSetPoint1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TempSetPoint1,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_range(ui_TempSetPoint1, 0, 50);
    lv_arc_set_value(ui_TempSetPoint1, 20);
    lv_arc_set_bg_angles(ui_TempSetPoint1, 0, 360);
    lv_arc_set_rotation(ui_TempSetPoint1, 90);
    lv_obj_set_style_arc_color(ui_TempSetPoint1, lv_color_hex(0x265655), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_TempSetPoint1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_TempSetPoint1, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_TempSetPoint1, lv_color_hex(0x3A9993), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_TempSetPoint1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_TempSetPoint1, 7, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_TempSetPoint1, lv_color_hex(0xC6DFD9), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempSetPoint1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TempSetPoint1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TempSetPoint1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TempSetPoint1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TempSetPoint1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TempSetPoint2 = lv_arc_create(ui_TempSetPoint1);
    lv_obj_set_width(ui_TempSetPoint2, 200);
    lv_obj_set_height(ui_TempSetPoint2, 200);
    lv_obj_set_align(ui_TempSetPoint2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TempSetPoint2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_arc_set_range(ui_TempSetPoint2, 0, 50);
    lv_arc_set_value(ui_TempSetPoint2, 20);
    lv_arc_set_bg_angles(ui_TempSetPoint2, 0, 360);
    lv_arc_set_rotation(ui_TempSetPoint2, 90);
    lv_obj_set_style_arc_color(ui_TempSetPoint2, lv_color_hex(0x205552), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_TempSetPoint2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_TempSetPoint2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_TempSetPoint2, lv_color_hex(0x399994), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_TempSetPoint2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_TempSetPoint2, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_TempSetPoint2, lv_color_hex(0xC5DEDE), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempSetPoint2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TempSetPoint2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TempSetPoint2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TempSetPoint2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TempSetPoint2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TemperatureVal = lv_textarea_create(ui_TemperatureContainer);
    lv_obj_set_width(ui_TemperatureVal, 241);
    lv_obj_set_height(ui_TemperatureVal, LV_SIZE_CONTENT);    /// 123
    lv_obj_set_x(ui_TemperatureVal, 11);
    lv_obj_set_y(ui_TemperatureVal, -10);
    lv_obj_set_align(ui_TemperatureVal, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_TemperatureVal, "0123456789.");
    lv_textarea_set_max_length(ui_TemperatureVal, 4);
    lv_textarea_set_placeholder_text(ui_TemperatureVal, "88.8");
    lv_textarea_set_one_line(ui_TemperatureVal, true);
    lv_obj_remove_flag(ui_TemperatureVal,
                       LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_TemperatureVal, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_TemperatureVal, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TemperatureVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TemperatureVal, &ui_font_Arial80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TemperatureVal, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TemperatureVal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_TemperatureVal, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempratureSymbol = lv_textarea_create(ui_TemperatureVal);
    lv_obj_set_width(ui_TempratureSymbol, 50);
    lv_obj_set_height(ui_TempratureSymbol, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_TempratureSymbol, -22);
    lv_obj_set_y(ui_TempratureSymbol, -9);
    lv_obj_set_align(ui_TempratureSymbol, LV_ALIGN_TOP_RIGHT);
    lv_textarea_set_accepted_chars(ui_TempratureSymbol, "°CF");
    lv_textarea_set_max_length(ui_TempratureSymbol, 2);
    lv_textarea_set_placeholder_text(ui_TempratureSymbol, "°C");
    lv_textarea_set_one_line(ui_TempratureSymbol, true);
    lv_obj_remove_flag(ui_TempratureSymbol, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_text_color(ui_TempratureSymbol, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempratureSymbol, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempratureSymbol, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TempratureSymbol, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempratureSymbol, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_TempratureSymbol, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TempratureSymbol, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TempratureSymbol, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TempratureSymbol, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TempratureSymbol, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SPLable = lv_label_create(ui_TemperatureContainer);
    lv_obj_set_width(ui_SPLable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SPLable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SPLable, -30);
    lv_obj_set_y(ui_SPLable, 60);
    lv_obj_set_align(ui_SPLable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SPLable, "Target : ");

    ui_TemperatureSetPoint = lv_textarea_create(ui_TemperatureContainer);
    lv_obj_set_width(ui_TemperatureSetPoint, 150);
    lv_obj_set_height(ui_TemperatureSetPoint, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TemperatureSetPoint, 64);
    lv_obj_set_y(ui_TemperatureSetPoint, 60);
    lv_obj_set_align(ui_TemperatureSetPoint, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_TemperatureSetPoint, "012345678.°CF ");
    lv_textarea_set_max_length(ui_TemperatureSetPoint, 8);
    lv_textarea_set_placeholder_text(ui_TemperatureSetPoint, "SetPoint");
    lv_textarea_set_one_line(ui_TemperatureSetPoint, true);
    lv_obj_remove_flag(ui_TemperatureSetPoint,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE);     /// Flags
    lv_obj_set_style_bg_color(ui_TemperatureSetPoint, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TemperatureSetPoint, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TemperatureSetPoint, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TemperatureSetPoint, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiSymb = lv_image_create(ui_HomeScreen);
    lv_image_set_src(ui_WifiSymb, &ui_img_wifisym_png);
    lv_obj_set_width(ui_WifiSymb, LV_SIZE_CONTENT);   /// 34
    lv_obj_set_height(ui_WifiSymb, LV_SIZE_CONTENT);    /// 29
    lv_obj_set_x(ui_WifiSymb, 210);
    lv_obj_set_y(ui_WifiSymb, -142);
    lv_obj_set_align(ui_WifiSymb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiSymb, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WifiSymb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_WifiSymb, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityContainer = lv_obj_create(ui_HomeScreen);
    lv_obj_remove_style_all(ui_HumidityContainer);
    lv_obj_set_width(ui_HumidityContainer, 100);
    lv_obj_set_height(ui_HumidityContainer, 99);
    lv_obj_set_x(ui_HumidityContainer, 189);
    lv_obj_set_y(ui_HumidityContainer, -60);
    lv_obj_set_align(ui_HumidityContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_HumidityContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_HumidityContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_HumidityContainer);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, -15);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "HUMIDITY");
    lv_obj_set_style_text_letter_space(ui_Label3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea4 = lv_textarea_create(ui_HumidityContainer);
    lv_obj_set_width(ui_TextArea4, 100);
    lv_obj_set_height(ui_TextArea4, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_TextArea4, 0);
    lv_obj_set_y(ui_TextArea4, 15);
    lv_obj_set_align(ui_TextArea4, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_TextArea4, "0123456789%");
    lv_textarea_set_max_length(ui_TextArea4, 3);
    lv_textarea_set_text(ui_TextArea4, "50%");
    lv_textarea_set_placeholder_text(ui_TextArea4, "50%");
    lv_textarea_set_one_line(ui_TextArea4, true);
    lv_obj_remove_flag(ui_TextArea4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_TextArea4, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextArea4, lv_color_hex(0x205552), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextArea4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TextArea4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_TextArea4, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton1 = lv_imagebutton_create(ui_HomeScreen);
    lv_imagebutton_set_src(ui_ImgButton1, LV_IMAGEBUTTON_STATE_RELEASED, NULL,
                           &ui_img_round_manage_accounts_black_36pt_1x_png, NULL);
    lv_imagebutton_set_src(ui_ImgButton1, LV_IMAGEBUTTON_STATE_PRESSED, NULL,
                           &ui_img_round_manage_accounts_black_36pt_1x_png, NULL);
    lv_obj_set_width(ui_ImgButton1, 35);
    lv_obj_set_height(ui_ImgButton1, 40);
    lv_obj_set_x(ui_ImgButton1, 214);
    lv_obj_set_y(ui_ImgButton1, 135);
    lv_obj_set_align(ui_ImgButton1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_ImgButton1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ImgButton1, lv_color_hex(0x205552), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ImgButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_TempSetPoint1, ui_event_TempSetPoint1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton1, ui_event_ImgButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HomeScreen, ui_event_HomeScreen, LV_EVENT_ALL, NULL);
    uic_RunTime = ui_RunTime;
    uic_TemperatureVal = ui_TemperatureVal;
    uic_TempratureSymbol = ui_TempratureSymbol;
    uic_TemperatureSetPoint = ui_TemperatureSetPoint;
    uic_WifiSymb = ui_WifiSymb;
    uic_MenuBtn = ui_ImgButton1;

}

void ui_HomeScreen_screen_destroy(void)
{
    if(ui_HomeScreen) lv_obj_del(ui_HomeScreen);

    // NULL screen variables
    ui_HomeScreen = NULL;
    uic_RunTime = NULL;
    ui_RunTime = NULL;
    ui_TemperatureContainer = NULL;
    ui_TempSetPoint1 = NULL;
    ui_TempSetPoint2 = NULL;
    uic_TemperatureVal = NULL;
    ui_TemperatureVal = NULL;
    uic_TempratureSymbol = NULL;
    ui_TempratureSymbol = NULL;
    ui_SPLable = NULL;
    uic_TemperatureSetPoint = NULL;
    ui_TemperatureSetPoint = NULL;
    uic_WifiSymb = NULL;
    ui_WifiSymb = NULL;
    ui_HumidityContainer = NULL;
    ui_Label3 = NULL;
    ui_TextArea4 = NULL;
    uic_MenuBtn = NULL;
    ui_ImgButton1 = NULL;

}
