// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: TemcoProject

#ifndef UI_HOLIDAYCALENDERSCREEN_H
#define UI_HOLIDAYCALENDERSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HolidayCalenderScreen
extern void ui_HolidayCalenderScreen_screen_init(void);
extern void ui_HolidayCalenderScreen_screen_destroy(void);
extern lv_obj_t * ui_HolidayCalenderScreen;
extern lv_obj_t * ui_ChangeConfigTitle9;
extern lv_obj_t * ui_CalanderStr;
extern void ui_event_GotoMenuButton4(lv_event_t * e);
extern lv_obj_t * ui_GotoMenuButton4;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Calendar1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

