// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: TemcoProject

#ifndef UI_HOMESCREEN_H
#define UI_HOMESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HomeScreen
extern void ui_HomeScreen_screen_init(void);
extern void ui_HomeScreen_screen_destroy(void);
extern void ui_event_HomeScreen(lv_event_t * e);
extern lv_obj_t * ui_HomeScreen;
extern lv_obj_t * ui_RunTime;
extern lv_obj_t * ui_TemperatureContainer;
extern void ui_event_TempSetPoint1(lv_event_t * e);
extern lv_obj_t * ui_TempSetPoint1;
extern lv_obj_t * ui_TempSetPoint2;
extern lv_obj_t * ui_TemperatureVal;
extern lv_obj_t * ui_TempratureSymbol;
extern lv_obj_t * ui_SPLable;
extern lv_obj_t * ui_TemperatureSetPoint;
extern lv_obj_t * ui_WifiSymb;
extern lv_obj_t * ui_HumidityContainer;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_TextArea4;
extern void ui_event_ImgButton1(lv_event_t * e);
extern lv_obj_t * ui_ImgButton1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_RunTime;
extern lv_obj_t * uic_TemperatureVal;
extern lv_obj_t * uic_TempratureSymbol;
extern lv_obj_t * uic_TemperatureSetPoint;
extern lv_obj_t * uic_WifiSymb;
extern lv_obj_t * uic_MenuBtn;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

