// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: TemcoProject

#include "ui.h"

lv_obj_t * ui_HolidayCalenderScreen = NULL;
lv_obj_t * ui_ChangeConfigTitle9 = NULL;
lv_obj_t * ui_CalanderStr = NULL;
lv_obj_t * ui_GotoMenuButton4 = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_Calendar1 = NULL;
// event funtions
void ui_event_GotoMenuButton4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainMenu, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 100, &ui_MainMenu_screen_init);
    }
}

// build funtions

void ui_HolidayCalenderScreen_screen_init(void)
{
    ui_HolidayCalenderScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_HolidayCalenderScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ChangeConfigTitle9 = lv_obj_create(ui_HolidayCalenderScreen);
    lv_obj_set_width(ui_ChangeConfigTitle9, 450);
    lv_obj_set_height(ui_ChangeConfigTitle9, 40);
    lv_obj_set_align(ui_ChangeConfigTitle9, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_ChangeConfigTitle9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ChangeConfigTitle9, lv_color_hex(0x2D70A0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChangeConfigTitle9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ChangeConfigTitle9, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalanderStr = lv_label_create(ui_ChangeConfigTitle9);
    lv_obj_set_width(ui_CalanderStr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CalanderStr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CalanderStr, -80);
    lv_obj_set_y(ui_CalanderStr, 0);
    lv_obj_set_align(ui_CalanderStr, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CalanderStr, "   Holiday Calender");
    lv_obj_set_style_text_font(ui_CalanderStr, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GotoMenuButton4 = lv_imagebutton_create(ui_ChangeConfigTitle9);
    lv_imagebutton_set_src(ui_GotoMenuButton4, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_backsmallarrow_png, NULL);
    lv_imagebutton_set_src(ui_GotoMenuButton4, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_backsmallarrow_png, NULL);
    lv_obj_set_width(ui_GotoMenuButton4, 35);
    lv_obj_set_height(ui_GotoMenuButton4, 35);
    lv_obj_set_align(ui_GotoMenuButton4, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_radius(ui_GotoMenuButton4, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GotoMenuButton4, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GotoMenuButton4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_HolidayCalenderScreen);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 480);
    lv_obj_set_height(ui_Container4, 280);
    lv_obj_set_x(ui_Container4, 0);
    lv_obj_set_y(ui_Container4, 20);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Calendar1 = lv_calendar_create(ui_Container4);
    lv_calendar_set_today_date(ui_Calendar1, 2026, 2, 10);
    lv_calendar_set_showed_date(ui_Calendar1, 2026, 2);
    lv_obj_t * ui_Calendar1_header = lv_calendar_header_arrow_create(ui_Calendar1);
    lv_obj_set_width(ui_Calendar1, 400);
    lv_obj_set_height(ui_Calendar1, 260);
    lv_obj_set_align(ui_Calendar1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Calendar1, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_radius(ui_Calendar1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Calendar1, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Calendar1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Calendar1, lv_color_hex(0x7FC0F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Calendar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Calendar1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Calendar1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Calendar1, lv_color_hex(0x7FC0F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Calendar1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Calendar1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Calendar1, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Calendar1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Calendar1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Calendar1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_GotoMenuButton4, ui_event_GotoMenuButton4, LV_EVENT_ALL, NULL);

}

void ui_HolidayCalenderScreen_screen_destroy(void)
{
    if(ui_HolidayCalenderScreen) lv_obj_del(ui_HolidayCalenderScreen);

    // NULL screen variables
    ui_HolidayCalenderScreen = NULL;
    ui_ChangeConfigTitle9 = NULL;
    ui_CalanderStr = NULL;
    ui_GotoMenuButton4 = NULL;
    ui_Container4 = NULL;
    ui_Calendar1 = NULL;

}
