// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: TemcoProject

#include "ui.h"

lv_obj_t * uic_StartFanBtn;
lv_obj_t * uic_FanOnTimePanel;
lv_obj_t * uic_CurculateBtn;
lv_obj_t * uic_FanONBtn;
lv_obj_t * uic_AutoBtn;
lv_obj_t * uic_RightBtn;
lv_obj_t * uic_WifiSymb;
lv_obj_t * uic_TemperatureSetPoint;
lv_obj_t * uic_TempratureSymbol;
lv_obj_t * uic_TemperatureVal;
lv_obj_t * uic_RunTime;
lv_obj_t * ui_HomeScreen = NULL;
lv_obj_t * ui_RunTime = NULL;
lv_obj_t * ui_TemperatureContainer = NULL;
lv_obj_t * ui_TempSetPoint1 = NULL;
lv_obj_t * ui_TempSetPoint2 = NULL;
lv_obj_t * ui_TemperatureVal = NULL;
lv_obj_t * ui_TempratureSymbol = NULL;
lv_obj_t * ui_SPLable = NULL;
lv_obj_t * ui_TemperatureSetPoint = NULL;
lv_obj_t * ui_WifiSymb = NULL;
lv_obj_t * ui_HumidityContainer = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_TextArea4 = NULL;
lv_obj_t * ui_RightBtn = NULL;
lv_obj_t * ui_HomeDot = NULL;
lv_obj_t * ui_FanModePanel = NULL;
lv_obj_t * ui_AutoBtn = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_FanONBtn = NULL;
lv_obj_t * ui_Label26 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_CurculateBtn = NULL;
lv_obj_t * ui_Label27 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_FanButton = NULL;
lv_obj_t * ui_FanOnTimePanel = NULL;
lv_obj_t * ui_Roller1 = NULL;
lv_obj_t * ui_StartFanBtn = NULL;
lv_obj_t * ui_Label29 = NULL;
lv_obj_t * ui_ModeBtn = NULL;
lv_obj_t * ui_Label30 = NULL;
lv_obj_t * ui_SysModePanel = NULL;
lv_obj_t * ui_HeatModeBtn = NULL;
lv_obj_t * ui_Label35 = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_Label28 = NULL;
lv_obj_t * ui_AutoModeBtn = NULL;
lv_obj_t * ui_Label31 = NULL;
lv_obj_t * ui_Label33 = NULL;
lv_obj_t * ui_OffModeBtn = NULL;
lv_obj_t * ui_Label32 = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_CoolModeBtn = NULL;
lv_obj_t * ui_Label36 = NULL;
lv_obj_t * ui_Image8 = NULL;
// event funtions
void ui_event_HomeScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        ShowItem_Animation(ui_WifiSymb, 1000);
        ShowItem_Animation(ui_TemperatureContainer, 200);
        ShowItem_Animation(ui_HumidityContainer, 1000);
        ShowItem_Animation(ui_RunTime, 1000);
        LeftInItem_Animation(ui_RightBtn, 1000);
        RightIn_Animation(ui_FanButton, 1000);
        LeftInItem_Animation(ui_ModeBtn, 1000);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        _ui_opacity_set(ui_TemperatureContainer, 0);
        _ui_opacity_set(ui_RunTime, 0);
        _ui_opacity_set(ui_WifiSymb, 0);
        _ui_opacity_set(ui_HumidityContainer, 0);
        _ui_opacity_set(ui_RightBtn, 0);
        _ui_opacity_set(ui_FanButton, 0);
        _ui_opacity_set(ui_ModeBtn, 0);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_FanModePanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_FanOnTimePanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_SysModePanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        ChangeTemperatureTypeCallBack(e);
    }
}

void ui_event_TempSetPoint1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_event_TempSetPoint(e);
    }
}

void ui_event_RightBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainMenu, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 100, &ui_MainMenu_screen_init);
    }
}

void ui_event_AutoBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_FanOnTimePanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        FanSetAutoMode(e);
        _ui_flag_modify(ui_FanModePanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_FanONBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_FanOnTimePanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_CurculateBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_FanOnTimePanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        CirculateBtnClicked(e);
        _ui_flag_modify(ui_FanModePanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_FanButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_FanModePanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_SysModePanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_StartFanBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        StartFanBtn(e);
        _ui_flag_modify(ui_FanOnTimePanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_FanModePanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ModeBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_SysModePanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_FanModePanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_HeatModeBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SysModeHeatFunc(e);
        _ui_flag_modify(ui_SysModePanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_AutoModeBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_SysModePanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        AutoModeBtnFunc(e);
    }
}

void ui_event_OffModeBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ModeOffBtnEventFunc(e);
        _ui_flag_modify(ui_SysModePanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_CoolModeBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SysModeCoolFunc(e);
        _ui_flag_modify(ui_SysModePanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

void ui_HomeScreen_screen_init(void)
{
    ui_HomeScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_HomeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomeScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunTime = lv_textarea_create(ui_HomeScreen);
    lv_obj_set_width(ui_RunTime, 100);
    lv_obj_set_height(ui_RunTime, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_RunTime, -190);
    lv_obj_set_y(ui_RunTime, -135);
    lv_obj_set_align(ui_RunTime, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_RunTime, "01234567890: AMP Time");
    lv_textarea_set_max_length(ui_RunTime, 10);
    lv_textarea_set_text(ui_RunTime, "10:20 AM");
    lv_textarea_set_placeholder_text(ui_RunTime, "Time");
    lv_textarea_set_one_line(ui_RunTime, true);
    lv_obj_remove_flag(ui_RunTime, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_RunTime, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_RunTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunTime, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RunTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RunTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_RunTime, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_RunTime, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RunTime, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_TemperatureContainer = lv_obj_create(ui_HomeScreen);
    lv_obj_remove_style_all(ui_TemperatureContainer);
    lv_obj_set_width(ui_TemperatureContainer, 230);
    lv_obj_set_height(ui_TemperatureContainer, 230);
    lv_obj_set_align(ui_TemperatureContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TemperatureContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TempSetPoint1 = lv_arc_create(ui_TemperatureContainer);
    lv_obj_set_width(ui_TempSetPoint1, 230);
    lv_obj_set_height(ui_TempSetPoint1, 230);
    lv_obj_set_align(ui_TempSetPoint1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TempSetPoint1,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_range(ui_TempSetPoint1, 0, 50);
    lv_arc_set_value(ui_TempSetPoint1, 20);
    lv_arc_set_bg_angles(ui_TempSetPoint1, 0, 360);
    lv_arc_set_rotation(ui_TempSetPoint1, 90);
    lv_obj_set_style_arc_color(ui_TempSetPoint1, lv_color_hex(0x62B7FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_TempSetPoint1, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_TempSetPoint1, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_TempSetPoint1, lv_color_hex(0x62B7FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_TempSetPoint1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_TempSetPoint1, 7, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_TempSetPoint1, lv_color_hex(0xC6DFD9), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempSetPoint1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TempSetPoint1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TempSetPoint1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TempSetPoint1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TempSetPoint1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TempSetPoint2 = lv_arc_create(ui_TempSetPoint1);
    lv_obj_set_width(ui_TempSetPoint2, 210);
    lv_obj_set_height(ui_TempSetPoint2, 210);
    lv_obj_set_align(ui_TempSetPoint2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TempSetPoint2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_arc_set_range(ui_TempSetPoint2, 0, 50);
    lv_arc_set_value(ui_TempSetPoint2, 20);
    lv_arc_set_bg_angles(ui_TempSetPoint2, 0, 360);
    lv_arc_set_rotation(ui_TempSetPoint2, 90);
    lv_obj_set_style_arc_color(ui_TempSetPoint2, lv_color_hex(0x62B7FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_TempSetPoint2, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_TempSetPoint2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_TempSetPoint2, lv_color_hex(0x62B7FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_TempSetPoint2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_TempSetPoint2, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_TempSetPoint2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TempSetPoint2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TempSetPoint2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TempSetPoint2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TemperatureVal = lv_textarea_create(ui_TemperatureContainer);
    lv_obj_set_width(ui_TemperatureVal, 241);
    lv_obj_set_height(ui_TemperatureVal, LV_SIZE_CONTENT);    /// 123
    lv_obj_set_x(ui_TemperatureVal, 11);
    lv_obj_set_y(ui_TemperatureVal, -10);
    lv_obj_set_align(ui_TemperatureVal, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_TemperatureVal, "0123456789.");
    lv_textarea_set_max_length(ui_TemperatureVal, 4);
    lv_textarea_set_placeholder_text(ui_TemperatureVal, "88.8");
    lv_textarea_set_one_line(ui_TemperatureVal, true);
    lv_obj_remove_flag(ui_TemperatureVal,
                       LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_TemperatureVal, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_TemperatureVal, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TemperatureVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TemperatureVal, &ui_font_Arial80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TemperatureVal, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TemperatureVal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_TemperatureVal, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempratureSymbol = lv_textarea_create(ui_TemperatureVal);
    lv_obj_set_width(ui_TempratureSymbol, 50);
    lv_obj_set_height(ui_TempratureSymbol, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_TempratureSymbol, -22);
    lv_obj_set_y(ui_TempratureSymbol, -9);
    lv_obj_set_align(ui_TempratureSymbol, LV_ALIGN_TOP_RIGHT);
    lv_textarea_set_accepted_chars(ui_TempratureSymbol, "°CF");
    lv_textarea_set_max_length(ui_TempratureSymbol, 2);
    lv_textarea_set_placeholder_text(ui_TempratureSymbol, "°C");
    lv_textarea_set_one_line(ui_TempratureSymbol, true);
    lv_obj_remove_flag(ui_TempratureSymbol, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_text_color(ui_TempratureSymbol, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempratureSymbol, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempratureSymbol, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TempratureSymbol, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempratureSymbol, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_TempratureSymbol, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TempratureSymbol, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TempratureSymbol, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TempratureSymbol, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TempratureSymbol, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SPLable = lv_label_create(ui_TemperatureContainer);
    lv_obj_set_width(ui_SPLable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SPLable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SPLable, -30);
    lv_obj_set_y(ui_SPLable, 60);
    lv_obj_set_align(ui_SPLable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SPLable, "Target : ");

    ui_TemperatureSetPoint = lv_textarea_create(ui_TemperatureContainer);
    lv_obj_set_width(ui_TemperatureSetPoint, 150);
    lv_obj_set_height(ui_TemperatureSetPoint, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TemperatureSetPoint, 64);
    lv_obj_set_y(ui_TemperatureSetPoint, 60);
    lv_obj_set_align(ui_TemperatureSetPoint, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_TemperatureSetPoint, "012345678.°CF ");
    lv_textarea_set_max_length(ui_TemperatureSetPoint, 8);
    lv_textarea_set_placeholder_text(ui_TemperatureSetPoint, "SetPoint");
    lv_textarea_set_one_line(ui_TemperatureSetPoint, true);
    lv_obj_remove_flag(ui_TemperatureSetPoint,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE);     /// Flags
    lv_obj_set_style_bg_color(ui_TemperatureSetPoint, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TemperatureSetPoint, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TemperatureSetPoint, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TemperatureSetPoint, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiSymb = lv_image_create(ui_HomeScreen);
    lv_image_set_src(ui_WifiSymb, &ui_img_wifisym_png);
    lv_obj_set_width(ui_WifiSymb, LV_SIZE_CONTENT);   /// 34
    lv_obj_set_height(ui_WifiSymb, LV_SIZE_CONTENT);    /// 29
    lv_obj_set_x(ui_WifiSymb, 210);
    lv_obj_set_y(ui_WifiSymb, -142);
    lv_obj_set_align(ui_WifiSymb, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WifiSymb, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_WifiSymb, LV_SCROLLBAR_MODE_OFF);

    ui_HumidityContainer = lv_obj_create(ui_HomeScreen);
    lv_obj_remove_style_all(ui_HumidityContainer);
    lv_obj_set_width(ui_HumidityContainer, 100);
    lv_obj_set_height(ui_HumidityContainer, 70);
    lv_obj_set_x(ui_HumidityContainer, 160);
    lv_obj_set_y(ui_HumidityContainer, 110);
    lv_obj_set_align(ui_HumidityContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_HumidityContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_HumidityContainer, lv_color_hex(0x349EF9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HumidityContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HumidityContainer, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_HumidityContainer, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_HumidityContainer);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, -15);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "HUMIDITY");
    lv_obj_set_style_text_letter_space(ui_Label3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea4 = lv_textarea_create(ui_HumidityContainer);
    lv_obj_set_width(ui_TextArea4, 100);
    lv_obj_set_height(ui_TextArea4, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_TextArea4, 0);
    lv_obj_set_y(ui_TextArea4, 15);
    lv_obj_set_align(ui_TextArea4, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_TextArea4, "0123456789%");
    lv_textarea_set_max_length(ui_TextArea4, 3);
    lv_textarea_set_text(ui_TextArea4, "50%");
    lv_textarea_set_placeholder_text(ui_TextArea4, "50%");
    lv_textarea_set_one_line(ui_TextArea4, true);
    lv_obj_remove_flag(ui_TextArea4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_TextArea4, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_TextArea4, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RightBtn = lv_imagebutton_create(ui_HomeScreen);
    lv_imagebutton_set_src(ui_RightBtn, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_rightarrow_png, NULL);
    lv_imagebutton_set_src(ui_RightBtn, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_rightarrow_png, NULL);
    lv_obj_set_width(ui_RightBtn, 35);
    lv_obj_set_height(ui_RightBtn, 60);
    lv_obj_set_x(ui_RightBtn, 214);
    lv_obj_set_y(ui_RightBtn, 0);
    lv_obj_set_align(ui_RightBtn, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_RightBtn, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_RightBtn, LV_SCROLLBAR_MODE_OFF);

    ui_HomeDot = lv_image_create(ui_HomeScreen);
    lv_image_set_src(ui_HomeDot, &ui_img_displayhomescreendot_png);
    lv_obj_set_width(ui_HomeDot, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_HomeDot, LV_SIZE_CONTENT);    /// 21
    lv_obj_set_x(ui_HomeDot, 0);
    lv_obj_set_y(ui_HomeDot, -5);
    lv_obj_set_align(ui_HomeDot, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_HomeDot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_HomeDot, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FanModePanel = lv_obj_create(ui_HomeScreen);
    lv_obj_set_width(ui_FanModePanel, 190);
    lv_obj_set_height(ui_FanModePanel, 180);
    lv_obj_set_x(ui_FanModePanel, -8);
    lv_obj_set_y(ui_FanModePanel, -19);
    lv_obj_set_align(ui_FanModePanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FanModePanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_FanModePanel, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_FanModePanel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_FanModePanel, lv_color_hex(0x54AEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_FanModePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_FanModePanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_FanModePanel, lv_color_hex(0x5AB1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_FanModePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_FanModePanel, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_FanModePanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AutoBtn = lv_button_create(ui_FanModePanel);
    lv_obj_set_width(ui_AutoBtn, 170);
    lv_obj_set_height(ui_AutoBtn, 40);
    lv_obj_set_x(ui_AutoBtn, 0);
    lv_obj_set_y(ui_AutoBtn, 20);
    lv_obj_set_align(ui_AutoBtn, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_AutoBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_AutoBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AutoBtn, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AutoBtn, lv_color_hex(0x3B62C1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AutoBtn, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_AutoBtn, lv_color_hex(0x494758), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_AutoBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_AutoBtn, 130, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_AutoBtn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AutoBtn, lv_color_hex(0x456CD4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AutoBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_AutoBtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_AutoBtn, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_AutoBtn, 50, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_AutoBtn, lv_color_hex(0x3B62CA), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_AutoBtn, 120, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_color(ui_AutoBtn, lv_color_hex(0x494758), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_main_stop(ui_AutoBtn, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_stop(ui_AutoBtn, 130, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_dir(ui_AutoBtn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_color(ui_AutoBtn, lv_color_hex(0x3D67C1), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_AutoBtn, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_width(ui_AutoBtn, 20, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_spread(ui_AutoBtn, 5, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label22 = lv_label_create(ui_AutoBtn);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "Auto");
    lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_image_create(ui_AutoBtn);
    lv_image_set_src(ui_Image1, &ui_img_fan_auto_new_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 35
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_Image1, 0);
    lv_obj_set_y(ui_Image1, -1);
    lv_obj_set_align(ui_Image1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label16 = lv_label_create(ui_FanModePanel);
    lv_obj_set_height(ui_Label16, 25);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Label16, 0);
    lv_obj_set_y(ui_Label16, -17);
    lv_obj_set_align(ui_Label16, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label16, "            Fan Mode          ");
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label16, lv_color_hex(0x3E6AE3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label16, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Label16, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Label16, lv_color_hex(0x333E5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Label16, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Label16, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Label16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Label16, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label16, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FanONBtn = lv_button_create(ui_FanModePanel);
    lv_obj_set_width(ui_FanONBtn, 170);
    lv_obj_set_height(ui_FanONBtn, 40);
    lv_obj_set_x(ui_FanONBtn, 0);
    lv_obj_set_y(ui_FanONBtn, 15);
    lv_obj_set_align(ui_FanONBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FanONBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_FanONBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_FanONBtn, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_FanONBtn, lv_color_hex(0x3B62C1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FanONBtn, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_FanONBtn, lv_color_hex(0x494758), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_FanONBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_FanONBtn, 130, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_FanONBtn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_FanONBtn, lv_color_hex(0x456CD4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_FanONBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_FanONBtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_FanONBtn, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_FanONBtn, lv_color_hex(0x3B62C1), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_FanONBtn, 120, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_color(ui_FanONBtn, lv_color_hex(0x494758), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_main_stop(ui_FanONBtn, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_stop(ui_FanONBtn, 130, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_dir(ui_FanONBtn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_color(ui_FanONBtn, lv_color_hex(0x3D67C1), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_FanONBtn, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_width(ui_FanONBtn, 20, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_spread(ui_FanONBtn, 5, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label26 = lv_label_create(ui_FanONBtn);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "On");
    lv_obj_set_style_text_font(ui_Label26, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_image_create(ui_FanONBtn);
    lv_image_set_src(ui_Image3, &ui_img_fan_small_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 35
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_Image3, 0);
    lv_obj_set_y(ui_Image3, -1);
    lv_obj_set_align(ui_Image3, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CurculateBtn = lv_button_create(ui_FanModePanel);
    lv_obj_set_width(ui_CurculateBtn, 170);
    lv_obj_set_height(ui_CurculateBtn, 40);
    lv_obj_set_x(ui_CurculateBtn, 0);
    lv_obj_set_y(ui_CurculateBtn, 10);
    lv_obj_set_align(ui_CurculateBtn, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_CurculateBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_CurculateBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CurculateBtn, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CurculateBtn, lv_color_hex(0x3B62C1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CurculateBtn, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_CurculateBtn, lv_color_hex(0x494758), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_CurculateBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_CurculateBtn, 130, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_CurculateBtn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CurculateBtn, lv_color_hex(0x456CD4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CurculateBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_CurculateBtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_CurculateBtn, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_CurculateBtn, 50, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_CurculateBtn, lv_color_hex(0x3B62C1), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_CurculateBtn, 120, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_color(ui_CurculateBtn, lv_color_hex(0x494758), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_main_stop(ui_CurculateBtn, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_stop(ui_CurculateBtn, 130, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_dir(ui_CurculateBtn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_color(ui_CurculateBtn, lv_color_hex(0x3D67C1), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_CurculateBtn, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_width(ui_CurculateBtn, 20, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_spread(ui_CurculateBtn, 5, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label27 = lv_label_create(ui_CurculateBtn);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, 20);
    lv_obj_set_y(ui_Label27, -5);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "Circulate");
    lv_obj_set_style_text_font(ui_Label27, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_image_create(ui_CurculateBtn);
    lv_image_set_src(ui_Image4, &ui_img_fan_withtime_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 35
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_Image4, 0);
    lv_obj_set_y(ui_Image4, -1);
    lv_obj_set_align(ui_Image4, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label25 = lv_label_create(ui_CurculateBtn);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, 20);
    lv_obj_set_y(ui_Label25, 10);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "Runs 20 min/hr");
    lv_obj_set_style_text_font(ui_Label25, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FanButton = lv_imagebutton_create(ui_HomeScreen);
    lv_imagebutton_set_src(ui_FanButton, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_fan_small_png, NULL);
    lv_imagebutton_set_src(ui_FanButton, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_fan_small_png, NULL);
    lv_obj_set_width(ui_FanButton, 35);
    lv_obj_set_height(ui_FanButton, 35);
    lv_obj_set_x(ui_FanButton, -200);
    lv_obj_set_y(ui_FanButton, 130);
    lv_obj_set_align(ui_FanButton, LV_ALIGN_CENTER);

    ui_FanOnTimePanel = lv_obj_create(ui_HomeScreen);
    lv_obj_set_width(ui_FanOnTimePanel, 140);
    lv_obj_set_height(ui_FanOnTimePanel, 180);
    lv_obj_set_x(ui_FanOnTimePanel, 150);
    lv_obj_set_y(ui_FanOnTimePanel, -19);
    lv_obj_set_align(ui_FanOnTimePanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FanOnTimePanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_FanOnTimePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_FanOnTimePanel, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_FanOnTimePanel, lv_color_hex(0x3969E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_FanOnTimePanel, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_FanOnTimePanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_FanOnTimePanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roller1 = lv_roller_create(ui_FanOnTimePanel);
    lv_roller_set_options(ui_Roller1, "1 Hour\n2 Hours\n4 Hours\n8 Hours\nUntil I turn it off\n", LV_ROLLER_MODE_INFINITE);
    lv_roller_set_selected(ui_Roller1, 2, LV_ANIM_OFF);
    lv_obj_set_width(ui_Roller1, 130);
    lv_obj_set_height(ui_Roller1, 100);
    lv_obj_set_x(ui_Roller1, 1);
    lv_obj_set_y(ui_Roller1, -20);
    lv_obj_set_align(ui_Roller1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Roller1, LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLL_WITH_ARROW |
                    LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_set_style_text_letter_space(ui_Roller1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Roller1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Roller1, 10, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Roller1, lv_color_hex(0x403E4F), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Roller1, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Roller1, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Roller1, LV_GRAD_DIR_VER, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Roller1, lv_color_hex(0x208FEA), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Roller1, 120, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Roller1, 40, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Roller1, 1, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_StartFanBtn = lv_button_create(ui_FanOnTimePanel);
    lv_obj_set_width(ui_StartFanBtn, 120);
    lv_obj_set_height(ui_StartFanBtn, 30);
    lv_obj_set_x(ui_StartFanBtn, 0);
    lv_obj_set_y(ui_StartFanBtn, 10);
    lv_obj_set_align(ui_StartFanBtn, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_StartFanBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_StartFanBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StartFanBtn, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_StartFanBtn, lv_color_hex(0x3B62C1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StartFanBtn, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_StartFanBtn, lv_color_hex(0x494758), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_StartFanBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_StartFanBtn, 130, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_StartFanBtn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StartFanBtn, lv_color_hex(0x456CD4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StartFanBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StartFanBtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StartFanBtn, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_StartFanBtn, 50, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_StartFanBtn, lv_color_hex(0x3B62CA), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_StartFanBtn, 120, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_color(ui_StartFanBtn, lv_color_hex(0x494758), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_main_stop(ui_StartFanBtn, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_stop(ui_StartFanBtn, 130, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_dir(ui_StartFanBtn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_color(ui_StartFanBtn, lv_color_hex(0x3D67C1), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_StartFanBtn, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_width(ui_StartFanBtn, 20, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_spread(ui_StartFanBtn, 5, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label29 = lv_label_create(ui_StartFanBtn);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "Start");
    lv_obj_set_style_text_font(ui_Label29, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ModeBtn = lv_button_create(ui_HomeScreen);
    lv_obj_set_width(ui_ModeBtn, 80);
    lv_obj_set_height(ui_ModeBtn, 30);
    lv_obj_set_x(ui_ModeBtn, 5);
    lv_obj_set_y(ui_ModeBtn, 90);
    lv_obj_set_align(ui_ModeBtn, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ModeBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ModeBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ModeBtn, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ModeBtn, lv_color_hex(0x3B62C1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ModeBtn, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ModeBtn, lv_color_hex(0x100086), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_ModeBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ModeBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ModeBtn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ModeBtn, lv_color_hex(0x456CD4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ModeBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ModeBtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ModeBtn, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ModeBtn, 50, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_ModeBtn, lv_color_hex(0x3B62CA), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_ModeBtn, 120, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_color(ui_ModeBtn, lv_color_hex(0x494758), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_main_stop(ui_ModeBtn, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_stop(ui_ModeBtn, 130, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_dir(ui_ModeBtn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_color(ui_ModeBtn, lv_color_hex(0x3D67C1), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_ModeBtn, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_width(ui_ModeBtn, 20, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_spread(ui_ModeBtn, 5, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label30 = lv_label_create(ui_ModeBtn);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "Mode");
    lv_obj_set_style_text_font(ui_Label30, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SysModePanel = lv_obj_create(ui_HomeScreen);
    lv_obj_set_width(ui_SysModePanel, 240);
    lv_obj_set_height(ui_SysModePanel, 250);
    lv_obj_set_align(ui_SysModePanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SysModePanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_SysModePanel, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SysModePanel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SysModePanel, lv_color_hex(0x24435E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_SysModePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_SysModePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SysModePanel, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SysModePanel, lv_color_hex(0x62B7FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SysModePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SysModePanel, lv_color_hex(0x62B7FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SysModePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SysModePanel, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SysModePanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeatModeBtn = lv_button_create(ui_SysModePanel);
    lv_obj_set_width(ui_HeatModeBtn, 200);
    lv_obj_set_height(ui_HeatModeBtn, 40);
    lv_obj_set_x(ui_HeatModeBtn, 0);
    lv_obj_set_y(ui_HeatModeBtn, 25);
    lv_obj_set_align(ui_HeatModeBtn, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_HeatModeBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_HeatModeBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HeatModeBtn, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HeatModeBtn, lv_color_hex(0x3B62C1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HeatModeBtn, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_HeatModeBtn, lv_color_hex(0x494758), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_HeatModeBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_HeatModeBtn, 130, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_HeatModeBtn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HeatModeBtn, lv_color_hex(0x456CD4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HeatModeBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HeatModeBtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_HeatModeBtn, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_HeatModeBtn, 50, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_HeatModeBtn, lv_color_hex(0x3B62CA), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_HeatModeBtn, 120, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_color(ui_HeatModeBtn, lv_color_hex(0x494758), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_main_stop(ui_HeatModeBtn, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_stop(ui_HeatModeBtn, 130, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_dir(ui_HeatModeBtn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_color(ui_HeatModeBtn, lv_color_hex(0x3D67C1), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_HeatModeBtn, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_width(ui_HeatModeBtn, 20, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_spread(ui_HeatModeBtn, 5, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label35 = lv_label_create(ui_HeatModeBtn);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "Heat");
    lv_obj_set_style_text_font(ui_Label35, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image7 = lv_image_create(ui_HeatModeBtn);
    lv_image_set_src(ui_Image7, &ui_img_1679221590);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 35
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_align(ui_Image7, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label28 = lv_label_create(ui_SysModePanel);
    lv_obj_set_height(ui_Label28, 25);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Label28, 0);
    lv_obj_set_y(ui_Label28, -12);
    lv_obj_set_align(ui_Label28, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label28, "            System Mode           ");
    lv_obj_set_style_text_font(ui_Label28, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label28, lv_color_hex(0x3E6AE3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label28, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Label28, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label28, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label28, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label28, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label28, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AutoModeBtn = lv_button_create(ui_SysModePanel);
    lv_obj_set_width(ui_AutoModeBtn, 200);
    lv_obj_set_height(ui_AutoModeBtn, 40);
    lv_obj_set_x(ui_AutoModeBtn, 0);
    lv_obj_set_y(ui_AutoModeBtn, 40);
    lv_obj_set_align(ui_AutoModeBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AutoModeBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_AutoModeBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AutoModeBtn, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AutoModeBtn, lv_color_hex(0x3B62C1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AutoModeBtn, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_AutoModeBtn, lv_color_hex(0x494758), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_AutoModeBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_AutoModeBtn, 130, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_AutoModeBtn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AutoModeBtn, lv_color_hex(0x456CD4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AutoModeBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_AutoModeBtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_AutoModeBtn, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AutoModeBtn, lv_color_hex(0x3B62C1), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_AutoModeBtn, 120, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_color(ui_AutoModeBtn, lv_color_hex(0x494758), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_main_stop(ui_AutoModeBtn, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_stop(ui_AutoModeBtn, 130, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_dir(ui_AutoModeBtn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_color(ui_AutoModeBtn, lv_color_hex(0x3D67C1), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_AutoModeBtn, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_width(ui_AutoModeBtn, 20, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_spread(ui_AutoModeBtn, 5, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label31 = lv_label_create(ui_AutoModeBtn);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "Auto");
    lv_obj_set_style_text_font(ui_Label31, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label33 = lv_label_create(ui_AutoModeBtn);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label33, 2);
    lv_obj_set_y(ui_Label33, 0);
    lv_obj_set_align(ui_Label33, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label33, "A");
    lv_obj_set_style_text_font(ui_Label33, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OffModeBtn = lv_button_create(ui_SysModePanel);
    lv_obj_set_width(ui_OffModeBtn, 200);
    lv_obj_set_height(ui_OffModeBtn, 40);
    lv_obj_set_x(ui_OffModeBtn, 0);
    lv_obj_set_y(ui_OffModeBtn, 5);
    lv_obj_set_align(ui_OffModeBtn, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_OffModeBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_OffModeBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_OffModeBtn, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_OffModeBtn, lv_color_hex(0x3B62C1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OffModeBtn, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_OffModeBtn, lv_color_hex(0x494758), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_OffModeBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_OffModeBtn, 130, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_OffModeBtn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_OffModeBtn, lv_color_hex(0x456CD4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_OffModeBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_OffModeBtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_OffModeBtn, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_OffModeBtn, 50, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_OffModeBtn, lv_color_hex(0x3B62C1), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_OffModeBtn, 120, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_color(ui_OffModeBtn, lv_color_hex(0x494758), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_main_stop(ui_OffModeBtn, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_stop(ui_OffModeBtn, 130, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_dir(ui_OffModeBtn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_color(ui_OffModeBtn, lv_color_hex(0x3D67C1), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_OffModeBtn, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_width(ui_OffModeBtn, 20, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_spread(ui_OffModeBtn, 5, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label32 = lv_label_create(ui_OffModeBtn);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "OFF");
    lv_obj_set_style_text_font(ui_Label32, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_image_create(ui_OffModeBtn);
    lv_image_set_src(ui_Image5, &ui_img_1020677502);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 35
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_align(ui_Image5, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CoolModeBtn = lv_button_create(ui_SysModePanel);
    lv_obj_set_width(ui_CoolModeBtn, 200);
    lv_obj_set_height(ui_CoolModeBtn, 40);
    lv_obj_set_x(ui_CoolModeBtn, 0);
    lv_obj_set_y(ui_CoolModeBtn, 75);
    lv_obj_set_align(ui_CoolModeBtn, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_CoolModeBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_CoolModeBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CoolModeBtn, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CoolModeBtn, lv_color_hex(0x3B62C1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CoolModeBtn, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_CoolModeBtn, lv_color_hex(0x494758), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_CoolModeBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_CoolModeBtn, 130, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_CoolModeBtn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CoolModeBtn, lv_color_hex(0x456CD4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CoolModeBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_CoolModeBtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_CoolModeBtn, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_CoolModeBtn, 50, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_CoolModeBtn, lv_color_hex(0x3B62CA), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_CoolModeBtn, 120, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_color(ui_CoolModeBtn, lv_color_hex(0x494758), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_main_stop(ui_CoolModeBtn, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_stop(ui_CoolModeBtn, 130, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_grad_dir(ui_CoolModeBtn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_color(ui_CoolModeBtn, lv_color_hex(0x3D67C1), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_CoolModeBtn, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_width(ui_CoolModeBtn, 20, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_spread(ui_CoolModeBtn, 5, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label36 = lv_label_create(ui_CoolModeBtn);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label36, "Cool");
    lv_obj_set_style_text_font(ui_Label36, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image8 = lv_image_create(ui_CoolModeBtn);
    lv_image_set_src(ui_Image8, &ui_img_1869774352);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 35
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_align(ui_Image8, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_TempSetPoint1, ui_event_TempSetPoint1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RightBtn, ui_event_RightBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AutoBtn, ui_event_AutoBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_FanONBtn, ui_event_FanONBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CurculateBtn, ui_event_CurculateBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_FanButton, ui_event_FanButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_StartFanBtn, ui_event_StartFanBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ModeBtn, ui_event_ModeBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HeatModeBtn, ui_event_HeatModeBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AutoModeBtn, ui_event_AutoModeBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OffModeBtn, ui_event_OffModeBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CoolModeBtn, ui_event_CoolModeBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HomeScreen, ui_event_HomeScreen, LV_EVENT_ALL, NULL);
    uic_RunTime = ui_RunTime;
    uic_TemperatureVal = ui_TemperatureVal;
    uic_TempratureSymbol = ui_TempratureSymbol;
    uic_TemperatureSetPoint = ui_TemperatureSetPoint;
    uic_WifiSymb = ui_WifiSymb;
    uic_RightBtn = ui_RightBtn;
    uic_AutoBtn = ui_AutoBtn;
    uic_FanONBtn = ui_FanONBtn;
    uic_CurculateBtn = ui_CurculateBtn;
    uic_FanOnTimePanel = ui_FanOnTimePanel;
    uic_StartFanBtn = ui_StartFanBtn;

}

void ui_HomeScreen_screen_destroy(void)
{
    if(ui_HomeScreen) lv_obj_del(ui_HomeScreen);

    // NULL screen variables
    ui_HomeScreen = NULL;
    uic_RunTime = NULL;
    ui_RunTime = NULL;
    ui_TemperatureContainer = NULL;
    ui_TempSetPoint1 = NULL;
    ui_TempSetPoint2 = NULL;
    uic_TemperatureVal = NULL;
    ui_TemperatureVal = NULL;
    uic_TempratureSymbol = NULL;
    ui_TempratureSymbol = NULL;
    ui_SPLable = NULL;
    uic_TemperatureSetPoint = NULL;
    ui_TemperatureSetPoint = NULL;
    uic_WifiSymb = NULL;
    ui_WifiSymb = NULL;
    ui_HumidityContainer = NULL;
    ui_Label3 = NULL;
    ui_TextArea4 = NULL;
    uic_RightBtn = NULL;
    ui_RightBtn = NULL;
    ui_HomeDot = NULL;
    ui_FanModePanel = NULL;
    uic_AutoBtn = NULL;
    ui_AutoBtn = NULL;
    ui_Label22 = NULL;
    ui_Image1 = NULL;
    ui_Label16 = NULL;
    uic_FanONBtn = NULL;
    ui_FanONBtn = NULL;
    ui_Label26 = NULL;
    ui_Image3 = NULL;
    uic_CurculateBtn = NULL;
    ui_CurculateBtn = NULL;
    ui_Label27 = NULL;
    ui_Image4 = NULL;
    ui_Label25 = NULL;
    ui_FanButton = NULL;
    uic_FanOnTimePanel = NULL;
    ui_FanOnTimePanel = NULL;
    ui_Roller1 = NULL;
    uic_StartFanBtn = NULL;
    ui_StartFanBtn = NULL;
    ui_Label29 = NULL;
    ui_ModeBtn = NULL;
    ui_Label30 = NULL;
    ui_SysModePanel = NULL;
    ui_HeatModeBtn = NULL;
    ui_Label35 = NULL;
    ui_Image7 = NULL;
    ui_Label28 = NULL;
    ui_AutoModeBtn = NULL;
    ui_Label31 = NULL;
    ui_Label33 = NULL;
    ui_OffModeBtn = NULL;
    ui_Label32 = NULL;
    ui_Image5 = NULL;
    ui_CoolModeBtn = NULL;
    ui_Label36 = NULL;
    ui_Image8 = NULL;

}
