// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: TemcoProject

#ifndef UI_KEYPAD_H
#define UI_KEYPAD_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Keypad
extern void ui_Keypad_screen_init(void);
extern void ui_Keypad_screen_destroy(void);
extern lv_obj_t * ui_Keypad;
extern lv_obj_t * ui_TextArea3;
extern lv_obj_t * ui_Keyboard1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

