// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: TemcoProject

#ifndef UI_MAINMENU_H
#define UI_MAINMENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainMenu
extern void ui_MainMenu_screen_init(void);
extern void ui_MainMenu_screen_destroy(void);
extern void ui_event_MainMenu(lv_event_t * e);
extern lv_obj_t * ui_MainMenu;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_MainMenuLbl;
extern lv_obj_t * ui_ButtonContainer;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label8;
extern void ui_event_BackButton(lv_event_t * e);
extern lv_obj_t * ui_BackButton;
// CUSTOM VARIABLES
extern lv_obj_t * uic_BackButton;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

