// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: TemcoProject

#ifndef UI_MAINMENU_H
#define UI_MAINMENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainMenu
extern void ui_MainMenu_screen_init(void);
extern void ui_MainMenu_screen_destroy(void);
extern void ui_event_MainMenu(lv_event_t * e);
extern lv_obj_t * ui_MainMenu;
extern lv_obj_t * ui_ChangeConfigTitle4;
extern lv_obj_t * ui_NetworkSetupConfig6;
extern lv_obj_t * ui_ButtonContainer;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label4;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label5;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label6;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label7;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label8;
extern void ui_event_BackButton(lv_event_t * e);
extern lv_obj_t * ui_BackButton;
extern lv_obj_t * ui_MenuDot;
extern lv_obj_t * ui_Panel2;
extern void ui_event_ImgButton1(lv_event_t * e);
extern lv_obj_t * ui_ImgButton1;
extern lv_obj_t * ui_Label39;
extern void ui_event_ImgButton2(lv_event_t * e);
extern lv_obj_t * ui_ImgButton2;
extern lv_obj_t * ui_Label40;
extern void ui_event_ImgButton3(lv_event_t * e);
extern lv_obj_t * ui_ImgButton3;
extern lv_obj_t * ui_Label41;
extern void ui_event_CalenderBtn(lv_event_t * e);
extern lv_obj_t * ui_CalenderBtn;
// CUSTOM VARIABLES
extern lv_obj_t * uic_BackButton;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

