// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: TemcoProject

#include "ui.h"

lv_obj_t * uic_BackButton;
lv_obj_t * ui_MainMenu = NULL;
lv_obj_t * ui_ChangeConfigTitle4 = NULL;
lv_obj_t * ui_NetworkSetupConfig6 = NULL;
lv_obj_t * ui_ButtonContainer = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Button5 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_BackButton = NULL;
lv_obj_t * ui_MenuDot = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_ImgButton1 = NULL;
lv_obj_t * ui_Label39 = NULL;
lv_obj_t * ui_ImgButton2 = NULL;
lv_obj_t * ui_Label40 = NULL;
lv_obj_t * ui_ImgButton3 = NULL;
lv_obj_t * ui_Label41 = NULL;
lv_obj_t * ui_CalenderBtn = NULL;
// event funtions
void ui_event_MainMenu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        LeftInItem_Animation(ui_Button1, 0);
        RightIn_Animation(ui_Button2, 0);
        LeftInItem_Animation(ui_Button3, 200);
        RightIn_Animation(ui_Button4, 200);
        LeftInItem_Animation(ui_Button5, 400);
        LeftInItem_Animation(ui_BackButton, 600);
        RightIn_Animation(ui_Panel2, 600);
        LeftInItem_Animation(ui_CalenderBtn, 600);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        _ui_opacity_set(ui_Button1, 0);
        _ui_opacity_set(ui_Button2, 0);
        _ui_opacity_set(ui_Button3, 0);
        _ui_opacity_set(ui_Button4, 0);
        _ui_opacity_set(ui_Button5, 0);
        _ui_opacity_set(ui_BackButton, 0);
        _ui_opacity_set(ui_Panel2, 0);
        _ui_opacity_set(ui_CalenderBtn, 0);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WifiConfig, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 100, &ui_WifiConfig_screen_init);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_NetworkConfig, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_NetworkConfig_screen_init);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Protocols, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Protocols_screen_init);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScheduleScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ScheduleScreen_screen_init);
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Time, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Time_screen_init);
    }
}

void ui_event_BackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 100, &ui_HomeScreen_screen_init);
    }
}

void ui_event_ImgButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Parameters, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 200, &ui_Parameters_screen_init);
        ParamInputShowCallBackFunc(e);
    }
}

void ui_event_ImgButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Parameters, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 200, &ui_Parameters_screen_init);
        ParamOutputShowCallBackFunc(e);
    }
}

void ui_event_ImgButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Parameters, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 200, &ui_Parameters_screen_init);
        ParamVariableShowCallBackFunc(e);
    }
}

void ui_event_CalenderBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HolidayCalenderScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 200,
                          &ui_HolidayCalenderScreen_screen_init);
    }
}

// build funtions

void ui_MainMenu_screen_init(void)
{
    ui_MainMenu = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_MainMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_side(ui_MainMenu, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChangeConfigTitle4 = lv_obj_create(ui_MainMenu);
    lv_obj_set_width(ui_ChangeConfigTitle4, 450);
    lv_obj_set_height(ui_ChangeConfigTitle4, 40);
    lv_obj_set_align(ui_ChangeConfigTitle4, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_ChangeConfigTitle4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ChangeConfigTitle4, lv_color_hex(0x2D70A0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChangeConfigTitle4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ChangeConfigTitle4, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NetworkSetupConfig6 = lv_label_create(ui_ChangeConfigTitle4);
    lv_obj_set_width(ui_NetworkSetupConfig6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NetworkSetupConfig6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NetworkSetupConfig6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NetworkSetupConfig6, "Main Menu");
    lv_obj_set_style_text_font(ui_NetworkSetupConfig6, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonContainer = lv_obj_create(ui_MainMenu);
    lv_obj_remove_style_all(ui_ButtonContainer);
    lv_obj_set_width(ui_ButtonContainer, 479);
    lv_obj_set_height(ui_ButtonContainer, 275);
    lv_obj_set_x(ui_ButtonContainer, 0);
    lv_obj_set_y(ui_ButtonContainer, 15);
    lv_obj_set_align(ui_ButtonContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ButtonContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button1 = lv_button_create(ui_ButtonContainer);
    lv_obj_set_width(ui_Button1, 220);
    lv_obj_set_height(ui_Button1, 40);
    lv_obj_set_x(ui_Button1, 0);
    lv_obj_set_y(ui_Button1, -110);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x349EF9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Button1, lv_color_hex(0x81BAEA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Button1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label4, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_Label4, "WiFi");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x09007D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_button_create(ui_ButtonContainer);
    lv_obj_set_width(ui_Button2, 220);
    lv_obj_set_height(ui_Button2, 40);
    lv_obj_set_x(ui_Button2, 0);
    lv_obj_set_y(ui_Button2, -60);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x349EF9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Button2, lv_color_hex(0x81BAEA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Button2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label5, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_Label5, "Network");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x09007D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_button_create(ui_ButtonContainer);
    lv_obj_set_width(ui_Button3, 220);
    lv_obj_set_height(ui_Button3, 40);
    lv_obj_set_x(ui_Button3, 0);
    lv_obj_set_y(ui_Button3, -10);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button3, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x349EF9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Button3, lv_color_hex(0x81BAEA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Button3, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label6, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_Label6, "Protocols");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x09007D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label6, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_button_create(ui_ButtonContainer);
    lv_obj_set_width(ui_Button4, 220);
    lv_obj_set_height(ui_Button4, 40);
    lv_obj_set_x(ui_Button4, 0);
    lv_obj_set_y(ui_Button4, 40);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button4, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x349EF9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Button4, lv_color_hex(0x81BAEA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Button4, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label7, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_Label7, "Schedule");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x09007D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label7, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_button_create(ui_ButtonContainer);
    lv_obj_set_width(ui_Button5, 220);
    lv_obj_set_height(ui_Button5, 40);
    lv_obj_set_x(ui_Button5, 0);
    lv_obj_set_y(ui_Button5, 90);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button5, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0x349EF9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Button5, lv_color_hex(0x81BAEA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Button5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Button5, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label8, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_Label8, "Time");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0x09007D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label8, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackButton = lv_imagebutton_create(ui_ButtonContainer);
    lv_imagebutton_set_src(ui_BackButton, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_leftarrow_png, NULL);
    lv_imagebutton_set_src(ui_BackButton, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_leftarrow_png, NULL);
    lv_obj_set_width(ui_BackButton, 40);
    lv_obj_set_height(ui_BackButton, 60);
    lv_obj_set_x(ui_BackButton, -215);
    lv_obj_set_y(ui_BackButton, 0);
    lv_obj_set_align(ui_BackButton, LV_ALIGN_CENTER);
    lv_obj_set_style_border_side(ui_BackButton, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuDot = lv_image_create(ui_MainMenu);
    lv_image_set_src(ui_MenuDot, &ui_img_displayscreendotformenuscreen_gray_png);
    lv_obj_set_width(ui_MenuDot, LV_SIZE_CONTENT);   /// 26
    lv_obj_set_height(ui_MenuDot, LV_SIZE_CONTENT);    /// 19
    lv_obj_set_x(ui_MenuDot, 0);
    lv_obj_set_y(ui_MenuDot, -5);
    lv_obj_set_align(ui_MenuDot, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_MenuDot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_MenuDot, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_MainMenu);
    lv_obj_set_width(ui_Panel2, 80);
    lv_obj_set_height(ui_Panel2, 210);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x73B6EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel2, lv_color_hex(0x38A1F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Panel2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton1 = lv_imagebutton_create(ui_Panel2);
    lv_imagebutton_set_src(ui_ImgButton1, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_1984394067, NULL);
    lv_imagebutton_set_src(ui_ImgButton1, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_1984394067, NULL);
    lv_obj_set_width(ui_ImgButton1, 40);
    lv_obj_set_height(ui_ImgButton1, 40);
    lv_obj_set_x(ui_ImgButton1, 0);
    lv_obj_set_y(ui_ImgButton1, -75);
    lv_obj_set_align(ui_ImgButton1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_ImgButton1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ImgButton1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ImgButton1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label39 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label39, 0);
    lv_obj_set_y(ui_Label39, -48);
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "Inputs");
    lv_obj_set_style_text_color(ui_Label39, lv_color_hex(0x05074D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label39, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Label39, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton2 = lv_imagebutton_create(ui_Panel2);
    lv_imagebutton_set_src(ui_ImgButton2, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_444508050, NULL);
    lv_imagebutton_set_src(ui_ImgButton2, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_444508050, NULL);
    lv_obj_set_width(ui_ImgButton2, 40);
    lv_obj_set_height(ui_ImgButton2, 40);
    lv_obj_set_x(ui_ImgButton2, 0);
    lv_obj_set_y(ui_ImgButton2, -5);
    lv_obj_set_align(ui_ImgButton2, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_ImgButton2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ImgButton2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ImgButton2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label40 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label40, 0);
    lv_obj_set_y(ui_Label40, 22);
    lv_obj_set_align(ui_Label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label40, "Outputs");
    lv_obj_set_style_text_color(ui_Label40, lv_color_hex(0x05074D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label40, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Label40, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton3 = lv_imagebutton_create(ui_Panel2);
    lv_imagebutton_set_src(ui_ImgButton3, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_1589547977, NULL);
    lv_imagebutton_set_src(ui_ImgButton3, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_1589547977, NULL);
    lv_obj_set_width(ui_ImgButton3, 40);
    lv_obj_set_height(ui_ImgButton3, 40);
    lv_obj_set_x(ui_ImgButton3, 0);
    lv_obj_set_y(ui_ImgButton3, 65);
    lv_obj_set_align(ui_ImgButton3, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_ImgButton3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ImgButton3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ImgButton3, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label41 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label41, 0);
    lv_obj_set_y(ui_Label41, 92);
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "Variables");
    lv_obj_set_style_text_color(ui_Label41, lv_color_hex(0x05074D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Label41, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalenderBtn = lv_imagebutton_create(ui_MainMenu);
    lv_imagebutton_set_src(ui_CalenderBtn, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_1207302323, NULL);
    lv_imagebutton_set_src(ui_CalenderBtn, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_1207302323, NULL);
    lv_obj_set_width(ui_CalenderBtn, 40);
    lv_obj_set_height(ui_CalenderBtn, 40);
    lv_obj_set_x(ui_CalenderBtn, 20);
    lv_obj_set_y(ui_CalenderBtn, -40);
    lv_obj_set_align(ui_CalenderBtn, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_style_radius(ui_CalenderBtn, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BackButton, ui_event_BackButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton1, ui_event_ImgButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton2, ui_event_ImgButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton3, ui_event_ImgButton3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CalenderBtn, ui_event_CalenderBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainMenu, ui_event_MainMenu, LV_EVENT_ALL, NULL);
    uic_BackButton = ui_BackButton;

}

void ui_MainMenu_screen_destroy(void)
{
    if(ui_MainMenu) lv_obj_del(ui_MainMenu);

    // NULL screen variables
    ui_MainMenu = NULL;
    ui_ChangeConfigTitle4 = NULL;
    ui_NetworkSetupConfig6 = NULL;
    ui_ButtonContainer = NULL;
    ui_Button1 = NULL;
    ui_Label4 = NULL;
    ui_Button2 = NULL;
    ui_Label5 = NULL;
    ui_Button3 = NULL;
    ui_Label6 = NULL;
    ui_Button4 = NULL;
    ui_Label7 = NULL;
    ui_Button5 = NULL;
    ui_Label8 = NULL;
    uic_BackButton = NULL;
    ui_BackButton = NULL;
    ui_MenuDot = NULL;
    ui_Panel2 = NULL;
    ui_ImgButton1 = NULL;
    ui_Label39 = NULL;
    ui_ImgButton2 = NULL;
    ui_Label40 = NULL;
    ui_ImgButton3 = NULL;
    ui_Label41 = NULL;
    ui_CalenderBtn = NULL;

}
