// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: TemcoProject

#include "ui.h"

lv_obj_t * uic_BackButton;
lv_obj_t * ui_MainMenu = NULL;
lv_obj_t * ui_Panel8 = NULL;
lv_obj_t * ui_MainMenuLbl = NULL;
lv_obj_t * ui_ButtonContainer = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Button5 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_BackButton = NULL;
// event funtions
void ui_event_MainMenu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        LeftInItem_Animation(ui_Button1, 0);
        RightIn_Animation(ui_Button2, 0);
        LeftInItem_Animation(ui_Button3, 800);
        RightIn_Animation(ui_Button4, 800);
        LeftInItem_Animation(ui_Button5, 1500);
        LeftInItem_Animation(ui_BackButton, 1500);
        _ui_opacity_set(ui_ButtonContainer, 255);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ChangeConfig, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 100, &ui_ChangeConfig_screen_init);
    }
}

void ui_event_BackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 100, &ui_HomeScreen_screen_init);
        _ui_opacity_set(ui_Button1, 0);
        _ui_opacity_set(ui_Button2, 0);
        _ui_opacity_set(ui_Button3, 0);
        _ui_opacity_set(ui_Button4, 0);
        _ui_opacity_set(ui_Button5, 0);
        _ui_opacity_set(ui_BackButton, 0);
    }
}

// build funtions

void ui_MainMenu_screen_init(void)
{
    ui_MainMenu = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_MainMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_side(ui_MainMenu, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_MainMenu);
    lv_obj_set_width(ui_Panel8, 480);
    lv_obj_set_height(ui_Panel8, 30);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x2D70A0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainMenuLbl = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_MainMenuLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainMenuLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MainMenuLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MainMenuLbl, "Configurations");
    lv_obj_set_style_text_color(ui_MainMenuLbl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MainMenuLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonContainer = lv_obj_create(ui_MainMenu);
    lv_obj_remove_style_all(ui_ButtonContainer);
    lv_obj_set_width(ui_ButtonContainer, 479);
    lv_obj_set_height(ui_ButtonContainer, 280);
    lv_obj_set_x(ui_ButtonContainer, 0);
    lv_obj_set_y(ui_ButtonContainer, 15);
    lv_obj_set_align(ui_ButtonContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ButtonContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button1 = lv_button_create(ui_ButtonContainer);
    lv_obj_set_width(ui_Button1, 220);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, 0);
    lv_obj_set_y(ui_Button1, -110);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x399994), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Button1, lv_color_hex(0x02F9E7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Button1, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label4, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_Label4, "WiFi");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x09007D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_button_create(ui_ButtonContainer);
    lv_obj_set_width(ui_Button2, 220);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_x(ui_Button2, 0);
    lv_obj_set_y(ui_Button2, -55);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x399994), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Button2, lv_color_hex(0x02F9E7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Button2, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label5, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_Label5, "Network");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x09007D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_button_create(ui_ButtonContainer);
    lv_obj_set_width(ui_Button3, 220);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button3, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x399994), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Button3, lv_color_hex(0x02F9E7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Button3, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label6, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_Label6, "Protocol");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x09007D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label6, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_button_create(ui_ButtonContainer);
    lv_obj_set_width(ui_Button4, 220);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_x(ui_Button4, 0);
    lv_obj_set_y(ui_Button4, 55);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button4, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x399994), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Button4, lv_color_hex(0x02F9E7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Button4, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label7, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_Label7, "Time");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x09007D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label7, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_button_create(ui_ButtonContainer);
    lv_obj_set_width(ui_Button5, 220);
    lv_obj_set_height(ui_Button5, 50);
    lv_obj_set_x(ui_Button5, 0);
    lv_obj_set_y(ui_Button5, 110);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button5, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0x399994), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Button5, lv_color_hex(0x02F9E7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Button5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Button5, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Button5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label8, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_Label8, "Other");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0x09007D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label8, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackButton = lv_imagebutton_create(ui_MainMenu);
    lv_imagebutton_set_src(ui_BackButton, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_round_arrow_back_black_36_png, NULL);
    lv_imagebutton_set_src(ui_BackButton, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_round_arrow_back_black_36_png, NULL);
    lv_obj_set_width(ui_BackButton, 40);
    lv_obj_set_height(ui_BackButton, 35);
    lv_obj_set_x(ui_BackButton, -212);
    lv_obj_set_y(ui_BackButton, 135);
    lv_obj_set_align(ui_BackButton, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BackButton, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BackButton, lv_color_hex(0x399994), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BackButton, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_BackButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BackButton, ui_event_BackButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainMenu, ui_event_MainMenu, LV_EVENT_ALL, NULL);
    uic_BackButton = ui_BackButton;

}

void ui_MainMenu_screen_destroy(void)
{
    if(ui_MainMenu) lv_obj_del(ui_MainMenu);

    // NULL screen variables
    ui_MainMenu = NULL;
    ui_Panel8 = NULL;
    ui_MainMenuLbl = NULL;
    ui_ButtonContainer = NULL;
    ui_Button1 = NULL;
    ui_Label4 = NULL;
    ui_Button2 = NULL;
    ui_Label5 = NULL;
    ui_Button3 = NULL;
    ui_Label6 = NULL;
    ui_Button4 = NULL;
    ui_Label7 = NULL;
    ui_Button5 = NULL;
    ui_Label8 = NULL;
    uic_BackButton = NULL;
    ui_BackButton = NULL;

}
