// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: TemcoProject

#include "ui.h"

lv_obj_t * uic_NumKeyboard;
lv_obj_t * uic_NetworkConfig;
lv_obj_t * ui_NetworkConfig = NULL;
lv_obj_t * ui_ChangeConfigTitle1 = NULL;
lv_obj_t * ui_NetworkSetupConfig = NULL;
lv_obj_t * ui_GotoMenuButton2 = NULL;
lv_obj_t * ui_NetworkContainer1 = NULL;
lv_obj_t * ui_IpPanel1 = NULL;
lv_obj_t * ui_BacNetPortStr4 = NULL;
lv_obj_t * ui_Checkbox3 = NULL;
lv_obj_t * ui_Checkbox2 = NULL;
lv_obj_t * ui_WifiUpdateButton2 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_IpPanel2 = NULL;
lv_obj_t * ui_IpAddressStr = NULL;
lv_obj_t * ui_Label34 = NULL;
lv_obj_t * ui_IPoct1 = NULL;
lv_obj_t * ui_IPoct2 = NULL;
lv_obj_t * ui_IPoct3 = NULL;
lv_obj_t * ui_IPoct4 = NULL;
lv_obj_t * ui_SubnetPanel = NULL;
lv_obj_t * ui_SubNetStr = NULL;
lv_obj_t * ui_Label37 = NULL;
lv_obj_t * ui_IPoct6 = NULL;
lv_obj_t * ui_IPoct7 = NULL;
lv_obj_t * ui_IPoct8 = NULL;
lv_obj_t * ui_IPoct9 = NULL;
lv_obj_t * ui_GatewayPanel = NULL;
lv_obj_t * ui_GateWayStr = NULL;
lv_obj_t * ui_Label38 = NULL;
lv_obj_t * ui_IPoct10 = NULL;
lv_obj_t * ui_IPoct11 = NULL;
lv_obj_t * ui_IPoct12 = NULL;
lv_obj_t * ui_IPoct13 = NULL;
lv_obj_t * ui_NumKeyboard = NULL;
// event funtions
void ui_event_NetworkConfig(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_NumKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_GotoMenuButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainMenu, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 100, &ui_MainMenu_screen_init);
    }
}

void ui_event_WifiUpdateButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        NetworkConfigUpdateFunc(e);
        _ui_screen_change(&ui_MainMenu, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 1000, 100, &ui_MainMenu_screen_init);
    }
}

void ui_event_IPoct1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_NumKeyboard,  ui_IPoct1);
        _ui_flag_modify(ui_NumKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ip_auto_next(e);
    }
}

void ui_event_IPoct2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_NumKeyboard,  ui_IPoct2);
        _ui_flag_modify(ui_NumKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ip_auto_next(e);
    }
}

void ui_event_IPoct3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_NumKeyboard,  ui_IPoct3);
        _ui_flag_modify(ui_NumKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ip_auto_next(e);
    }
}

void ui_event_IPoct4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_NumKeyboard,  ui_IPoct4);
        _ui_flag_modify(ui_NumKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ip_auto_next(e);
    }
}

void ui_event_IPoct6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_NumKeyboard,  ui_IPoct1);
        _ui_flag_modify(ui_NumKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ip_auto_next(e);
    }
}

void ui_event_IPoct7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_NumKeyboard,  ui_IPoct2);
        _ui_flag_modify(ui_NumKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ip_auto_next(e);
    }
}

void ui_event_IPoct8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_NumKeyboard,  ui_IPoct3);
        _ui_flag_modify(ui_NumKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ip_auto_next(e);
    }
}

void ui_event_IPoct9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_NumKeyboard,  ui_IPoct4);
        _ui_flag_modify(ui_NumKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ip_auto_next(e);
    }
}

void ui_event_IPoct10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_NumKeyboard,  ui_IPoct1);
        _ui_flag_modify(ui_NumKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ip_auto_next(e);
    }
}

void ui_event_IPoct11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_NumKeyboard,  ui_IPoct2);
        _ui_flag_modify(ui_NumKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ip_auto_next(e);
    }
}

void ui_event_IPoct12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_NumKeyboard,  ui_IPoct3);
        _ui_flag_modify(ui_NumKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ip_auto_next(e);
    }
}

void ui_event_IPoct13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_NumKeyboard,  ui_IPoct4);
        _ui_flag_modify(ui_NumKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ip_auto_next(e);
    }
}

void ui_event_NumKeyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        NetworkConfigKeyPressFunc(e);
    }
}

// build funtions

void ui_NetworkConfig_screen_init(void)
{
    ui_NetworkConfig = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_NetworkConfig, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ChangeConfigTitle1 = lv_obj_create(ui_NetworkConfig);
    lv_obj_set_width(ui_ChangeConfigTitle1, 450);
    lv_obj_set_height(ui_ChangeConfigTitle1, 40);
    lv_obj_set_align(ui_ChangeConfigTitle1, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_ChangeConfigTitle1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ChangeConfigTitle1, lv_color_hex(0x2D70A0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChangeConfigTitle1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ChangeConfigTitle1, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NetworkSetupConfig = lv_label_create(ui_ChangeConfigTitle1);
    lv_obj_set_width(ui_NetworkSetupConfig, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NetworkSetupConfig, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NetworkSetupConfig, -80);
    lv_obj_set_y(ui_NetworkSetupConfig, 0);
    lv_obj_set_align(ui_NetworkSetupConfig, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NetworkSetupConfig, "Network Setup");
    lv_obj_set_style_text_font(ui_NetworkSetupConfig, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GotoMenuButton2 = lv_imagebutton_create(ui_ChangeConfigTitle1);
    lv_imagebutton_set_src(ui_GotoMenuButton2, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_backsmallarrow_png, NULL);
    lv_imagebutton_set_src(ui_GotoMenuButton2, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_backsmallarrow_png, NULL);
    lv_obj_set_width(ui_GotoMenuButton2, 35);
    lv_obj_set_height(ui_GotoMenuButton2, 35);
    lv_obj_set_align(ui_GotoMenuButton2, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_radius(ui_GotoMenuButton2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GotoMenuButton2, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GotoMenuButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NetworkContainer1 = lv_obj_create(ui_NetworkConfig);
    lv_obj_remove_style_all(ui_NetworkContainer1);
    lv_obj_set_width(ui_NetworkContainer1, 480);
    lv_obj_set_height(ui_NetworkContainer1, 290);
    lv_obj_set_align(ui_NetworkContainer1, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_NetworkContainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_IpPanel1 = lv_obj_create(ui_NetworkContainer1);
    lv_obj_set_width(ui_IpPanel1, 445);
    lv_obj_set_height(ui_IpPanel1, 30);
    lv_obj_set_x(ui_IpPanel1, 0);
    lv_obj_set_y(ui_IpPanel1, -100);
    lv_obj_set_align(ui_IpPanel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_IpPanel1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_IpPanel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IpPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_IpPanel1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BacNetPortStr4 = lv_label_create(ui_IpPanel1);
    lv_obj_set_width(ui_BacNetPortStr4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BacNetPortStr4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BacNetPortStr4, -10);
    lv_obj_set_y(ui_BacNetPortStr4, 0);
    lv_obj_set_align(ui_BacNetPortStr4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BacNetPortStr4, "Assignment    :");
    lv_obj_remove_flag(ui_BacNetPortStr4,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);    /// Flags
    lv_obj_set_style_text_font(ui_BacNetPortStr4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Checkbox3 = lv_checkbox_create(ui_IpPanel1);
    lv_checkbox_set_text(ui_Checkbox3, "Auto(DHCP)");
    lv_obj_set_width(ui_Checkbox3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Checkbox3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Checkbox3, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Checkbox3, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Checkbox2 = lv_checkbox_create(ui_IpPanel1);
    lv_checkbox_set_text(ui_Checkbox2, "Static IP");
    lv_obj_set_width(ui_Checkbox2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Checkbox2, -30);
    lv_obj_set_y(ui_Checkbox2, 0);
    lv_obj_set_align(ui_Checkbox2, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Checkbox2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Checkbox2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Checkbox2, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_WifiUpdateButton2 = lv_button_create(ui_NetworkContainer1);
    lv_obj_set_width(ui_WifiUpdateButton2, 100);
    lv_obj_set_height(ui_WifiUpdateButton2, 30);
    lv_obj_set_x(ui_WifiUpdateButton2, 180);
    lv_obj_set_y(ui_WifiUpdateButton2, 120);
    lv_obj_set_align(ui_WifiUpdateButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiUpdateButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_WifiUpdateButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiUpdateButton2, lv_color_hex(0x2971A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiUpdateButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_WifiUpdateButton2);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Update");
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IpPanel2 = lv_obj_create(ui_NetworkContainer1);
    lv_obj_set_width(ui_IpPanel2, 445);
    lv_obj_set_height(ui_IpPanel2, 35);
    lv_obj_set_x(ui_IpPanel2, 0);
    lv_obj_set_y(ui_IpPanel2, -60);
    lv_obj_set_align(ui_IpPanel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_IpPanel2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_IpPanel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IpPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_IpPanel2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IpAddressStr = lv_label_create(ui_IpPanel2);
    lv_obj_set_width(ui_IpAddressStr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IpAddressStr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IpAddressStr, -10);
    lv_obj_set_y(ui_IpAddressStr, 0);
    lv_obj_set_align(ui_IpAddressStr, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_IpAddressStr, "IP Address          :");
    lv_obj_remove_flag(ui_IpAddressStr, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM);    /// Flags
    lv_obj_set_style_text_font(ui_IpAddressStr, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_IpAddressStr, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label34 = lv_label_create(ui_IpPanel2);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label34, 36);
    lv_obj_set_y(ui_Label34, 2);
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "               .                 .                 . ");

    ui_IPoct1 = lv_textarea_create(ui_IpPanel2);
    lv_obj_set_width(ui_IPoct1, 60);
    lv_obj_set_height(ui_IPoct1, 30);
    lv_obj_set_x(ui_IPoct1, -40);
    lv_obj_set_y(ui_IPoct1, 0);
    lv_obj_set_align(ui_IPoct1, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_IPoct1, "0123456789");
    lv_textarea_set_max_length(ui_IPoct1, 3);
    lv_textarea_set_placeholder_text(ui_IPoct1, "192");
    lv_obj_remove_flag(ui_IPoct1, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_IPoct1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_letter_space(ui_IPoct1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_IPoct1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_IPoct1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IPoct1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_IPoct1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_IPoct1, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_IPoct1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_IPoct1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_IPoct1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IPoct2 = lv_textarea_create(ui_IpPanel2);
    lv_obj_set_width(ui_IPoct2, 60);
    lv_obj_set_height(ui_IPoct2, 30);
    lv_obj_set_x(ui_IPoct2, 30);
    lv_obj_set_y(ui_IPoct2, 0);
    lv_obj_set_align(ui_IPoct2, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_IPoct2, "0123456789");
    lv_textarea_set_max_length(ui_IPoct2, 3);
    lv_textarea_set_placeholder_text(ui_IPoct2, "168");
    lv_obj_remove_flag(ui_IPoct2, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_IPoct2, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_letter_space(ui_IPoct2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_IPoct2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_IPoct2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IPoct2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_IPoct2, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_IPoct2, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_IPoct2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_IPoct2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_IPoct2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IPoct3 = lv_textarea_create(ui_IpPanel2);
    lv_obj_set_width(ui_IPoct3, 60);
    lv_obj_set_height(ui_IPoct3, 30);
    lv_obj_set_x(ui_IPoct3, 100);
    lv_obj_set_y(ui_IPoct3, 0);
    lv_obj_set_align(ui_IPoct3, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_IPoct3, "0123456789");
    lv_textarea_set_max_length(ui_IPoct3, 3);
    lv_textarea_set_placeholder_text(ui_IPoct3, "1");
    lv_obj_remove_flag(ui_IPoct3, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_IPoct3, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_letter_space(ui_IPoct3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_IPoct3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_IPoct3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IPoct3, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_IPoct3, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_IPoct3, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_IPoct3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_IPoct3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_IPoct3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IPoct4 = lv_textarea_create(ui_IpPanel2);
    lv_obj_set_width(ui_IPoct4, 60);
    lv_obj_set_height(ui_IPoct4, 30);
    lv_obj_set_x(ui_IPoct4, 170);
    lv_obj_set_y(ui_IPoct4, 0);
    lv_obj_set_align(ui_IPoct4, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_IPoct4, "0123456789");
    lv_textarea_set_max_length(ui_IPoct4, 3);
    lv_textarea_set_placeholder_text(ui_IPoct4, "1");
    lv_obj_remove_flag(ui_IPoct4, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_IPoct4, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_letter_space(ui_IPoct4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_IPoct4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_IPoct4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IPoct4, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_IPoct4, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_IPoct4, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_IPoct4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_IPoct4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_IPoct4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SubnetPanel = lv_obj_create(ui_NetworkContainer1);
    lv_obj_set_width(ui_SubnetPanel, 445);
    lv_obj_set_height(ui_SubnetPanel, 35);
    lv_obj_set_x(ui_SubnetPanel, 0);
    lv_obj_set_y(ui_SubnetPanel, -20);
    lv_obj_set_align(ui_SubnetPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SubnetPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SubnetPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SubnetPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SubnetPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SubNetStr = lv_label_create(ui_SubnetPanel);
    lv_obj_set_width(ui_SubNetStr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SubNetStr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SubNetStr, -10);
    lv_obj_set_y(ui_SubNetStr, 0);
    lv_obj_set_align(ui_SubNetStr, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_SubNetStr, "Subnet                 :");
    lv_obj_remove_flag(ui_SubNetStr, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_style_text_font(ui_SubNetStr, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_SubNetStr, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label37 = lv_label_create(ui_SubnetPanel);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label37, 36);
    lv_obj_set_y(ui_Label37, 2);
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label37, "               .                 .                 . ");

    ui_IPoct6 = lv_textarea_create(ui_SubnetPanel);
    lv_obj_set_width(ui_IPoct6, 60);
    lv_obj_set_height(ui_IPoct6, 30);
    lv_obj_set_x(ui_IPoct6, -40);
    lv_obj_set_y(ui_IPoct6, 0);
    lv_obj_set_align(ui_IPoct6, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_IPoct6, "0123456789");
    lv_textarea_set_max_length(ui_IPoct6, 3);
    lv_textarea_set_placeholder_text(ui_IPoct6, "255");
    lv_obj_remove_flag(ui_IPoct6, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_IPoct6, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_letter_space(ui_IPoct6, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_IPoct6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_IPoct6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IPoct6, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_IPoct6, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_IPoct6, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_IPoct6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_IPoct6, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_IPoct6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IPoct7 = lv_textarea_create(ui_SubnetPanel);
    lv_obj_set_width(ui_IPoct7, 60);
    lv_obj_set_height(ui_IPoct7, 30);
    lv_obj_set_x(ui_IPoct7, 30);
    lv_obj_set_y(ui_IPoct7, 0);
    lv_obj_set_align(ui_IPoct7, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_IPoct7, "0123456789");
    lv_textarea_set_max_length(ui_IPoct7, 3);
    lv_textarea_set_placeholder_text(ui_IPoct7, "255");
    lv_obj_remove_flag(ui_IPoct7, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_IPoct7, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_letter_space(ui_IPoct7, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_IPoct7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_IPoct7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IPoct7, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_IPoct7, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_IPoct7, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_IPoct7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_IPoct7, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_IPoct7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IPoct8 = lv_textarea_create(ui_SubnetPanel);
    lv_obj_set_width(ui_IPoct8, 60);
    lv_obj_set_height(ui_IPoct8, 30);
    lv_obj_set_x(ui_IPoct8, 100);
    lv_obj_set_y(ui_IPoct8, 0);
    lv_obj_set_align(ui_IPoct8, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_IPoct8, "0123456789");
    lv_textarea_set_max_length(ui_IPoct8, 3);
    lv_textarea_set_placeholder_text(ui_IPoct8, "1");
    lv_obj_remove_flag(ui_IPoct8, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_IPoct8, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_letter_space(ui_IPoct8, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_IPoct8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_IPoct8, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IPoct8, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_IPoct8, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_IPoct8, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_IPoct8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_IPoct8, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_IPoct8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IPoct9 = lv_textarea_create(ui_SubnetPanel);
    lv_obj_set_width(ui_IPoct9, 60);
    lv_obj_set_height(ui_IPoct9, 30);
    lv_obj_set_x(ui_IPoct9, 170);
    lv_obj_set_y(ui_IPoct9, 0);
    lv_obj_set_align(ui_IPoct9, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_IPoct9, "0123456789");
    lv_textarea_set_max_length(ui_IPoct9, 3);
    lv_textarea_set_placeholder_text(ui_IPoct9, "0");
    lv_obj_remove_flag(ui_IPoct9, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_IPoct9, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_letter_space(ui_IPoct9, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_IPoct9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_IPoct9, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IPoct9, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_IPoct9, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_IPoct9, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_IPoct9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_IPoct9, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_IPoct9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GatewayPanel = lv_obj_create(ui_NetworkContainer1);
    lv_obj_set_width(ui_GatewayPanel, 445);
    lv_obj_set_height(ui_GatewayPanel, 35);
    lv_obj_set_x(ui_GatewayPanel, 0);
    lv_obj_set_y(ui_GatewayPanel, 20);
    lv_obj_set_align(ui_GatewayPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_GatewayPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GatewayPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GatewayPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_GatewayPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GateWayStr = lv_label_create(ui_GatewayPanel);
    lv_obj_set_width(ui_GateWayStr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GateWayStr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GateWayStr, -10);
    lv_obj_set_y(ui_GateWayStr, 0);
    lv_obj_set_align(ui_GateWayStr, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_GateWayStr, "Gateway              :");
    lv_obj_remove_flag(ui_GateWayStr, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM);    /// Flags
    lv_obj_set_style_text_font(ui_GateWayStr, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_GateWayStr, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label38 = lv_label_create(ui_GatewayPanel);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label38, 36);
    lv_obj_set_y(ui_Label38, 2);
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, "               .                 .                 . ");

    ui_IPoct10 = lv_textarea_create(ui_GatewayPanel);
    lv_obj_set_width(ui_IPoct10, 60);
    lv_obj_set_height(ui_IPoct10, 30);
    lv_obj_set_x(ui_IPoct10, -40);
    lv_obj_set_y(ui_IPoct10, 0);
    lv_obj_set_align(ui_IPoct10, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_IPoct10, "0123456789");
    lv_textarea_set_max_length(ui_IPoct10, 3);
    lv_textarea_set_placeholder_text(ui_IPoct10, "192");
    lv_obj_remove_flag(ui_IPoct10, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_IPoct10, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_letter_space(ui_IPoct10, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_IPoct10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_IPoct10, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IPoct10, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_IPoct10, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_IPoct10, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_IPoct10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_IPoct10, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_IPoct10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IPoct11 = lv_textarea_create(ui_GatewayPanel);
    lv_obj_set_width(ui_IPoct11, 60);
    lv_obj_set_height(ui_IPoct11, 30);
    lv_obj_set_x(ui_IPoct11, 30);
    lv_obj_set_y(ui_IPoct11, 0);
    lv_obj_set_align(ui_IPoct11, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_IPoct11, "0123456789");
    lv_textarea_set_max_length(ui_IPoct11, 3);
    lv_textarea_set_placeholder_text(ui_IPoct11, "168");
    lv_obj_remove_flag(ui_IPoct11, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_IPoct11, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_letter_space(ui_IPoct11, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_IPoct11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_IPoct11, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IPoct11, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_IPoct11, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_IPoct11, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_IPoct11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_IPoct11, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_IPoct11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IPoct12 = lv_textarea_create(ui_GatewayPanel);
    lv_obj_set_width(ui_IPoct12, 60);
    lv_obj_set_height(ui_IPoct12, 30);
    lv_obj_set_x(ui_IPoct12, 100);
    lv_obj_set_y(ui_IPoct12, 0);
    lv_obj_set_align(ui_IPoct12, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_IPoct12, "0123456789");
    lv_textarea_set_max_length(ui_IPoct12, 3);
    lv_textarea_set_placeholder_text(ui_IPoct12, "1");
    lv_obj_remove_flag(ui_IPoct12, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_IPoct12, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_letter_space(ui_IPoct12, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_IPoct12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_IPoct12, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IPoct12, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_IPoct12, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_IPoct12, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_IPoct12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_IPoct12, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_IPoct12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IPoct13 = lv_textarea_create(ui_GatewayPanel);
    lv_obj_set_width(ui_IPoct13, 60);
    lv_obj_set_height(ui_IPoct13, 30);
    lv_obj_set_x(ui_IPoct13, 170);
    lv_obj_set_y(ui_IPoct13, 0);
    lv_obj_set_align(ui_IPoct13, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_IPoct13, "0123456789");
    lv_textarea_set_max_length(ui_IPoct13, 3);
    lv_textarea_set_placeholder_text(ui_IPoct13, "0");
    lv_obj_remove_flag(ui_IPoct13, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_IPoct13, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_letter_space(ui_IPoct13, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_IPoct13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_IPoct13, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IPoct13, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_IPoct13, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_IPoct13, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_IPoct13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_IPoct13, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_IPoct13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NumKeyboard = lv_keyboard_create(ui_NetworkContainer1);
    lv_keyboard_set_mode(ui_NumKeyboard, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_NumKeyboard, 300);
    lv_obj_set_height(ui_NumKeyboard, 120);
    lv_obj_set_align(ui_NumKeyboard, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_NumKeyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_NumKeyboard, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_GotoMenuButton2, ui_event_GotoMenuButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WifiUpdateButton2, ui_event_WifiUpdateButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IPoct1, ui_event_IPoct1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IPoct2, ui_event_IPoct2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IPoct3, ui_event_IPoct3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IPoct4, ui_event_IPoct4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IPoct6, ui_event_IPoct6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IPoct7, ui_event_IPoct7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IPoct8, ui_event_IPoct8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IPoct9, ui_event_IPoct9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IPoct10, ui_event_IPoct10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IPoct11, ui_event_IPoct11, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IPoct12, ui_event_IPoct12, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IPoct13, ui_event_IPoct13, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_NumKeyboard, ui_IPoct1);
    lv_obj_add_event_cb(ui_NumKeyboard, ui_event_NumKeyboard, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_NetworkConfig, ui_event_NetworkConfig, LV_EVENT_ALL, NULL);
    uic_NetworkConfig = ui_NetworkConfig;
    uic_NumKeyboard = ui_NumKeyboard;

}

void ui_NetworkConfig_screen_destroy(void)
{
    if(ui_NetworkConfig) lv_obj_del(ui_NetworkConfig);

    // NULL screen variables
    uic_NetworkConfig = NULL;
    ui_NetworkConfig = NULL;
    ui_ChangeConfigTitle1 = NULL;
    ui_NetworkSetupConfig = NULL;
    ui_GotoMenuButton2 = NULL;
    ui_NetworkContainer1 = NULL;
    ui_IpPanel1 = NULL;
    ui_BacNetPortStr4 = NULL;
    ui_Checkbox3 = NULL;
    ui_Checkbox2 = NULL;
    ui_WifiUpdateButton2 = NULL;
    ui_Label13 = NULL;
    ui_IpPanel2 = NULL;
    ui_IpAddressStr = NULL;
    ui_Label34 = NULL;
    ui_IPoct1 = NULL;
    ui_IPoct2 = NULL;
    ui_IPoct3 = NULL;
    ui_IPoct4 = NULL;
    ui_SubnetPanel = NULL;
    ui_SubNetStr = NULL;
    ui_Label37 = NULL;
    ui_IPoct6 = NULL;
    ui_IPoct7 = NULL;
    ui_IPoct8 = NULL;
    ui_IPoct9 = NULL;
    ui_GatewayPanel = NULL;
    ui_GateWayStr = NULL;
    ui_Label38 = NULL;
    ui_IPoct10 = NULL;
    ui_IPoct11 = NULL;
    ui_IPoct12 = NULL;
    ui_IPoct13 = NULL;
    uic_NumKeyboard = NULL;
    ui_NumKeyboard = NULL;

}
