// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: TemcoProject

#include "ui.h"

lv_obj_t * uic_Parameters;
lv_obj_t * ui_Parameters = NULL;
lv_obj_t * ui_ChangeConfigTitle2 = NULL;
lv_obj_t * ui_NetworkSetupConfig4 = NULL;
lv_obj_t * ui_GotoMenuButton8 = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_ParameterUpdateBtn = NULL;
lv_obj_t * ui_Label15 = NULL;
// event funtions
void ui_event_Parameters(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        UpdateParameterTableFunc(e);
    }
}

void ui_event_GotoMenuButton8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainMenu, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 100, &ui_MainMenu_screen_init);
    }
}

void ui_event_ParameterUpdateBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ParameterUpdateFunc(e);
        _ui_screen_change(&ui_MainMenu, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 1000, 100, &ui_MainMenu_screen_init);
    }
}

// build funtions

void ui_Parameters_screen_init(void)
{
    ui_Parameters = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Parameters, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ChangeConfigTitle2 = lv_obj_create(ui_Parameters);
    lv_obj_set_width(ui_ChangeConfigTitle2, 450);
    lv_obj_set_height(ui_ChangeConfigTitle2, 40);
    lv_obj_set_align(ui_ChangeConfigTitle2, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_ChangeConfigTitle2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ChangeConfigTitle2, lv_color_hex(0x2D70A0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChangeConfigTitle2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ChangeConfigTitle2, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NetworkSetupConfig4 = lv_label_create(ui_ChangeConfigTitle2);
    lv_obj_set_width(ui_NetworkSetupConfig4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NetworkSetupConfig4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NetworkSetupConfig4, -80);
    lv_obj_set_y(ui_NetworkSetupConfig4, 0);
    lv_obj_set_align(ui_NetworkSetupConfig4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NetworkSetupConfig4, "   Parameter Setup");
    lv_obj_set_style_text_font(ui_NetworkSetupConfig4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GotoMenuButton8 = lv_imagebutton_create(ui_ChangeConfigTitle2);
    lv_imagebutton_set_src(ui_GotoMenuButton8, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_backsmallarrow_png, NULL);
    lv_imagebutton_set_src(ui_GotoMenuButton8, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_backsmallarrow_png, NULL);
    lv_obj_set_width(ui_GotoMenuButton8, 35);
    lv_obj_set_height(ui_GotoMenuButton8, 35);
    lv_obj_set_align(ui_GotoMenuButton8, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_radius(ui_GotoMenuButton8, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GotoMenuButton8, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GotoMenuButton8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_Parameters);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 480);
    lv_obj_set_height(ui_Container1, 280);
    lv_obj_set_x(ui_Container1, 0);
    lv_obj_set_y(ui_Container1, 20);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel4 = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_Panel4, 480);
    lv_obj_set_height(ui_Panel4, 230);
    lv_obj_set_x(ui_Panel4, 0);
    lv_obj_set_y(ui_Panel4, -20);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel4, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ParameterUpdateBtn = lv_button_create(ui_Container1);
    lv_obj_set_width(ui_ParameterUpdateBtn, 100);
    lv_obj_set_height(ui_ParameterUpdateBtn, 30);
    lv_obj_set_x(ui_ParameterUpdateBtn, 180);
    lv_obj_set_y(ui_ParameterUpdateBtn, 110);
    lv_obj_set_align(ui_ParameterUpdateBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ParameterUpdateBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ParameterUpdateBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ParameterUpdateBtn, lv_color_hex(0x2971A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ParameterUpdateBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_ParameterUpdateBtn);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Update");
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_GotoMenuButton8, ui_event_GotoMenuButton8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ParameterUpdateBtn, ui_event_ParameterUpdateBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Parameters, ui_event_Parameters, LV_EVENT_ALL, NULL);
    uic_Parameters = ui_Parameters;

}

void ui_Parameters_screen_destroy(void)
{
    if(ui_Parameters) lv_obj_del(ui_Parameters);

    // NULL screen variables
    uic_Parameters = NULL;
    ui_Parameters = NULL;
    ui_ChangeConfigTitle2 = NULL;
    ui_NetworkSetupConfig4 = NULL;
    ui_GotoMenuButton8 = NULL;
    ui_Container1 = NULL;
    ui_Panel4 = NULL;
    ui_ParameterUpdateBtn = NULL;
    ui_Label15 = NULL;

}
