// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: TemcoProject

#include "ui.h"

lv_obj_t * uic_BaudRateText;
lv_obj_t * uic_PanelNameText;
lv_obj_t * ui_Protocols = NULL;
lv_obj_t * ui_ChangeConfigTitle7 = NULL;
lv_obj_t * ui_NetworkSetupConfig3 = NULL;
lv_obj_t * ui_GotoMenuButton7 = NULL;
lv_obj_t * ui_ProtocolContainer = NULL;
lv_obj_t * ui_WifiPassPanel2 = NULL;
lv_obj_t * ui_PasswordStr3 = NULL;
lv_obj_t * ui_PanelNameText = NULL;
lv_obj_t * ui_CommPanel = NULL;
lv_obj_t * ui_DropdownNetdata2 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_BacNetPortPanel2 = NULL;
lv_obj_t * ui_BacNetPortStr2 = NULL;
lv_obj_t * ui_ModbusIdText = NULL;
lv_obj_t * ui_ModbusPortPanel2 = NULL;
lv_obj_t * ui_ModbusPortStr2 = NULL;
lv_obj_t * ui_BaudRateText = NULL;
lv_obj_t * ui_WifiUpdateButton3 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_KeyboardProtocol = NULL;
lv_obj_t * ui_NumKeyboardProtocol = NULL;
// event funtions
void ui_event_Protocols(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_NumKeyboardProtocol, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_KeyboardProtocol, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_GotoMenuButton7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainMenu, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 100, &ui_MainMenu_screen_init);
    }
}

void ui_event_PanelNameText(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_KeyboardProtocol,  ui_PanelNameText);
        _ui_flag_modify(ui_NumKeyboardProtocol, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_KeyboardProtocol, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_ModbusIdText(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_NumKeyboardProtocol,  ui_ModbusIdText);
        _ui_flag_modify(ui_NumKeyboardProtocol, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_KeyboardProtocol, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_BaudRateText(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_NumKeyboardProtocol,  ui_BaudRateText);
        _ui_flag_modify(ui_NumKeyboardProtocol, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_KeyboardProtocol, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_WifiUpdateButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        UpdateWifiConfig(e);
        _ui_screen_change(&ui_MainMenu, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 1000, 100, &ui_MainMenu_screen_init);
    }
}

void ui_event_KeyboardProtocol(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        WifiKeyboardPressFunc(e);
    }
}

void ui_event_NumKeyboardProtocol(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        NetworkConfigKeyPressFunc(e);
    }
}

// build funtions

void ui_Protocols_screen_init(void)
{
    ui_Protocols = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Protocols, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ChangeConfigTitle7 = lv_obj_create(ui_Protocols);
    lv_obj_set_width(ui_ChangeConfigTitle7, 450);
    lv_obj_set_height(ui_ChangeConfigTitle7, 40);
    lv_obj_set_align(ui_ChangeConfigTitle7, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_ChangeConfigTitle7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ChangeConfigTitle7, lv_color_hex(0x2D70A0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChangeConfigTitle7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ChangeConfigTitle7, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NetworkSetupConfig3 = lv_label_create(ui_ChangeConfigTitle7);
    lv_obj_set_width(ui_NetworkSetupConfig3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NetworkSetupConfig3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NetworkSetupConfig3, -80);
    lv_obj_set_y(ui_NetworkSetupConfig3, 0);
    lv_obj_set_align(ui_NetworkSetupConfig3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NetworkSetupConfig3, "Protocol Setup");
    lv_obj_set_style_text_font(ui_NetworkSetupConfig3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GotoMenuButton7 = lv_imagebutton_create(ui_ChangeConfigTitle7);
    lv_imagebutton_set_src(ui_GotoMenuButton7, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_backsmallarrow_png, NULL);
    lv_imagebutton_set_src(ui_GotoMenuButton7, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_backsmallarrow_png, NULL);
    lv_obj_set_width(ui_GotoMenuButton7, 35);
    lv_obj_set_height(ui_GotoMenuButton7, 35);
    lv_obj_set_align(ui_GotoMenuButton7, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_radius(ui_GotoMenuButton7, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GotoMenuButton7, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GotoMenuButton7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProtocolContainer = lv_obj_create(ui_Protocols);
    lv_obj_remove_style_all(ui_ProtocolContainer);
    lv_obj_set_width(ui_ProtocolContainer, 480);
    lv_obj_set_height(ui_ProtocolContainer, 290);
    lv_obj_set_align(ui_ProtocolContainer, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_ProtocolContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiPassPanel2 = lv_obj_create(ui_ProtocolContainer);
    lv_obj_set_width(ui_WifiPassPanel2, 445);
    lv_obj_set_height(ui_WifiPassPanel2, 45);
    lv_obj_set_x(ui_WifiPassPanel2, 0);
    lv_obj_set_y(ui_WifiPassPanel2, -20);
    lv_obj_set_align(ui_WifiPassPanel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WifiPassPanel2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiPassPanel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiPassPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_WifiPassPanel2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PasswordStr3 = lv_label_create(ui_WifiPassPanel2);
    lv_obj_set_width(ui_PasswordStr3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PasswordStr3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PasswordStr3, -10);
    lv_obj_set_y(ui_PasswordStr3, 0);
    lv_obj_set_align(ui_PasswordStr3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_PasswordStr3, "Panel Name               :");
    lv_obj_remove_flag(ui_PasswordStr3, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM);    /// Flags
    lv_obj_set_style_text_font(ui_PasswordStr3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelNameText = lv_textarea_create(ui_WifiPassPanel2);
    lv_obj_set_width(ui_PanelNameText, 200);
    lv_obj_set_height(ui_PanelNameText, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_x(ui_PanelNameText, 85);
    lv_obj_set_y(ui_PanelNameText, 0);
    lv_obj_set_align(ui_PanelNameText, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_PanelNameText, 20);
    lv_textarea_set_placeholder_text(ui_PanelNameText, "Panel Name");
    lv_textarea_set_one_line(ui_PanelNameText, true);
    lv_obj_set_style_radius(ui_PanelNameText, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelNameText, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CommPanel = lv_obj_create(ui_ProtocolContainer);
    lv_obj_set_width(ui_CommPanel, 445);
    lv_obj_set_height(ui_CommPanel, 45);
    lv_obj_set_x(ui_CommPanel, 0);
    lv_obj_set_y(ui_CommPanel, 60);
    lv_obj_set_align(ui_CommPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_CommPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CommPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CommPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_CommPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropdownNetdata2 = lv_dropdown_create(ui_CommPanel);
    lv_dropdown_set_options(ui_DropdownNetdata2, "BACnet Slave\nModbus Slave");
    lv_obj_set_width(ui_DropdownNetdata2, 160);
    lv_obj_set_height(ui_DropdownNetdata2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownNetdata2, 60);
    lv_obj_set_y(ui_DropdownNetdata2, 0);
    lv_obj_set_align(ui_DropdownNetdata2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownNetdata2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_DropdownNetdata2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_DropdownNetdata2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_DropdownNetdata2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_CommPanel);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -130);
    lv_obj_set_y(ui_Label10, 0);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Communication Type  :");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BacNetPortPanel2 = lv_obj_create(ui_ProtocolContainer);
    lv_obj_set_width(ui_BacNetPortPanel2, 445);
    lv_obj_set_height(ui_BacNetPortPanel2, 45);
    lv_obj_set_x(ui_BacNetPortPanel2, 0);
    lv_obj_set_y(ui_BacNetPortPanel2, -110);
    lv_obj_set_align(ui_BacNetPortPanel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_BacNetPortPanel2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BacNetPortPanel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BacNetPortPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BacNetPortPanel2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BacNetPortStr2 = lv_label_create(ui_BacNetPortPanel2);
    lv_obj_set_width(ui_BacNetPortStr2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BacNetPortStr2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BacNetPortStr2, -10);
    lv_obj_set_y(ui_BacNetPortStr2, 0);
    lv_obj_set_align(ui_BacNetPortStr2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BacNetPortStr2, "Modbus/Bacnet Id    :");
    lv_obj_remove_flag(ui_BacNetPortStr2,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);    /// Flags
    lv_obj_set_style_text_font(ui_BacNetPortStr2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ModbusIdText = lv_textarea_create(ui_BacNetPortPanel2);
    lv_obj_set_width(ui_ModbusIdText, 150);
    lv_obj_set_height(ui_ModbusIdText, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_x(ui_ModbusIdText, 60);
    lv_obj_set_y(ui_ModbusIdText, 0);
    lv_obj_set_align(ui_ModbusIdText, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_ModbusIdText, "0123456789");
    lv_textarea_set_max_length(ui_ModbusIdText, 5);
    lv_textarea_set_placeholder_text(ui_ModbusIdText, "ID");
    lv_textarea_set_one_line(ui_ModbusIdText, true);
    lv_obj_set_style_radius(ui_ModbusIdText, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ModbusIdText, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ModbusPortPanel2 = lv_obj_create(ui_ProtocolContainer);
    lv_obj_set_width(ui_ModbusPortPanel2, 445);
    lv_obj_set_height(ui_ModbusPortPanel2, 45);
    lv_obj_set_x(ui_ModbusPortPanel2, 0);
    lv_obj_set_y(ui_ModbusPortPanel2, -65);
    lv_obj_set_align(ui_ModbusPortPanel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ModbusPortPanel2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ModbusPortPanel2, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ModbusPortPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ModbusPortPanel2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ModbusPortStr2 = lv_label_create(ui_ModbusPortPanel2);
    lv_obj_set_width(ui_ModbusPortStr2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ModbusPortStr2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ModbusPortStr2, -10);
    lv_obj_set_y(ui_ModbusPortStr2, 0);
    lv_obj_set_align(ui_ModbusPortStr2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ModbusPortStr2, "Baud Rate                  :");
    lv_obj_remove_flag(ui_ModbusPortStr2,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);    /// Flags
    lv_obj_set_style_text_font(ui_ModbusPortStr2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BaudRateText = lv_textarea_create(ui_ModbusPortPanel2);
    lv_obj_set_width(ui_BaudRateText, 150);
    lv_obj_set_height(ui_BaudRateText, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_x(ui_BaudRateText, 60);
    lv_obj_set_y(ui_BaudRateText, 0);
    lv_obj_set_align(ui_BaudRateText, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_BaudRateText, "0123456789");
    lv_textarea_set_max_length(ui_BaudRateText, 10);
    lv_textarea_set_placeholder_text(ui_BaudRateText, "Baud Rate");
    lv_textarea_set_one_line(ui_BaudRateText, true);
    lv_obj_set_style_radius(ui_BaudRateText, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BaudRateText, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiUpdateButton3 = lv_button_create(ui_ProtocolContainer);
    lv_obj_set_width(ui_WifiUpdateButton3, 100);
    lv_obj_set_height(ui_WifiUpdateButton3, 30);
    lv_obj_set_x(ui_WifiUpdateButton3, 180);
    lv_obj_set_y(ui_WifiUpdateButton3, 120);
    lv_obj_set_align(ui_WifiUpdateButton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiUpdateButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_WifiUpdateButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiUpdateButton3, lv_color_hex(0x2971A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiUpdateButton3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_WifiUpdateButton3);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Update");
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KeyboardProtocol = lv_keyboard_create(ui_ProtocolContainer);
    lv_obj_set_width(ui_KeyboardProtocol, 480);
    lv_obj_set_height(ui_KeyboardProtocol, 120);
    lv_obj_set_x(ui_KeyboardProtocol, 0);
    lv_obj_set_y(ui_KeyboardProtocol, 1);
    lv_obj_set_align(ui_KeyboardProtocol, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_KeyboardProtocol, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_border_side(ui_KeyboardProtocol, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_KeyboardProtocol, 0, LV_PART_MAIN | LV_STATE_DISABLED);

    lv_obj_set_style_radius(ui_KeyboardProtocol, 30, LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_NumKeyboardProtocol = lv_keyboard_create(ui_ProtocolContainer);
    lv_keyboard_set_mode(ui_NumKeyboardProtocol, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_NumKeyboardProtocol, 300);
    lv_obj_set_height(ui_NumKeyboardProtocol, 120);
    lv_obj_set_align(ui_NumKeyboardProtocol, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_NumKeyboardProtocol, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_GotoMenuButton7, ui_event_GotoMenuButton7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelNameText, ui_event_PanelNameText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ModbusIdText, ui_event_ModbusIdText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BaudRateText, ui_event_BaudRateText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WifiUpdateButton3, ui_event_WifiUpdateButton3, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_KeyboardProtocol, ui_PanelNameText);
    lv_obj_add_event_cb(ui_KeyboardProtocol, ui_event_KeyboardProtocol, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_NumKeyboardProtocol, ui_PanelNameText);
    lv_obj_add_event_cb(ui_NumKeyboardProtocol, ui_event_NumKeyboardProtocol, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Protocols, ui_event_Protocols, LV_EVENT_ALL, NULL);
    uic_PanelNameText = ui_PanelNameText;
    uic_BaudRateText = ui_BaudRateText;

}

void ui_Protocols_screen_destroy(void)
{
    if(ui_Protocols) lv_obj_del(ui_Protocols);

    // NULL screen variables
    ui_Protocols = NULL;
    ui_ChangeConfigTitle7 = NULL;
    ui_NetworkSetupConfig3 = NULL;
    ui_GotoMenuButton7 = NULL;
    ui_ProtocolContainer = NULL;
    ui_WifiPassPanel2 = NULL;
    ui_PasswordStr3 = NULL;
    uic_PanelNameText = NULL;
    ui_PanelNameText = NULL;
    ui_CommPanel = NULL;
    ui_DropdownNetdata2 = NULL;
    ui_Label10 = NULL;
    ui_BacNetPortPanel2 = NULL;
    ui_BacNetPortStr2 = NULL;
    ui_ModbusIdText = NULL;
    ui_ModbusPortPanel2 = NULL;
    ui_ModbusPortStr2 = NULL;
    uic_BaudRateText = NULL;
    ui_BaudRateText = NULL;
    ui_WifiUpdateButton3 = NULL;
    ui_Label14 = NULL;
    ui_KeyboardProtocol = NULL;
    ui_NumKeyboardProtocol = NULL;

}
