// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: TemcoProject

#ifndef UI_PROTOCOLS_H
#define UI_PROTOCOLS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Protocols
extern void ui_Protocols_screen_init(void);
extern void ui_Protocols_screen_destroy(void);
extern void ui_event_Protocols(lv_event_t * e);
extern lv_obj_t * ui_Protocols;
extern lv_obj_t * ui_ChangeConfigTitle7;
extern lv_obj_t * ui_NetworkSetupConfig3;
extern void ui_event_GotoMenuButton7(lv_event_t * e);
extern lv_obj_t * ui_GotoMenuButton7;
extern lv_obj_t * ui_ProtocolContainer;
extern lv_obj_t * ui_WifiPassPanel2;
extern lv_obj_t * ui_PasswordStr3;
extern void ui_event_PanelNameText(lv_event_t * e);
extern lv_obj_t * ui_PanelNameText;
extern lv_obj_t * ui_CommPanel;
extern lv_obj_t * ui_DropdownNetdata2;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_BacNetPortPanel2;
extern lv_obj_t * ui_BacNetPortStr2;
extern void ui_event_ModbusIdText(lv_event_t * e);
extern lv_obj_t * ui_ModbusIdText;
extern lv_obj_t * ui_ModbusPortPanel2;
extern lv_obj_t * ui_ModbusPortStr2;
extern void ui_event_BaudRateText(lv_event_t * e);
extern lv_obj_t * ui_BaudRateText;
extern void ui_event_WifiUpdateButton3(lv_event_t * e);
extern lv_obj_t * ui_WifiUpdateButton3;
extern lv_obj_t * ui_Label14;
extern void ui_event_KeyboardProtocol(lv_event_t * e);
extern lv_obj_t * ui_KeyboardProtocol;
extern void ui_event_NumKeyboardProtocol(lv_event_t * e);
extern lv_obj_t * ui_NumKeyboardProtocol;
// CUSTOM VARIABLES
extern lv_obj_t * uic_PanelNameText;
extern lv_obj_t * uic_BaudRateText;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

