// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: TemcoProject

#ifndef UI_PARAMETERS_H
#define UI_PARAMETERS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Parameters
extern void ui_Parameters_screen_init(void);
extern void ui_Parameters_screen_destroy(void);
extern void ui_event_Parameters(lv_event_t * e);
extern lv_obj_t * ui_Parameters;
extern lv_obj_t * ui_ChangeConfigTitle2;
extern lv_obj_t * ui_NetworkSetupConfig4;
extern void ui_event_GotoMenuButton8(lv_event_t * e);
extern lv_obj_t * ui_GotoMenuButton8;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label42;
extern lv_obj_t * ui_Label43;
extern lv_obj_t * ui_Label44;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Parameters;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

