// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: TemcoProject

#ifndef UI_STARTUPSCREEN_H
#define UI_STARTUPSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_StartUpScreen
extern void ui_StartUpScreen_screen_init(void);
extern void ui_StartUpScreen_screen_destroy(void);
extern void ui_event_StartUpScreen(lv_event_t * e);
extern lv_obj_t * ui_StartUpScreen;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

