// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: TemcoProject

#ifndef UI_SCHEDULEEDITSCREEN_H
#define UI_SCHEDULEEDITSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScheduleEditScreen
extern void ui_ScheduleEditScreen_screen_init(void);
extern void ui_ScheduleEditScreen_screen_destroy(void);
extern lv_obj_t * ui_ScheduleEditScreen;
extern lv_obj_t * ui_ChangeConfigTitle8;
extern lv_obj_t * ui_ScheduleSetupstr1;
extern void ui_event_GotoMenuButton3(lv_event_t * e);
extern lv_obj_t * ui_GotoMenuButton3;
extern lv_obj_t * ui_Dropdown9;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_SchedulePanelMain1;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_ScheduleEditPanel;
extern lv_obj_t * ui_StateStr;
extern lv_obj_t * ui_StateStr1;
extern lv_obj_t * ui_StateStr2;
extern lv_obj_t * ui_StateStr3;
extern lv_obj_t * ui_StateStr4;
extern lv_obj_t * ui_StateStr5;
extern lv_obj_t * ui_StateStr6;
extern lv_obj_t * ui_StateStr7;
extern lv_obj_t * ui_ScheduleEditPanel1;
extern lv_obj_t * ui_SchState1;
extern lv_obj_t * ui_ScheduleText1;
extern lv_obj_t * ui_ScheduleText2;
extern lv_obj_t * ui_ScheduleText3;
extern lv_obj_t * ui_ScheduleText4;
extern lv_obj_t * ui_ScheduleText5;
extern lv_obj_t * ui_ScheduleText6;
extern lv_obj_t * ui_ScheduleText7;
extern lv_obj_t * ui_ScheduleEditPanel2;
extern lv_obj_t * ui_SchState2;
extern lv_obj_t * ui_ScheduleText8;
extern lv_obj_t * ui_ScheduleText9;
extern lv_obj_t * ui_ScheduleText10;
extern lv_obj_t * ui_ScheduleText11;
extern lv_obj_t * ui_ScheduleText12;
extern lv_obj_t * ui_ScheduleText13;
extern lv_obj_t * ui_ScheduleText14;
extern lv_obj_t * ui_ScheduleEditPanel3;
extern lv_obj_t * ui_SchState3;
extern lv_obj_t * ui_ScheduleText15;
extern lv_obj_t * ui_ScheduleText16;
extern lv_obj_t * ui_ScheduleText17;
extern lv_obj_t * ui_ScheduleText18;
extern lv_obj_t * ui_ScheduleText19;
extern lv_obj_t * ui_ScheduleText20;
extern lv_obj_t * ui_ScheduleText21;
extern lv_obj_t * ui_ScheduleEditPanel4;
extern lv_obj_t * ui_SchState4;
extern lv_obj_t * ui_ScheduleText22;
extern lv_obj_t * ui_ScheduleText23;
extern lv_obj_t * ui_ScheduleText24;
extern lv_obj_t * ui_ScheduleText25;
extern lv_obj_t * ui_ScheduleText26;
extern lv_obj_t * ui_ScheduleText27;
extern lv_obj_t * ui_ScheduleText28;
extern lv_obj_t * ui_ScheduleEditPanel5;
extern lv_obj_t * ui_SchState5;
extern lv_obj_t * ui_ScheduleText29;
extern lv_obj_t * ui_ScheduleText30;
extern lv_obj_t * ui_ScheduleText31;
extern lv_obj_t * ui_ScheduleText32;
extern lv_obj_t * ui_ScheduleText33;
extern lv_obj_t * ui_ScheduleText34;
extern lv_obj_t * ui_ScheduleText35;
extern lv_obj_t * ui_ScheduleEditPanel6;
extern lv_obj_t * ui_SchState6;
extern lv_obj_t * ui_ScheduleText36;
extern lv_obj_t * ui_ScheduleText37;
extern lv_obj_t * ui_ScheduleText38;
extern lv_obj_t * ui_ScheduleText39;
extern lv_obj_t * ui_ScheduleText40;
extern lv_obj_t * ui_ScheduleText41;
extern lv_obj_t * ui_ScheduleText42;
extern lv_obj_t * ui_ScheduleEditPanel7;
extern lv_obj_t * ui_SchState7;
extern lv_obj_t * ui_ScheduleText43;
extern lv_obj_t * ui_ScheduleText44;
extern lv_obj_t * ui_ScheduleText45;
extern lv_obj_t * ui_ScheduleText46;
extern lv_obj_t * ui_ScheduleText47;
extern lv_obj_t * ui_ScheduleText48;
extern lv_obj_t * ui_ScheduleText49;
extern lv_obj_t * ui_ScheduleEditPanel8;
extern lv_obj_t * ui_SchState8;
extern lv_obj_t * ui_ScheduleText50;
extern lv_obj_t * ui_ScheduleText51;
extern lv_obj_t * ui_ScheduleText52;
extern lv_obj_t * ui_ScheduleText53;
extern lv_obj_t * ui_ScheduleText54;
extern lv_obj_t * ui_ScheduleText55;
extern lv_obj_t * ui_ScheduleText56;
extern void ui_event_ScheduleText(lv_event_t * e);
extern lv_obj_t * ui_ScheduleSettingPopup;
extern void ui_event_Button20(lv_event_t * e);
extern lv_obj_t * ui_Button20;
extern lv_obj_t * ui_Label83;
extern lv_obj_t * ui_TimePanel;
extern lv_obj_t * ui_Dropdown6;
extern lv_obj_t * ui_Label66;
extern lv_obj_t * ui_Dropdown7;
extern void ui_event_SchEditSaveBtn(lv_event_t * e);
extern lv_obj_t * ui_SchEditSaveBtn;
extern lv_obj_t * ui_Label84;
extern void ui_event_SchClearAllBtn(lv_event_t * e);
extern lv_obj_t * ui_SchClearAllBtn;
extern lv_obj_t * ui_Label65;
extern void ui_event_SchCopyAllBtn(lv_event_t * e);
extern lv_obj_t * ui_SchCopyAllBtn;
extern lv_obj_t * ui_Label11;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

