// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: TemcoProject

#ifndef UI_SCHEDULESCREEN_H
#define UI_SCHEDULESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScheduleScreen
extern void ui_ScheduleScreen_screen_init(void);
extern void ui_ScheduleScreen_screen_destroy(void);
extern void ui_event_ScheduleScreen(lv_event_t * e);
extern lv_obj_t * ui_ScheduleScreen;
extern lv_obj_t * ui_ChangeConfigTitle5;
extern lv_obj_t * ui_ScheduleSetupstr;
extern void ui_event_GotoMenuButton1(lv_event_t * e);
extern lv_obj_t * ui_GotoMenuButton1;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_SchedulePanelMain;
extern lv_obj_t * ui_SchedulePanel1;
extern lv_obj_t * ui_SchIndex1;
extern void ui_event_SchText1(lv_event_t * e);
extern lv_obj_t * ui_SchText1;
extern void ui_event_SchAutoMan1(lv_event_t * e);
extern lv_obj_t * ui_SchAutoMan1;
extern lv_obj_t * ui_SchAutoManLabel1;
extern void ui_event_SchSwitch1(lv_event_t * e);
extern lv_obj_t * ui_SchSwitch1;
extern lv_obj_t * ui_SchedulePanel2;
extern lv_obj_t * ui_SchIndex2;
extern void ui_event_SchText2(lv_event_t * e);
extern lv_obj_t * ui_SchText2;
extern void ui_event_SchAutoMan2(lv_event_t * e);
extern lv_obj_t * ui_SchAutoMan2;
extern lv_obj_t * ui_SchAutoManLabel2;
extern void ui_event_SchSwitch2(lv_event_t * e);
extern lv_obj_t * ui_SchSwitch2;
extern lv_obj_t * ui_SchedulePanel3;
extern lv_obj_t * ui_SchIndex3;
extern void ui_event_SchText3(lv_event_t * e);
extern lv_obj_t * ui_SchText3;
extern void ui_event_SchAutoMan3(lv_event_t * e);
extern lv_obj_t * ui_SchAutoMan3;
extern lv_obj_t * ui_SchAutoManLabel3;
extern void ui_event_SchSwitch3(lv_event_t * e);
extern lv_obj_t * ui_SchSwitch3;
extern lv_obj_t * ui_SchedulePanel4;
extern lv_obj_t * ui_SchIndex4;
extern void ui_event_SchText4(lv_event_t * e);
extern lv_obj_t * ui_SchText4;
extern void ui_event_SchAutoMan4(lv_event_t * e);
extern lv_obj_t * ui_SchAutoMan4;
extern lv_obj_t * ui_SchAutoManLabel4;
extern void ui_event_SchSwitch4(lv_event_t * e);
extern lv_obj_t * ui_SchSwitch4;
extern lv_obj_t * ui_SchedulePanel5;
extern lv_obj_t * ui_SchIndex5;
extern void ui_event_SchText5(lv_event_t * e);
extern lv_obj_t * ui_SchText5;
extern void ui_event_SchAutoMan5(lv_event_t * e);
extern lv_obj_t * ui_SchAutoMan5;
extern lv_obj_t * ui_SchAutoManLabel5;
extern void ui_event_SchSwitch5(lv_event_t * e);
extern lv_obj_t * ui_SchSwitch5;
extern lv_obj_t * ui_SchedulePanel6;
extern lv_obj_t * ui_SchIndex6;
extern void ui_event_SchText6(lv_event_t * e);
extern lv_obj_t * ui_SchText6;
extern void ui_event_SchAutoMan6(lv_event_t * e);
extern lv_obj_t * ui_SchAutoMan6;
extern lv_obj_t * ui_SchAutoManLabel6;
extern void ui_event_SchSwitch6(lv_event_t * e);
extern lv_obj_t * ui_SchSwitch6;
extern lv_obj_t * ui_SchedulePanel7;
extern lv_obj_t * ui_SchIndex7;
extern void ui_event_SchText7(lv_event_t * e);
extern lv_obj_t * ui_SchText7;
extern void ui_event_SchAutoMan7(lv_event_t * e);
extern lv_obj_t * ui_SchAutoMan7;
extern lv_obj_t * ui_SchAutoManLabel7;
extern void ui_event_SchSwitch7(lv_event_t * e);
extern lv_obj_t * ui_SchSwitch7;
extern lv_obj_t * ui_SchedulePanel8;
extern lv_obj_t * ui_SchIndex8;
extern void ui_event_SchText8(lv_event_t * e);
extern lv_obj_t * ui_SchText8;
extern void ui_event_SchAutoMan8(lv_event_t * e);
extern lv_obj_t * ui_SchAutoMan8;
extern lv_obj_t * ui_SchAutoManLabel8;
extern void ui_event_SchSwitch8(lv_event_t * e);
extern lv_obj_t * ui_SchSwitch8;
extern void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Label64;
extern void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Label63;
extern void ui_event_ScheduleKeyboard(lv_event_t * e);
extern lv_obj_t * ui_ScheduleKeyboard;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

