// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: TemcoProject

#include "ui.h"

lv_obj_t * ui_ScheduleScreen = NULL;
lv_obj_t * ui_ChangeConfigTitle5 = NULL;
lv_obj_t * ui_ScheduleSetupstr = NULL;
lv_obj_t * ui_GotoMenuButton1 = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_SchedulePanelMain = NULL;
lv_obj_t * ui_SchedulePanel1 = NULL;
lv_obj_t * ui_Label45 = NULL;
lv_obj_t * ui_Label46 = NULL;
lv_obj_t * ui_Button6 = NULL;
lv_obj_t * ui_Label47 = NULL;
lv_obj_t * ui_Switch1 = NULL;
lv_obj_t * ui_SchedulePanel2 = NULL;
lv_obj_t * ui_Label48 = NULL;
lv_obj_t * ui_Label49 = NULL;
lv_obj_t * ui_Button7 = NULL;
lv_obj_t * ui_Label50 = NULL;
lv_obj_t * ui_Switch2 = NULL;
lv_obj_t * ui_SchedulePanel3 = NULL;
lv_obj_t * ui_Label51 = NULL;
lv_obj_t * ui_Label52 = NULL;
lv_obj_t * ui_Button8 = NULL;
lv_obj_t * ui_Label53 = NULL;
lv_obj_t * ui_Switch3 = NULL;
lv_obj_t * ui_SchedulePanel4 = NULL;
lv_obj_t * ui_Label54 = NULL;
lv_obj_t * ui_Label55 = NULL;
lv_obj_t * ui_Button9 = NULL;
lv_obj_t * ui_Label56 = NULL;
lv_obj_t * ui_Switch4 = NULL;
lv_obj_t * ui_SchedulePanel5 = NULL;
lv_obj_t * ui_Label57 = NULL;
lv_obj_t * ui_Label58 = NULL;
lv_obj_t * ui_Button10 = NULL;
lv_obj_t * ui_Label59 = NULL;
lv_obj_t * ui_Switch5 = NULL;
lv_obj_t * ui_SchedulePanel6 = NULL;
lv_obj_t * ui_Label60 = NULL;
lv_obj_t * ui_Label61 = NULL;
lv_obj_t * ui_Button11 = NULL;
lv_obj_t * ui_Label62 = NULL;
lv_obj_t * ui_Switch6 = NULL;
lv_obj_t * ui_Button13 = NULL;
lv_obj_t * ui_Label64 = NULL;
lv_obj_t * ui_Button12 = NULL;
lv_obj_t * ui_Label63 = NULL;
// event funtions
void ui_event_GotoMenuButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainMenu, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 100, &ui_MainMenu_screen_init);
    }
}

void ui_event_Button13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScheduleEditScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 200, &ui_ScheduleEditScreen_screen_init);
    }
}

// build funtions

void ui_ScheduleScreen_screen_init(void)
{
    ui_ScheduleScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScheduleScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ChangeConfigTitle5 = lv_obj_create(ui_ScheduleScreen);
    lv_obj_set_width(ui_ChangeConfigTitle5, 450);
    lv_obj_set_height(ui_ChangeConfigTitle5, 40);
    lv_obj_set_align(ui_ChangeConfigTitle5, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_ChangeConfigTitle5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ChangeConfigTitle5, lv_color_hex(0x2D70A0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChangeConfigTitle5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ChangeConfigTitle5, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScheduleSetupstr = lv_label_create(ui_ChangeConfigTitle5);
    lv_obj_set_width(ui_ScheduleSetupstr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScheduleSetupstr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScheduleSetupstr, -80);
    lv_obj_set_y(ui_ScheduleSetupstr, 0);
    lv_obj_set_align(ui_ScheduleSetupstr, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScheduleSetupstr, "   Schedule Setup");
    lv_obj_set_style_text_font(ui_ScheduleSetupstr, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GotoMenuButton1 = lv_imagebutton_create(ui_ChangeConfigTitle5);
    lv_imagebutton_set_src(ui_GotoMenuButton1, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_backsmallarrow_png, NULL);
    lv_imagebutton_set_src(ui_GotoMenuButton1, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_backsmallarrow_png, NULL);
    lv_obj_set_width(ui_GotoMenuButton1, 35);
    lv_obj_set_height(ui_GotoMenuButton1, 35);
    lv_obj_set_align(ui_GotoMenuButton1, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_radius(ui_GotoMenuButton1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GotoMenuButton1, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GotoMenuButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_ScheduleScreen);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 480);
    lv_obj_set_height(ui_Container2, 280);
    lv_obj_set_x(ui_Container2, 0);
    lv_obj_set_y(ui_Container2, 20);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SchedulePanelMain = lv_obj_create(ui_Container2);
    lv_obj_set_width(ui_SchedulePanelMain, 480);
    lv_obj_set_height(ui_SchedulePanelMain, 230);
    lv_obj_set_x(ui_SchedulePanelMain, 0);
    lv_obj_set_y(ui_SchedulePanelMain, 5);
    lv_obj_set_align(ui_SchedulePanelMain, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_SchedulePanelMain, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_SchedulePanelMain, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_remove_flag(ui_SchedulePanelMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SchedulePanelMain, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SchedulePanelMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SchedulePanelMain, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SchedulePanelMain, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SchedulePanelMain, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SchedulePanelMain, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SchedulePanelMain, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SchedulePanelMain, 0, LV_PART_SCROLLBAR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_SchedulePanelMain, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_SchedulePanelMain, 255, LV_PART_SCROLLBAR | LV_STATE_CHECKED);

    ui_SchedulePanel1 = lv_obj_create(ui_SchedulePanelMain);
    lv_obj_set_width(ui_SchedulePanel1, 460);
    lv_obj_set_height(ui_SchedulePanel1, 30);
    lv_obj_set_align(ui_SchedulePanel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SchedulePanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SchedulePanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SchedulePanel1, lv_color_hex(0x313031), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SchedulePanel1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SchedulePanel1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label45 = lv_label_create(ui_SchedulePanel1);
    lv_obj_set_width(ui_Label45, 30);
    lv_obj_set_height(ui_Label45, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label45, -10);
    lv_obj_set_y(ui_Label45, 0);
    lv_obj_set_align(ui_Label45, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label45, "1");
    lv_obj_set_style_text_align(ui_Label45, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label45, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label45, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label45, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label45, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label46 = lv_label_create(ui_SchedulePanel1);
    lv_obj_set_width(ui_Label46, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label46, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label46, 40);
    lv_obj_set_y(ui_Label46, 0);
    lv_obj_set_align(ui_Label46, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label46, "Schedule 1");
    lv_obj_set_style_text_font(ui_Label46, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button6 = lv_button_create(ui_SchedulePanel1);
    lv_obj_set_width(ui_Button6, 100);
    lv_obj_set_height(ui_Button6, 24);
    lv_obj_set_x(ui_Button6, 30);
    lv_obj_set_y(ui_Button6, 0);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button6, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label47 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label47, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label47, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label47, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label47, "MANUAL");
    lv_obj_set_style_text_font(ui_Label47, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_SchedulePanel1);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 20);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0x40765B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Switch1, lv_color_hex(0x5A846F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Switch1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Switch1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Switch1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Switch1, lv_color_hex(0x4A745F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Switch1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Switch1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Switch1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0x00FF7D), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0xB0CB79), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SchedulePanel2 = lv_obj_create(ui_SchedulePanelMain);
    lv_obj_set_width(ui_SchedulePanel2, 460);
    lv_obj_set_height(ui_SchedulePanel2, 30);
    lv_obj_set_align(ui_SchedulePanel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SchedulePanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SchedulePanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SchedulePanel2, lv_color_hex(0x313031), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SchedulePanel2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SchedulePanel2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label48 = lv_label_create(ui_SchedulePanel2);
    lv_obj_set_width(ui_Label48, 30);
    lv_obj_set_height(ui_Label48, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label48, -10);
    lv_obj_set_y(ui_Label48, 0);
    lv_obj_set_align(ui_Label48, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label48, "2");
    lv_obj_set_style_text_align(ui_Label48, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label48, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label48, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label48, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label48, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label49 = lv_label_create(ui_SchedulePanel2);
    lv_obj_set_width(ui_Label49, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label49, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label49, 40);
    lv_obj_set_y(ui_Label49, 0);
    lv_obj_set_align(ui_Label49, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label49, "Schedule 2");
    lv_obj_set_style_text_font(ui_Label49, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button7 = lv_button_create(ui_SchedulePanel2);
    lv_obj_set_width(ui_Button7, 100);
    lv_obj_set_height(ui_Button7, 24);
    lv_obj_set_x(ui_Button7, 30);
    lv_obj_set_y(ui_Button7, 0);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button7, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button7, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label50 = lv_label_create(ui_Button7);
    lv_obj_set_width(ui_Label50, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label50, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label50, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label50, "MANUAL");
    lv_obj_set_style_text_font(ui_Label50, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch2 = lv_switch_create(ui_SchedulePanel2);
    lv_obj_set_width(ui_Switch2, 50);
    lv_obj_set_height(ui_Switch2, 20);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0x40765B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Switch2, lv_color_hex(0x5A846F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Switch2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Switch2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Switch2, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Switch2, lv_color_hex(0x4A745F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Switch2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Switch2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Switch2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0x00FF7D), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch2, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0xB0CB79), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SchedulePanel3 = lv_obj_create(ui_SchedulePanelMain);
    lv_obj_set_width(ui_SchedulePanel3, 460);
    lv_obj_set_height(ui_SchedulePanel3, 30);
    lv_obj_set_align(ui_SchedulePanel3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SchedulePanel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SchedulePanel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SchedulePanel3, lv_color_hex(0x313031), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SchedulePanel3, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SchedulePanel3, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label51 = lv_label_create(ui_SchedulePanel3);
    lv_obj_set_width(ui_Label51, 30);
    lv_obj_set_height(ui_Label51, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label51, -10);
    lv_obj_set_y(ui_Label51, 0);
    lv_obj_set_align(ui_Label51, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label51, "3");
    lv_obj_set_style_text_align(ui_Label51, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label51, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label51, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label51, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label51, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label52 = lv_label_create(ui_SchedulePanel3);
    lv_obj_set_width(ui_Label52, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label52, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label52, 40);
    lv_obj_set_y(ui_Label52, 0);
    lv_obj_set_align(ui_Label52, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label52, "Schedule 3");
    lv_obj_set_style_text_font(ui_Label52, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button8 = lv_button_create(ui_SchedulePanel3);
    lv_obj_set_width(ui_Button8, 100);
    lv_obj_set_height(ui_Button8, 24);
    lv_obj_set_x(ui_Button8, 30);
    lv_obj_set_y(ui_Button8, 0);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button8, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button8, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label53 = lv_label_create(ui_Button8);
    lv_obj_set_width(ui_Label53, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label53, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label53, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label53, "MANUAL");
    lv_obj_set_style_text_font(ui_Label53, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch3 = lv_switch_create(ui_SchedulePanel3);
    lv_obj_set_width(ui_Switch3, 50);
    lv_obj_set_height(ui_Switch3, 20);
    lv_obj_set_align(ui_Switch3, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_bg_color(ui_Switch3, lv_color_hex(0x40765B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch3, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Switch3, lv_color_hex(0x5A846F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Switch3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Switch3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Switch3, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Switch3, lv_color_hex(0x4A745F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Switch3, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Switch3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Switch3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch3, lv_color_hex(0x00FF7D), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch3, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_Switch3, lv_color_hex(0xB0CB79), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch3, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SchedulePanel4 = lv_obj_create(ui_SchedulePanelMain);
    lv_obj_set_width(ui_SchedulePanel4, 460);
    lv_obj_set_height(ui_SchedulePanel4, 30);
    lv_obj_set_align(ui_SchedulePanel4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SchedulePanel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SchedulePanel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SchedulePanel4, lv_color_hex(0x313031), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SchedulePanel4, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SchedulePanel4, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label54 = lv_label_create(ui_SchedulePanel4);
    lv_obj_set_width(ui_Label54, 30);
    lv_obj_set_height(ui_Label54, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label54, -10);
    lv_obj_set_y(ui_Label54, 0);
    lv_obj_set_align(ui_Label54, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label54, "4");
    lv_obj_set_style_text_align(ui_Label54, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label54, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label54, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label54, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label54, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label55 = lv_label_create(ui_SchedulePanel4);
    lv_obj_set_width(ui_Label55, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label55, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label55, 40);
    lv_obj_set_y(ui_Label55, 0);
    lv_obj_set_align(ui_Label55, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label55, "Schedule 4");
    lv_obj_set_style_text_font(ui_Label55, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button9 = lv_button_create(ui_SchedulePanel4);
    lv_obj_set_width(ui_Button9, 100);
    lv_obj_set_height(ui_Button9, 24);
    lv_obj_set_x(ui_Button9, 30);
    lv_obj_set_y(ui_Button9, 0);
    lv_obj_set_align(ui_Button9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button9, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button9, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label56 = lv_label_create(ui_Button9);
    lv_obj_set_width(ui_Label56, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label56, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label56, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label56, "MANUAL");
    lv_obj_set_style_text_font(ui_Label56, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch4 = lv_switch_create(ui_SchedulePanel4);
    lv_obj_set_width(ui_Switch4, 50);
    lv_obj_set_height(ui_Switch4, 20);
    lv_obj_set_align(ui_Switch4, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_bg_color(ui_Switch4, lv_color_hex(0x40765B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch4, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Switch4, lv_color_hex(0x5A846F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Switch4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Switch4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Switch4, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Switch4, lv_color_hex(0x4A745F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Switch4, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Switch4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Switch4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch4, lv_color_hex(0x00FF7D), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch4, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_Switch4, lv_color_hex(0xB0CB79), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch4, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SchedulePanel5 = lv_obj_create(ui_SchedulePanelMain);
    lv_obj_set_width(ui_SchedulePanel5, 460);
    lv_obj_set_height(ui_SchedulePanel5, 30);
    lv_obj_set_align(ui_SchedulePanel5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SchedulePanel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SchedulePanel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SchedulePanel5, lv_color_hex(0x313031), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SchedulePanel5, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SchedulePanel5, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label57 = lv_label_create(ui_SchedulePanel5);
    lv_obj_set_width(ui_Label57, 30);
    lv_obj_set_height(ui_Label57, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label57, -10);
    lv_obj_set_y(ui_Label57, 0);
    lv_obj_set_align(ui_Label57, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label57, "5");
    lv_obj_set_style_text_align(ui_Label57, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label57, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label57, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label57, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label57, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label58 = lv_label_create(ui_SchedulePanel5);
    lv_obj_set_width(ui_Label58, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label58, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label58, 40);
    lv_obj_set_y(ui_Label58, 0);
    lv_obj_set_align(ui_Label58, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label58, "Schedule 5");
    lv_obj_set_style_text_font(ui_Label58, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button10 = lv_button_create(ui_SchedulePanel5);
    lv_obj_set_width(ui_Button10, 100);
    lv_obj_set_height(ui_Button10, 24);
    lv_obj_set_x(ui_Button10, 30);
    lv_obj_set_y(ui_Button10, 0);
    lv_obj_set_align(ui_Button10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button10, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button10, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label59 = lv_label_create(ui_Button10);
    lv_obj_set_width(ui_Label59, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label59, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label59, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label59, "MANUAL");
    lv_obj_set_style_text_font(ui_Label59, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch5 = lv_switch_create(ui_SchedulePanel5);
    lv_obj_set_width(ui_Switch5, 50);
    lv_obj_set_height(ui_Switch5, 20);
    lv_obj_set_align(ui_Switch5, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_bg_color(ui_Switch5, lv_color_hex(0x40765B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch5, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Switch5, lv_color_hex(0x5A846F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Switch5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Switch5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Switch5, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Switch5, lv_color_hex(0x4A745F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Switch5, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Switch5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Switch5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch5, lv_color_hex(0x00FF7D), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch5, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_Switch5, lv_color_hex(0xB0CB79), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch5, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SchedulePanel6 = lv_obj_create(ui_SchedulePanelMain);
    lv_obj_set_width(ui_SchedulePanel6, 460);
    lv_obj_set_height(ui_SchedulePanel6, 30);
    lv_obj_set_align(ui_SchedulePanel6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SchedulePanel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SchedulePanel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SchedulePanel6, lv_color_hex(0x313031), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SchedulePanel6, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SchedulePanel6, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label60 = lv_label_create(ui_SchedulePanel6);
    lv_obj_set_width(ui_Label60, 30);
    lv_obj_set_height(ui_Label60, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label60, -10);
    lv_obj_set_y(ui_Label60, 0);
    lv_obj_set_align(ui_Label60, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label60, "6");
    lv_obj_set_style_text_align(ui_Label60, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label60, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label60, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label60, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label60, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label61 = lv_label_create(ui_SchedulePanel6);
    lv_obj_set_width(ui_Label61, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label61, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label61, 40);
    lv_obj_set_y(ui_Label61, 0);
    lv_obj_set_align(ui_Label61, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label61, "Schedule 6");
    lv_obj_set_style_text_font(ui_Label61, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button11 = lv_button_create(ui_SchedulePanel6);
    lv_obj_set_width(ui_Button11, 100);
    lv_obj_set_height(ui_Button11, 24);
    lv_obj_set_x(ui_Button11, 30);
    lv_obj_set_y(ui_Button11, 0);
    lv_obj_set_align(ui_Button11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button11, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button11, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button11, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label62 = lv_label_create(ui_Button11);
    lv_obj_set_width(ui_Label62, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label62, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label62, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label62, "MANUAL");
    lv_obj_set_style_text_font(ui_Label62, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch6 = lv_switch_create(ui_SchedulePanel6);
    lv_obj_set_width(ui_Switch6, 50);
    lv_obj_set_height(ui_Switch6, 20);
    lv_obj_set_align(ui_Switch6, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_bg_color(ui_Switch6, lv_color_hex(0x40765B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch6, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Switch6, lv_color_hex(0x5A846F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Switch6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Switch6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Switch6, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Switch6, lv_color_hex(0x4A745F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Switch6, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Switch6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Switch6, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch6, lv_color_hex(0x00FF7D), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch6, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_Switch6, lv_color_hex(0xB0CB79), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch6, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Button13 = lv_button_create(ui_Container2);
    lv_obj_set_width(ui_Button13, 140);
    lv_obj_set_height(ui_Button13, 30);
    lv_obj_set_x(ui_Button13, 30);
    lv_obj_set_y(ui_Button13, -10);
    lv_obj_set_align(ui_Button13, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_Button13, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button13, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button13, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label64 = lv_label_create(ui_Button13);
    lv_obj_set_width(ui_Label64, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label64, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label64, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label64, "Edit");
    lv_obj_set_style_text_font(ui_Label64, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button12 = lv_button_create(ui_Container2);
    lv_obj_set_width(ui_Button12, 140);
    lv_obj_set_height(ui_Button12, 30);
    lv_obj_set_x(ui_Button12, -30);
    lv_obj_set_y(ui_Button12, -10);
    lv_obj_set_align(ui_Button12, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_Button12, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button12, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button12, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label63 = lv_label_create(ui_Button12);
    lv_obj_set_width(ui_Label63, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label63, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label63, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label63, "Clear All");
    lv_obj_set_style_text_font(ui_Label63, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_GotoMenuButton1, ui_event_GotoMenuButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button13, ui_event_Button13, LV_EVENT_ALL, NULL);

}

void ui_ScheduleScreen_screen_destroy(void)
{
    if(ui_ScheduleScreen) lv_obj_del(ui_ScheduleScreen);

    // NULL screen variables
    ui_ScheduleScreen = NULL;
    ui_ChangeConfigTitle5 = NULL;
    ui_ScheduleSetupstr = NULL;
    ui_GotoMenuButton1 = NULL;
    ui_Container2 = NULL;
    ui_SchedulePanelMain = NULL;
    ui_SchedulePanel1 = NULL;
    ui_Label45 = NULL;
    ui_Label46 = NULL;
    ui_Button6 = NULL;
    ui_Label47 = NULL;
    ui_Switch1 = NULL;
    ui_SchedulePanel2 = NULL;
    ui_Label48 = NULL;
    ui_Label49 = NULL;
    ui_Button7 = NULL;
    ui_Label50 = NULL;
    ui_Switch2 = NULL;
    ui_SchedulePanel3 = NULL;
    ui_Label51 = NULL;
    ui_Label52 = NULL;
    ui_Button8 = NULL;
    ui_Label53 = NULL;
    ui_Switch3 = NULL;
    ui_SchedulePanel4 = NULL;
    ui_Label54 = NULL;
    ui_Label55 = NULL;
    ui_Button9 = NULL;
    ui_Label56 = NULL;
    ui_Switch4 = NULL;
    ui_SchedulePanel5 = NULL;
    ui_Label57 = NULL;
    ui_Label58 = NULL;
    ui_Button10 = NULL;
    ui_Label59 = NULL;
    ui_Switch5 = NULL;
    ui_SchedulePanel6 = NULL;
    ui_Label60 = NULL;
    ui_Label61 = NULL;
    ui_Button11 = NULL;
    ui_Label62 = NULL;
    ui_Switch6 = NULL;
    ui_Button13 = NULL;
    ui_Label64 = NULL;
    ui_Button12 = NULL;
    ui_Label63 = NULL;

}
