// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: TemcoProject

#include "ui.h"

lv_obj_t * ui_StartUpScreen = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label2 = NULL;
// event funtions
void ui_event_StartUpScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 1000, 3000, &ui_HomeScreen_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        StartName_Animation(ui_Label1, 100);
        InitAnimation_Animation(ui_Label2, 1000);
    }
}

// build funtions

void ui_StartUpScreen_screen_init(void)
{
    ui_StartUpScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_StartUpScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_StartUpScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StartUpScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_StartUpScreen);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Tstate - 11");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Label1, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Label1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_StartUpScreen);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, 110);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Initialising . . .");
    lv_obj_set_scroll_dir(ui_Label2, LV_DIR_RIGHT);
    lv_obj_set_style_opa(ui_Label2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_StartUpScreen, ui_event_StartUpScreen, LV_EVENT_ALL, NULL);

}

void ui_StartUpScreen_screen_destroy(void)
{
    if(ui_StartUpScreen) lv_obj_del(ui_StartUpScreen);

    // NULL screen variables
    ui_StartUpScreen = NULL;
    ui_Label1 = NULL;
    ui_Label2 = NULL;

}
