// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: TemcoProject

#ifndef UI_SCHEDULESCREEN_H
#define UI_SCHEDULESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScheduleScreen
extern void ui_ScheduleScreen_screen_init(void);
extern void ui_ScheduleScreen_screen_destroy(void);
extern lv_obj_t * ui_ScheduleScreen;
extern lv_obj_t * ui_ChangeConfigTitle5;
extern lv_obj_t * ui_ScheduleSetupstr;
extern void ui_event_GotoMenuButton1(lv_event_t * e);
extern lv_obj_t * ui_GotoMenuButton1;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_SchedulePanelMain;
extern lv_obj_t * ui_SchedulePanel1;
extern lv_obj_t * ui_Label45;
extern lv_obj_t * ui_Label46;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label47;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_SchedulePanel2;
extern lv_obj_t * ui_Label48;
extern lv_obj_t * ui_Label49;
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label50;
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_SchedulePanel3;
extern lv_obj_t * ui_Label51;
extern lv_obj_t * ui_Label52;
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label53;
extern lv_obj_t * ui_Switch3;
extern lv_obj_t * ui_SchedulePanel4;
extern lv_obj_t * ui_Label54;
extern lv_obj_t * ui_Label55;
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label56;
extern lv_obj_t * ui_Switch4;
extern lv_obj_t * ui_SchedulePanel5;
extern lv_obj_t * ui_Label57;
extern lv_obj_t * ui_Label58;
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label59;
extern lv_obj_t * ui_Switch5;
extern lv_obj_t * ui_SchedulePanel6;
extern lv_obj_t * ui_Label60;
extern lv_obj_t * ui_Label61;
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Label62;
extern lv_obj_t * ui_Switch6;
extern void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Label64;
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Label63;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

