// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: TemcoProject

#ifndef UI_TIME_H
#define UI_TIME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Time
extern void ui_Time_screen_init(void);
extern void ui_Time_screen_destroy(void);
extern void ui_event_Time(lv_event_t * e);
extern lv_obj_t * ui_Time;
extern lv_obj_t * ui_ChangeConfigTitle3;
extern lv_obj_t * ui_NetworkSetupConfig5;
extern void ui_event_GotoMenuButton9(lv_event_t * e);
extern lv_obj_t * ui_GotoMenuButton9;
extern lv_obj_t * ui_SyncLocalPcCheckbox;
extern lv_obj_t * ui_Panel1;
extern void ui_event_ChangeTimeBtn(lv_event_t * e);
extern lv_obj_t * ui_ChangeTimeBtn;
extern lv_obj_t * ui_Label68;
extern void ui_event_ChangeDateBtn(lv_event_t * e);
extern lv_obj_t * ui_ChangeDateBtn;
extern lv_obj_t * ui_Label70;
extern lv_obj_t * ui_RefreshBtn;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_SyncWithPcBtn;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_UpdateLastServerSyncBtn2;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_SyncLocalPcCheckbox2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Dropdown5;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Dropdown4;
extern lv_obj_t * ui_UpdateLastServerSyncBtn;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_TimeSettingPopUp;
extern void ui_event_Button16(lv_event_t * e);
extern lv_obj_t * ui_Button16;
extern lv_obj_t * ui_Label69;
extern lv_obj_t * ui_TimePanel2;
extern lv_obj_t * ui_Dropdown11;
extern lv_obj_t * ui_Label67;
extern lv_obj_t * ui_Dropdown8;
extern void ui_event_Calendar3(lv_event_t * e);
extern lv_obj_t * ui_Calendar3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

