// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: TemcoProject

#ifndef UI_WIFICONFIG_H
#define UI_WIFICONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WifiConfig
extern void ui_WifiConfig_screen_init(void);
extern void ui_WifiConfig_screen_destroy(void);
extern void ui_event_WifiConfig(lv_event_t * e);
extern lv_obj_t * ui_WifiConfig;
extern lv_obj_t * ui_ChangeConfigTitle6;
extern lv_obj_t * ui_NetworkSetupConfig2;
extern void ui_event_GotoMenuButton6(lv_event_t * e);
extern lv_obj_t * ui_GotoMenuButton6;
extern lv_obj_t * ui_WifiContainer;
extern lv_obj_t * ui_WifiEnPanel;
extern lv_obj_t * ui_WifiEnableStr;
extern void ui_event_WifiEnSw(lv_event_t * e);
extern lv_obj_t * ui_WifiEnSw;
extern lv_obj_t * ui_WifiSsidPanel;
extern lv_obj_t * ui_SSIDStr;
extern void ui_event_SSIDText(lv_event_t * e);
extern lv_obj_t * ui_SSIDText;
extern void ui_event_Dropdown2(lv_event_t * e);
extern lv_obj_t * ui_Dropdown2;
extern lv_obj_t * ui_WifiPassPanel;
extern lv_obj_t * ui_PasswordStr1;
extern void ui_event_PasswordText(lv_event_t * e);
extern lv_obj_t * ui_PasswordText;
extern void ui_event_WifiUpdateButton(lv_event_t * e);
extern lv_obj_t * ui_WifiUpdateButton;
extern lv_obj_t * ui_Label9;
extern void ui_event_Keyboard(lv_event_t * e);
extern lv_obj_t * ui_Keyboard;
// CUSTOM VARIABLES
extern lv_obj_t * uic_WifiConfig;
extern lv_obj_t * uic_WifiEnSw;
extern lv_obj_t * uic_SSIDText;
extern lv_obj_t * uic_PasswordText;
extern lv_obj_t * uic_WifiUpdateButton;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

