// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: TemcoProject

#include "ui.h"

lv_obj_t * uic_WifiUpdateButton;
lv_obj_t * uic_PasswordText;
lv_obj_t * uic_SSIDText;
lv_obj_t * uic_WifiEnSw;
lv_obj_t * uic_WifiConfig;
lv_obj_t * ui_WifiConfig = NULL;
lv_obj_t * ui_ChangeConfigTitle6 = NULL;
lv_obj_t * ui_NetworkSetupConfig2 = NULL;
lv_obj_t * ui_GotoMenuButton6 = NULL;
lv_obj_t * ui_WifiContainer = NULL;
lv_obj_t * ui_WifiEnPanel = NULL;
lv_obj_t * ui_WifiEnableStr = NULL;
lv_obj_t * ui_WifiEnSw = NULL;
lv_obj_t * ui_WifiSsidPanel = NULL;
lv_obj_t * ui_SSIDStr = NULL;
lv_obj_t * ui_SSIDText = NULL;
lv_obj_t * ui_Dropdown2 = NULL;
lv_obj_t * ui_WifiPassPanel = NULL;
lv_obj_t * ui_PasswordStr1 = NULL;
lv_obj_t * ui_PasswordText = NULL;
lv_obj_t * ui_WifiUpdateButton = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Keyboard = NULL;
// event funtions
void ui_event_WifiConfig(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_GotoMenuButton6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainMenu, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 100, &ui_MainMenu_screen_init);
    }
}

void ui_event_WifiEnSw(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        WifiEnEvent(e);
    }
}

void ui_event_Dropdown2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SSIDShowEventFunc(e);
    }
}

void ui_event_PasswordText(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard,  ui_PasswordText);
        _ui_flag_modify(ui_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_WifiUpdateButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        UpdateWifiConfig(e);
        _ui_screen_change(&ui_MainMenu, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 1000, 100, &ui_MainMenu_screen_init);
    }
}

void ui_event_Keyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        WifiKeyboardPressFunc(e);
    }
}

// build funtions

void ui_WifiConfig_screen_init(void)
{
    ui_WifiConfig = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_WifiConfig, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ChangeConfigTitle6 = lv_obj_create(ui_WifiConfig);
    lv_obj_set_width(ui_ChangeConfigTitle6, 450);
    lv_obj_set_height(ui_ChangeConfigTitle6, 40);
    lv_obj_set_align(ui_ChangeConfigTitle6, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_ChangeConfigTitle6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ChangeConfigTitle6, lv_color_hex(0x2D70A0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChangeConfigTitle6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ChangeConfigTitle6, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NetworkSetupConfig2 = lv_label_create(ui_ChangeConfigTitle6);
    lv_obj_set_width(ui_NetworkSetupConfig2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NetworkSetupConfig2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NetworkSetupConfig2, -80);
    lv_obj_set_y(ui_NetworkSetupConfig2, 0);
    lv_obj_set_align(ui_NetworkSetupConfig2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NetworkSetupConfig2, "Wifi Setup");
    lv_obj_set_style_text_font(ui_NetworkSetupConfig2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GotoMenuButton6 = lv_imagebutton_create(ui_ChangeConfigTitle6);
    lv_imagebutton_set_src(ui_GotoMenuButton6, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_backsmallarrow_png, NULL);
    lv_imagebutton_set_src(ui_GotoMenuButton6, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_backsmallarrow_png, NULL);
    lv_obj_set_width(ui_GotoMenuButton6, 35);
    lv_obj_set_height(ui_GotoMenuButton6, 35);
    lv_obj_set_align(ui_GotoMenuButton6, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_radius(ui_GotoMenuButton6, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GotoMenuButton6, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GotoMenuButton6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiContainer = lv_obj_create(ui_WifiConfig);
    lv_obj_remove_style_all(ui_WifiContainer);
    lv_obj_set_width(ui_WifiContainer, 480);
    lv_obj_set_height(ui_WifiContainer, 290);
    lv_obj_set_align(ui_WifiContainer, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_WifiContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiEnPanel = lv_obj_create(ui_WifiContainer);
    lv_obj_set_width(ui_WifiEnPanel, 226);
    lv_obj_set_height(ui_WifiEnPanel, 30);
    lv_obj_set_align(ui_WifiEnPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WifiEnPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiEnPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiEnPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_WifiEnPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiEnableStr = lv_label_create(ui_WifiEnPanel);
    lv_obj_set_width(ui_WifiEnableStr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiEnableStr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiEnableStr, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_WifiEnableStr, "Wifi Enable");
    lv_obj_remove_flag(ui_WifiEnableStr,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_WifiEnableStr, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiEnSw = lv_switch_create(ui_WifiEnPanel);
    lv_obj_set_width(ui_WifiEnSw, 50);
    lv_obj_set_height(ui_WifiEnSw, 25);
    lv_obj_set_align(ui_WifiEnSw, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_WifiEnSw, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_WifiEnSw, lv_color_hex(0x868383), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiEnSw, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiSsidPanel = lv_obj_create(ui_WifiContainer);
    lv_obj_set_width(ui_WifiSsidPanel, 445);
    lv_obj_set_height(ui_WifiSsidPanel, 45);
    lv_obj_set_x(ui_WifiSsidPanel, 0);
    lv_obj_set_y(ui_WifiSsidPanel, -100);
    lv_obj_set_align(ui_WifiSsidPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WifiSsidPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiSsidPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiSsidPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_WifiSsidPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SSIDStr = lv_label_create(ui_WifiSsidPanel);
    lv_obj_set_width(ui_SSIDStr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SSIDStr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SSIDStr, -10);
    lv_obj_set_y(ui_SSIDStr, 0);
    lv_obj_set_align(ui_SSIDStr, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_SSIDStr, "SSID           :");
    lv_obj_remove_flag(ui_SSIDStr, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_style_text_font(ui_SSIDStr, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SSIDText = lv_textarea_create(ui_WifiSsidPanel);
    lv_obj_set_width(ui_SSIDText, 315);
    lv_obj_set_height(ui_SSIDText, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_align(ui_SSIDText, LV_ALIGN_RIGHT_MID);
    lv_textarea_set_max_length(ui_SSIDText, 64);
    lv_textarea_set_placeholder_text(ui_SSIDText, "Wifi SSID");
    lv_textarea_set_one_line(ui_SSIDText, true);
    lv_obj_add_flag(ui_SSIDText, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_SSIDText, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SSIDText, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown2 = lv_dropdown_create(ui_WifiSsidPanel);
    lv_dropdown_set_options(ui_Dropdown2, "SSID 1\nSSID 2\nSSID 3\nSSID 4\nSSID 5\nSSID 6\nSSID 7");
    lv_obj_set_width(ui_Dropdown2, 315);
    lv_obj_set_height(ui_Dropdown2, 35);
    lv_obj_set_align(ui_Dropdown2, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Dropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_radius(ui_Dropdown2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiPassPanel = lv_obj_create(ui_WifiContainer);
    lv_obj_set_width(ui_WifiPassPanel, 445);
    lv_obj_set_height(ui_WifiPassPanel, 45);
    lv_obj_set_x(ui_WifiPassPanel, 0);
    lv_obj_set_y(ui_WifiPassPanel, -55);
    lv_obj_set_align(ui_WifiPassPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WifiPassPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiPassPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiPassPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_WifiPassPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PasswordStr1 = lv_label_create(ui_WifiPassPanel);
    lv_obj_set_width(ui_PasswordStr1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PasswordStr1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PasswordStr1, -10);
    lv_obj_set_y(ui_PasswordStr1, 0);
    lv_obj_set_align(ui_PasswordStr1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_PasswordStr1, "Password  :");
    lv_obj_remove_flag(ui_PasswordStr1, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM);    /// Flags
    lv_obj_set_style_text_font(ui_PasswordStr1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PasswordText = lv_textarea_create(ui_WifiPassPanel);
    lv_obj_set_width(ui_PasswordText, 315);
    lv_obj_set_height(ui_PasswordText, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_align(ui_PasswordText, LV_ALIGN_RIGHT_MID);
    lv_textarea_set_max_length(ui_PasswordText, 36);
    lv_textarea_set_placeholder_text(ui_PasswordText, "Wifi Password");
    lv_textarea_set_one_line(ui_PasswordText, true);
    lv_obj_set_style_radius(ui_PasswordText, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PasswordText, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiUpdateButton = lv_button_create(ui_WifiContainer);
    lv_obj_set_width(ui_WifiUpdateButton, 100);
    lv_obj_set_height(ui_WifiUpdateButton, 30);
    lv_obj_set_x(ui_WifiUpdateButton, 180);
    lv_obj_set_y(ui_WifiUpdateButton, 120);
    lv_obj_set_align(ui_WifiUpdateButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiUpdateButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_WifiUpdateButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiUpdateButton, lv_color_hex(0x2971A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiUpdateButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_WifiUpdateButton);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Update");
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard = lv_keyboard_create(ui_WifiContainer);
    lv_obj_set_width(ui_Keyboard, 480);
    lv_obj_set_height(ui_Keyboard, 120);
    lv_obj_set_x(ui_Keyboard, 0);
    lv_obj_set_y(ui_Keyboard, 1);
    lv_obj_set_align(ui_Keyboard, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Keyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_border_side(ui_Keyboard, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Keyboard, 0, LV_PART_MAIN | LV_STATE_DISABLED);

    lv_obj_set_style_radius(ui_Keyboard, 30, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_GotoMenuButton6, ui_event_GotoMenuButton6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WifiEnSw, ui_event_WifiEnSw, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown2, ui_event_Dropdown2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PasswordText, ui_event_PasswordText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WifiUpdateButton, ui_event_WifiUpdateButton, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard, ui_SSIDText);
    lv_obj_add_event_cb(ui_Keyboard, ui_event_Keyboard, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WifiConfig, ui_event_WifiConfig, LV_EVENT_ALL, NULL);
    uic_WifiConfig = ui_WifiConfig;
    uic_WifiEnSw = ui_WifiEnSw;
    uic_SSIDText = ui_SSIDText;
    uic_PasswordText = ui_PasswordText;
    uic_WifiUpdateButton = ui_WifiUpdateButton;

}

void ui_WifiConfig_screen_destroy(void)
{
    if(ui_WifiConfig) lv_obj_del(ui_WifiConfig);

    // NULL screen variables
    uic_WifiConfig = NULL;
    ui_WifiConfig = NULL;
    ui_ChangeConfigTitle6 = NULL;
    ui_NetworkSetupConfig2 = NULL;
    ui_GotoMenuButton6 = NULL;
    ui_WifiContainer = NULL;
    ui_WifiEnPanel = NULL;
    ui_WifiEnableStr = NULL;
    uic_WifiEnSw = NULL;
    ui_WifiEnSw = NULL;
    ui_WifiSsidPanel = NULL;
    ui_SSIDStr = NULL;
    uic_SSIDText = NULL;
    ui_SSIDText = NULL;
    ui_Dropdown2 = NULL;
    ui_WifiPassPanel = NULL;
    ui_PasswordStr1 = NULL;
    uic_PasswordText = NULL;
    ui_PasswordText = NULL;
    uic_WifiUpdateButton = NULL;
    ui_WifiUpdateButton = NULL;
    ui_Label9 = NULL;
    ui_Keyboard = NULL;

}
