idf_component_register(
    SRCS
        "src/dynamic_display_api.c"
        "src/screen_flash_store.c"
    INCLUDE_DIRS
        "include"
    PRIV_INCLUDE_DIRS
        "src"
    REQUIRES
        esp_http_server
        spiffs
        json
        nvs_flash
    EMBED_TXTFILES
        "DefaultScreens/start_up_screen.json"
        "DefaultScreens/home_screen.json"
        "DefaultScreens/main_menu.json"
        "DefaultScreens/network_config.json"
        "DefaultScreens/parameters.json"
        "DefaultScreens/protocols.json"
        "DefaultScreens/schedule_edit_screen.json"
        "DefaultScreens/schedule_screen.json"
        "DefaultScreens/time.json"
        "DefaultScreens/wifi_config.json"
        "DefaultScreens/holiday_calender_screen.json"
        "DefaultScreens/wireguard_screen.json"
        "DefaultScreens/ddns_screen.json"
        "DefaultImages/1020677502.json"
        "DefaultImages/1207302323.json"
        "DefaultImages/1589547977.json"
        "DefaultImages/1679221590.json"
        "DefaultImages/1869774352.json"
        "DefaultImages/1984394067.json"
        "DefaultImages/444508050.json"
        "DefaultImages/backsmallarrow.json"
        "DefaultImages/displayhomescreendot.json"
        "DefaultImages/displayscreendotformenuscreen_gray.json"
        "DefaultImages/fan_auto_new.json"
        "DefaultImages/fan_small.json"
        "DefaultImages/fan_withtime.json"
        "DefaultImages/leftarrow.json"
        "DefaultImages/rightarrow.json"
        "DefaultImages/wifisym.json"
        "DefaultImages/wifisym_0.json"
        "DefaultImages/wifisym_1.json"
        "DefaultImages/wifisym_2.json"
        "DefaultImages/wifisym_3.json"
        "DefaultImages/wifisym_4.json"
        "DefaultImages/wifisym_Disable.json"
)
