#ifndef __REGISTERLIST_H
#define	__REGISTERLIST_H







typedef enum
{
	EEP_SERIALNUMBER_LOWORD = 0,
	EEP_SERIALNUMBER_HIWORD = EEP_SERIALNUMBER_LOWORD + 2,
	EEP_VERSION_NUMBER_LO = EEP_SERIALNUMBER_HIWORD + 2,
	EEP_VERSION_NUMBER_HI,
	EEP_ADDRESS,
	EEP_PRODUCT_MODEL,
	EEP_HARDWARE_REV,
	EEP_PIC_VER,
	EEP_BASE_ADDRESS,

	EEP_UPDATE_STATUS = 16,
	EEP_SERIALNUMBER_WRITE_FLAG,

	
	EEP_BAUDRATE,
	#ifdef T38AI8AO6DO
	EEP_AO_CHANNLE0 ,
	EEP_AO_CHANNLE1 = EEP_AO_CHANNLE0+2,
	EEP_AO_CHANNLE2 = EEP_AO_CHANNLE1+2 ,
	EEP_AO_CHANNLE3 = EEP_AO_CHANNLE2+2 ,
	EEP_AO_CHANNLE4 = EEP_AO_CHANNLE3+2,
	EEP_AO_CHANNLE5 = EEP_AO_CHANNLE4+2,
	EEP_AO_CHANNLE6 = EEP_AO_CHANNLE5+2,
	EEP_AO_CHANNLE7 = EEP_AO_CHANNLE6+2,
	EEP_DO_CHANNLE0	= EEP_AO_CHANNLE7+2,
	EEP_DO_CHANNLE1		,
	EEP_DO_CHANNLE2		,
	EEP_DO_CHANNLE3		,
	EEP_DO_CHANNLE4		,
	EEP_DO_CHANNLE5		,
	EEP_AI_FILTER0		,
	EEP_AI_FILTER1		,
	EEP_AI_FILTER2		,
	EEP_AI_FILTER3		,
	EEP_AI_FILTER4		,
	EEP_AI_FILTER5		,
	EEP_AI_FILTER6		,
	EEP_AI_FILTER7		,
	EEP_AI_RANGE0		,
	EEP_AI_RANGE1		,
	EEP_AI_RANGE2		,
	EEP_AI_RANGE3		,
	EEP_AI_RANGE4		,
	EEP_AI_RANGE5		,
	EEP_AI_RANGE6		,
	EEP_AI_RANGE7		,
	EEP_AI_OFFSET0		,
	EEP_AI_OFFSET1= EEP_AI_OFFSET0+2,
	EEP_AI_OFFSET2= EEP_AI_OFFSET1+2		,
	EEP_AI_OFFSET3= EEP_AI_OFFSET2+2		,
	EEP_AI_OFFSET4= EEP_AI_OFFSET3+2		,
	EEP_AI_OFFSET5= EEP_AI_OFFSET4+2		,
	EEP_AI_OFFSET6= EEP_AI_OFFSET5+2		,
	EEP_AI_OFFSET7= EEP_AI_OFFSET6+2		,
	#endif
	#ifdef T322AI
	EEP_AI_FILTER0	,
	EEP_AI_FILTER1	,
	EEP_AI_FILTER2	,
	EEP_AI_FILTER3	,
	EEP_AI_FILTER4	,
	EEP_AI_FILTER5	,
	EEP_AI_FILTER6	,
	EEP_AI_FILTER7	,
	EEP_AI_FILTER8	,
	EEP_AI_FILTER9	,
	EEP_AI_FILTER10	,
	EEP_AI_FILTER11	,
	EEP_AI_FILTER12	,
	EEP_AI_FILTER13	,
	EEP_AI_FILTER14	,
	EEP_AI_FILTER15	,
	EEP_AI_FILTER16	,
	EEP_AI_FILTER17	,
	EEP_AI_FILTER18	,
	EEP_AI_FILTER19	,
	EEP_AI_FILTER20	,
	EEP_AI_FILTER21	,
	EEP_AI_RANGE0		,
	EEP_AI_RANGE1		,
	EEP_AI_RANGE2		,
	EEP_AI_RANGE3		,
	EEP_AI_RANGE4		,
	EEP_AI_RANGE5		,
	EEP_AI_RANGE6		,
	EEP_AI_RANGE7		,
	EEP_AI_RANGE8		,
	EEP_AI_RANGE9		,
	EEP_AI_RANGE10		,
	EEP_AI_RANGE11		,
	EEP_AI_RANGE12		,
	EEP_AI_RANGE13	,
	EEP_AI_RANGE14		,
	EEP_AI_RANGE15		,
	EEP_AI_RANGE16		,
	EEP_AI_RANGE17		,
	EEP_AI_RANGE18		,
	EEP_AI_RANGE19		,
	EEP_AI_RANGE20		,
	EEP_AI_RANGE21		,
	EEP_AI_OFFSET0		,
	EEP_AI_OFFSET1= EEP_AI_OFFSET0+2,
	EEP_AI_OFFSET2= EEP_AI_OFFSET1+2		,
	EEP_AI_OFFSET3= EEP_AI_OFFSET2+2		,
	EEP_AI_OFFSET4= EEP_AI_OFFSET3+2		,
	EEP_AI_OFFSET5= EEP_AI_OFFSET4+2		,
	EEP_AI_OFFSET6= EEP_AI_OFFSET5+2		,
	EEP_AI_OFFSET7= EEP_AI_OFFSET6+2		,
	EEP_AI_OFFSET8= EEP_AI_OFFSET7+2		,
	EEP_AI_OFFSET9= EEP_AI_OFFSET8+2		,
	EEP_AI_OFFSET10= EEP_AI_OFFSET9+2		,
	EEP_AI_OFFSET11= EEP_AI_OFFSET10+2		,
	EEP_AI_OFFSET12= EEP_AI_OFFSET11+2		,
	EEP_AI_OFFSET13= EEP_AI_OFFSET12+2		,
	EEP_AI_OFFSET14= EEP_AI_OFFSET13+2		,
	EEP_AI_OFFSET15= EEP_AI_OFFSET14+2		,
	EEP_AI_OFFSET16= EEP_AI_OFFSET15+2		,
	EEP_AI_OFFSET17= EEP_AI_OFFSET16+2		,
	EEP_AI_OFFSET18= EEP_AI_OFFSET17+2		,
	EEP_AI_OFFSET19= EEP_AI_OFFSET18+2		,
	EEP_AI_OFFSET20= EEP_AI_OFFSET19+2		,
	EEP_AI_OFFSET21= EEP_AI_OFFSET20+2		,
	
	EEP_PLUSE0_HI_HI											,
	EEP_PLUSE0_HI_LO											,
	EEP_PLUSE0_LO_HI											,
	EEP_PLUSE0_LO_LO											,
	EEP_PLUSE1_HI_HI											,
	EEP_PLUSE1_HI_LO											,
	EEP_PLUSE1_LO_HI											,
	EEP_PLUSE1_LO_LO											,
	EEP_PLUSE2_HI_HI											,
	EEP_PLUSE2_HI_LO											,
	EEP_PLUSE2_LO_HI											,
	EEP_PLUSE2_LO_LO											,
	EEP_PLUSE3_HI_HI											,
	EEP_PLUSE3_HI_LO											,
	EEP_PLUSE3_LO_HI											,
	EEP_PLUSE3_LO_LO											,
	EEP_PLUSE4_HI_HI											,
	EEP_PLUSE4_HI_LO											,
	EEP_PLUSE4_LO_HI											,
	EEP_PLUSE4_LO_LO											,
	EEP_PLUSE5_HI_HI											,
	EEP_PLUSE5_HI_LO											,
	EEP_PLUSE5_LO_HI											,
	EEP_PLUSE5_LO_LO											,
	EEP_PLUSE6_HI_HI											,
	EEP_PLUSE6_HI_LO											,
	EEP_PLUSE6_LO_HI											,
	EEP_PLUSE6_LO_LO											,
	EEP_PLUSE7_HI_HI											,
	EEP_PLUSE7_HI_LO											,
	EEP_PLUSE7_LO_HI											,
	EEP_PLUSE7_LO_LO											,
	EEP_PLUSE8_HI_HI											,
	EEP_PLUSE8_HI_LO											,
	EEP_PLUSE8_LO_HI											,
	EEP_PLUSE8_LO_LO											,
	EEP_PLUSE9_HI_HI											,
	EEP_PLUSE9_HI_LO											,
	EEP_PLUSE9_LO_HI											,
	EEP_PLUSE9_LO_LO											,
	EEP_PLUSE10_HI_HI											,
	EEP_PLUSE10_HI_LO											,
	EEP_PLUSE10_LO_HI											,
	EEP_PLUSE10_LO_LO											,
	EEP_PLUSE11_HI_HI											,
	EEP_PLUSE11_HI_LO											,
	EEP_PLUSE11_LO_HI											,
	EEP_PLUSE11_LO_LO											,
	EEP_PLUSE12_HI_HI											,
	EEP_PLUSE12_HI_LO											,
	EEP_PLUSE12_LO_HI											,
	EEP_PLUSE12_LO_LO											,
	EEP_PLUSE13_HI_HI											,
	EEP_PLUSE13_HI_LO											,
	EEP_PLUSE13_LO_HI											,
	EEP_PLUSE13_LO_LO											,
	EEP_PLUSE14_HI_HI											,
	EEP_PLUSE14_HI_LO											,
	EEP_PLUSE14_LO_HI											,
	EEP_PLUSE14_LO_LO											,
	EEP_PLUSE15_HI_HI											,
	EEP_PLUSE15_HI_LO											,
	EEP_PLUSE15_LO_HI											,
	EEP_PLUSE15_LO_LO											,
	EEP_PLUSE16_HI_HI											,
	EEP_PLUSE16_HI_LO											,
	EEP_PLUSE16_LO_HI											,
	EEP_PLUSE16_LO_LO											,
	EEP_PLUSE17_HI_HI											,
	EEP_PLUSE17_HI_LO											,
	EEP_PLUSE17_LO_HI											,
	EEP_PLUSE17_LO_LO											,
	EEP_PLUSE18_HI_HI											,
	EEP_PLUSE18_HI_LO											,
	EEP_PLUSE18_LO_HI											,
	EEP_PLUSE18_LO_LO											,
	EEP_PLUSE19_HI_HI											,
	EEP_PLUSE19_HI_LO											,
	EEP_PLUSE19_LO_HI											,
	EEP_PLUSE19_LO_LO											,
	EEP_PLUSE20_HI_HI											,
	EEP_PLUSE20_HI_LO											,
	EEP_PLUSE20_LO_HI											,
	EEP_PLUSE20_LO_LO											,
	EEP_PLUSE21_HI_HI											,
	EEP_PLUSE21_HI_LO											,
	EEP_PLUSE21_LO_HI											,
	EEP_PLUSE21_LO_LO											,

	
	
	#endif

} EEP_MAP;

typedef enum
{
	MODBUS_SERIALNUMBER_LOWORD = 0,             
	MODBUS_SERIALNUMBER_HIWORD = 2,
	MODBUS_VERSION_NUMBER_LO = 4,
	MODBUS_VERSION_NUMBER_HI = 5,
	MODBUS_ADDRESS = 6,
	MODBUS_PRODUCT_MODEL,
	MODBUS_HARDWARE_REV,
	//MODBUS_PIC_VERSION,
	MODBUS_ADDRESS_PLUG_N_PLAY,
	MODBUS_BAUDRATE = 15,			// base address select
	MODBUS_UPDATE_STATUS = 16,			// status for update flash
	MODBUS_SERINALNUMBER_WRITE_FLAG = 99,
	
	
	
	#ifdef T38AI8AO6DO

	MODBUS_AO_CHANNLE0	= 100,
	MODBUS_AO_CHANNLE1  = 101,
	MODBUS_AO_CHANNLE2	= 102,
	MODBUS_AO_CHANNLE3  = 103,
	MODBUS_AO_CHANNLE4	= 104,
	MODBUS_AO_CHANNLE5  = 105,
	MODBUS_AO_CHANNLE6	= 106,
	MODBUS_AO_CHANNLE7  = 107,
	
	MODBUS_DO_CHANNLE0	= 108,
	MODBUS_DO_CHANNLE1  = 109,
	MODBUS_DO_CHANNLE2	= 110,
	MODBUS_DO_CHANNLE3  = 111,
	MODBUS_DO_CHANNLE4	= 112,
	MODBUS_DO_CHANNLE5	= 113,
	
	MODBUS_SWITCH_BANK0 = 114,
	MODBUS_SWITCH_BANK1 = 115,
	
	MODBUS_AI_CHANNLE0  = 116 ,
	MODBUS_AI_CHANNLE1  = 117 ,
	MODBUS_AI_CHANNLE2  = 118 ,
	MODBUS_AI_CHANNLE3  = 119 ,
	MODBUS_AI_CHANNLE4  = 120 ,
	MODBUS_AI_CHANNLE5  = 121 ,
	MODBUS_AI_CHANNLE6  = 122 ,
	MODBUS_AI_CHANNLE7  = 123 ,
	

	MODBUS_AI_FILTER0	= 200 ,
	MODBUS_AI_FILTER1	= 201 ,
	MODBUS_AI_FILTER2	= 202 ,
	MODBUS_AI_FILTER3	= 203 ,
	MODBUS_AI_FILTER4	= 204 ,
	MODBUS_AI_FILTER5	= 205 ,
	MODBUS_AI_FILTER6	= 206 ,
	MODBUS_AI_FILTER7	= 207 ,

	
	MODBUS_AI_RANGE0  =   225,
	MODBUS_AI_RANGE1  =   226,
	MODBUS_AI_RANGE2  =   227,
	MODBUS_AI_RANGE3  =   228,
	MODBUS_AI_RANGE4  =   229,
	MODBUS_AI_RANGE5  =   230,
	MODBUS_AI_RANGE6  =   231,
	MODBUS_AI_RANGE7  =   232,


	
	MODBUS_AI_OFFSET0  = 250 ,
	MODBUS_AI_OFFSET1  = 251 ,
	MODBUS_AI_OFFSET2  = 252 ,
	MODBUS_AI_OFFSET3  = 253 ,
	MODBUS_AI_OFFSET4  = 254 ,
	MODBUS_AI_OFFSET5  = 255 ,
	MODBUS_AI_OFFSET6  = 256 ,
	MODBUS_AI_OFFSET7  = 257 ,

	#elif T322AI
	MODBUS_AI_CHANNLE0_HI  = 100 ,
	MODBUS_AI_CHANNLE0_LO  = 101 ,
	MODBUS_AI_CHANNLE1_HI  = 102 ,
	MODBUS_AI_CHANNLE1_LO  = 103 ,
	MODBUS_AI_CHANNLE2_HI  = 104 ,
	MODBUS_AI_CHANNLE2_LO  = 105 ,
	MODBUS_AI_CHANNLE3_HI  = 106 ,
	MODBUS_AI_CHANNLE3_LO  = 107 ,
	MODBUS_AI_CHANNLE4_HI  = 108 ,
	MODBUS_AI_CHANNLE4_LO  = 109 ,
	MODBUS_AI_CHANNLE5_HI  = 110 ,
	MODBUS_AI_CHANNLE5_LO  = 111 ,
	MODBUS_AI_CHANNLE6_HI  = 112 ,
	MODBUS_AI_CHANNLE6_LO  = 113 ,
	MODBUS_AI_CHANNLE7_HI  = 114 ,
	MODBUS_AI_CHANNLE7_LO  = 115 ,
	MODBUS_AI_CHANNLE8_HI  = 116 ,
	MODBUS_AI_CHANNLE8_LO  = 117 ,
	MODBUS_AI_CHANNLE9_HI  = 118 ,	
	MODBUS_AI_CHANNLE9_LO  = 119 ,
	MODBUS_AI_CHANNLE10_HI  = 120 ,
	MODBUS_AI_CHANNLE10_LO  = 121 ,
	MODBUS_AI_CHANNLE11  = 122 ,
	MODBUS_AI_CHANNLE12  = 123 ,
	MODBUS_AI_CHANNLE13  = 124 ,
	MODBUS_AI_CHANNLE14  = 125 ,
	MODBUS_AI_CHANNLE15  = 126 ,
	MODBUS_AI_CHANNLE16  = 127 ,
	MODBUS_AI_CHANNLE17  = 128 ,
	MODBUS_AI_CHANNLE18  = 129 ,
	MODBUS_AI_CHANNLE19  = 130 ,
	MODBUS_AI_CHANNLE20  = 131 ,
	MODBUS_AI_CHANNLE21  = 132 ,
	
	MODBUS_AI_FILTER0	= 200 ,
	MODBUS_AI_FILTER1	= 201 ,
	MODBUS_AI_FILTER2	= 202 ,
	MODBUS_AI_FILTER3	= 203 ,
	MODBUS_AI_FILTER4	= 204 ,
	MODBUS_AI_FILTER5	= 205 ,
	MODBUS_AI_FILTER6	= 206 ,
	MODBUS_AI_FILTER7	= 207 ,
	MODBUS_AI_FILTER8	= 208 ,
	MODBUS_AI_FILTER9	= 209 ,
	MODBUS_AI_FILTER10	= 210 ,
	MODBUS_AI_FILTER11	= 211 ,
	MODBUS_AI_FILTER12	= 212 ,
	MODBUS_AI_FILTER13	= 213 ,
	MODBUS_AI_FILTER14	= 214 ,
	MODBUS_AI_FILTER15	= 215 ,
	MODBUS_AI_FILTER16	= 216 ,
	MODBUS_AI_FILTER17	= 217 ,
	MODBUS_AI_FILTER18	= 218 ,
	MODBUS_AI_FILTER19	= 219 ,
	MODBUS_AI_FILTER20	= 220 ,
	MODBUS_AI_FILTER21	= 221 ,
	
	MODBUS_AI_RANGE0  =   225,
	MODBUS_AI_RANGE1  =   226,
	MODBUS_AI_RANGE2  =   227,
	MODBUS_AI_RANGE3  =   228,
	MODBUS_AI_RANGE4  =   229,
	MODBUS_AI_RANGE5  =   230,
	MODBUS_AI_RANGE6  =   231,
	MODBUS_AI_RANGE7  =   232,
	MODBUS_AI_RANGE8  =   233,
	MODBUS_AI_RANGE9  =   234,
	MODBUS_AI_RANGE10  =   235,
	MODBUS_AI_RANGE11  =   236,
	MODBUS_AI_RANGE12  =   237,
	MODBUS_AI_RANGE13  =   238,
	MODBUS_AI_RANGE14  =   239,
	MODBUS_AI_RANGE15  =   240,
	MODBUS_AI_RANGE16  =   241,
	MODBUS_AI_RANGE17  =   242,
	MODBUS_AI_RANGE18  =   243,
	MODBUS_AI_RANGE19  =   244,
	MODBUS_AI_RANGE20  =   245,
	MODBUS_AI_RANGE21  =   246,
	
	MODBUS_AI_OFFSET0  = 250 ,
	MODBUS_AI_OFFSET1  = 251 ,
	MODBUS_AI_OFFSET2  = 252 ,
	MODBUS_AI_OFFSET3  = 253 ,
	MODBUS_AI_OFFSET4  = 254 ,
	MODBUS_AI_OFFSET5  = 255 ,
	MODBUS_AI_OFFSET6  = 256 ,
	MODBUS_AI_OFFSET7  = 257 ,
	MODBUS_AI_OFFSET8  = 258 ,
	MODBUS_AI_OFFSET9  = 259 ,
	MODBUS_AI_OFFSET10 = 260 ,
	MODBUS_AI_OFFSET11 = 261 ,
	MODBUS_AI_OFFSET12 = 262 ,
	MODBUS_AI_OFFSET13 = 263 ,
	MODBUS_AI_OFFSET14 = 264 ,
	MODBUS_AI_OFFSET15 = 265 ,
	MODBUS_AI_OFFSET16 = 266 ,
	MODBUS_AI_OFFSET17 = 267 ,
	MODBUS_AI_OFFSET18 = 268 ,
	MODBUS_AI_OFFSET19 = 269 ,
	MODBUS_AI_OFFSET20 = 270 ,
	MODBUS_AI_OFFSET21 = 271 ,
	#endif
	 MODBUS_TEST1 = 801 ,
	 MODBUS_TEST2 = 802 ,
	 MODBUS_TEST3 = 803 ,
	 MODBUS_TEST4 = 804 ,
	 MODBUS_TEST5 = 805 ,
	 MODBUS_TEST6 = 806 ,
	 
	MODBUS_TEST7 ,
	MODBUS_TEST8 ,
	MODBUS_TEST9 ,
	MODBUS_TEST10,
	MODBUS_TEST11,
	MODBUS_TEST12,
	MODBUS_TEST13,
	MODBUS_TEST14,
	MODBUS_TEST15,

} 
MODBUS_REGISTER_LIST;























































 




#endif
