name: Build Firmware

on:
  push:
    branches:
      - "**"

  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: espressif/idf:v5.5.3

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Show ESP-IDF Version
        run: |
          . /opt/esp/idf/export.sh
          idf.py --version

      - name: Add Custom Components
        run: |
          cp -r temco_bacnet /opt/esp/idf/components/
          cp -r temco_IO_control /opt/esp/idf/components/

      - name: Build
        run: |
          . /opt/esp/idf/export.sh
          idf.py fullclean
          idf.py build

      - name: Upload Firmware Files
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            build/bootloader/bootloader.bin
            build/partition_table/partition-table.bin
            build/*.bin