name: ESP-Matter Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup ESP-IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.5.3

      - name: Build
        run: |
          . $IDF_PATH/export.sh
          idf.py build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/*.bin
